### ISSUE TITLE
make demo failing

### ISSUE THREAD

**Issue by delapsley** [contiv/netplugin#1027]
## Description

I cloned the net plugin repo into my Ubuntu Xenial development machine. "make demo" failed to execute correctly.

#### Expected Behavior

Make would execute successfully.

#### Observed Behavior

Make terminated with the following error:

==> netplugin-node1: Skipping Go reinstall
==> netplugin-node1: Removed symlink /etc/systemd/system/multi-user.target.wants/NetworkManager.service.
==> netplugin-node1: Removed symlink /etc/systemd/system/dbus-org.freedesktop.NetworkManager.service.
==> netplugin-node1: Removed symlink /etc/systemd/system/dbus-org.freedesktop.nm-dispatcher.service.
==> netplugin-node1: Remove the unneeded ceph repository if it exists
==> netplugin-node1: Loaded plugins: fastestmirror
==> netplugin-node1: Cleaning repos: base docker-main-repo epel extras rdo-qemu-ev updates
==> netplugin-node1:               : yum.dockerproject.org_repo_main_centos_7_
==> netplugin-node1: Cleaning up everything
==> netplugin-node1: Docker 1.12.6 is already installed
==> netplugin-node1: Cleaning up the Docker directory
==> netplugin-node1: Redirecting to /bin/systemctl stop  docker.service
==> netplugin-node1: mkdir: cannot create directory ‘/etc/systemd/system/docker.service.d’: File exists
==> netplugin-node1: [Service]
==> netplugin-node1: Environment="no_proxy=192.168.2.10,192.168.2.11,192.168.2.12,127.0.0.1,localhost,netmaster" "http_proxy=" "https_proxy="
==> netplugin-node1: Redirecting to /bin/systemctl restart  docker.service
==> netplugin-node1: Running provisioner: shell...
    netplugin-node1: Running: inline script
==> netplugin-node1: Running provisioner: shell...
    netplugin-node1: Running: inline script
==> netplugin-node1: ++ echo '#!/bin/bash'
==> netplugin-node1: ++ echo 'etcd --name netplugin-node1 --data-dir /var/lib/etcd  -heartbeat-interval=100 -election-timeout=5000  --listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001  --advertise-client-urls http://192.168.2.10:2379,http://192.168.2.10:4001  --initial-advertise-peer-urls http://192.168.2.10:2380,http://192.168.2.10:7001  --listen-peer-urls http://192.168.2.10:2380  --initial-cluster netplugin-node1=http://192.168.2.10:2380,netplugin-node1=http://192.168.2.10:7001,netplugin-node2=http://192.168.2.11:2380,netplugin-node2=http://192.168.2.11:7001,netplugin-node3=http://192.168.2.12:2380,netplugin-node3=http://192.168.2.12:7001 --initial-cluster-state new'
==> netplugin-node1: ++ chmod +x /usr/bin/etcd.sh
==> netplugin-node1: ++ cp /opt/gopath/src/github.com/contiv/netplugin/scripts/etcd.service /etc/systemd/system/etcd.service
==> netplugin-node1: cp: cannot stat ‘/opt/gopath/src/github.com/contiv/netplugin/scripts/etcd.service’: No such file or directory
==> netplugin-node1: ++ echo '#!/bin/bash'
==> netplugin-node1: ++ echo 'consul agent -server  -bootstrap-expect=3  -bind=192.168.2.10 -data-dir /opt/consul'
==> netplugin-node1: ++ chmod +x /usr/bin/consul.sh
==> netplugin-node1: ++ cp /opt/gopath/src/github.com/contiv/netplugin/scripts/consul.service /etc/systemd/system/consul.service
==> netplugin-node1: cp: cannot stat ‘/opt/gopath/src/github.com/contiv/netplugin/scripts/consul.service’: No such file or directory
==> netplugin-node1: ++ systemctl daemon-reload
==> netplugin-node1: ++ systemctl enable etcd
==> netplugin-node1: Failed to execute operation: No such file or directory
==> netplugin-node1: ++ exit 1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
Makefile:132: recipe for target 'start' failed
make: *** [start] Error 1

## Steps to Reproduce (for bugs)

1. $ cd ~/repos/
2. $ git clone git@github.com:contiv/netplugin.git
3. $ cd netplugin
4. $ export GOPATH=`pwd`
5. $ make demo
6. 

## Your Environment

- Ubuntu  Xenial operating system
- Master branch of netgplugin (latest commit: 7ff78e84a70626b9aee429c83fb357cb81df8a45)

**Comment by dseevr** [comment]
According to our [Vagrantfile](https://github.com/contiv/netplugin/blob/7ff78e84a70626b9aee429c83fb357cb81df8a45/Vagrantfile#L367-L371), if you have a GOPATH set, the `netplugin` directory needs to be at `$GOPATH/src/github.com/netplugin`

If you don't have one set, the current directory is shared at the correct location inside the VM.

If you do have a GOPATH set, the expectation is that your entire GOPATH should be shared into the VM in case you are building the code from scratch.  A bunch of the Makefile targets use the same Vagrantfile to bring up a VM used to compile the code.

We should modify the instructions to point out that you must create the netplugin repo in the correct spot if GOPATH is set.

**Comment by dseevr** [comment]
Please reopen the issue if you are still having issue with the instructions in the README
