### ISSUE TITLE
contiv is starting ovsdb-server in Debug mode

### ISSUE THREAD

**Issue by sbskas** [contiv/netplugin#1059]
## Description
The ovsInit.sh is starting the ovsdb-server in debug mode.
Heres the line in the ovsInit.sh startup script:
`ovsdb-server --remote=punix:/var/run/openvswitch/db.sock --remote=db:Open_vSwitch,Open_vSwitch,manager_options \
--private-key=db:Open_vSwitch,SSL,private_key \
--certificate=db:Open_vSwitch,SSL,certificate --bootstrap-ca-cert=db:Open_vSwitch,SSL,ca_cert \
--log-file=/var/contiv/log/ovs-db.log \
-vsyslog:dbg -vfile:dbg --pidfile --detach /etc/openvswitch/conf.db`

#### Expected Behavior
Logs should be rotated and compressed every day to keep the netplugin logs volume low.

#### Observed Behavior
The logs are filling up the /var/contiv directory at high rate, causing disk pressure and disabling completely the node when there is not any space left.
There is no easy way to change this behavior, most of the logs are useless in a production env.

## Steps to Reproduce (for bugs)
N/A 
## Your Environment
* netctl version : 1.1.6
* Orchestrator version (e.g. kubernetes, mesos, swarm): 1.8.3
* Operating System and version : Rhel 7.4 and Fedora 26

**Comment by kahou82** [comment]
https://github.com/contiv/netplugin/pull/1075

**Comment by sbskas** [comment]
What about the kubernetes part ?

**Comment by dseevr** [comment]
Gonna close this as the change has been merged.  This will go out in the 1.1.8 release
