### ISSUE TITLE
Provide a REST interface/endpoint for netmaster and run it as a daemon

### ISSUE THREAD

**Issue by mapuri** [contiv/netplugin#108]
*netmaster* represents the interface that faces the management-function. It performs **state-translation** and **resource-allocation** operations before triggering **netplugin** instance to perform host level provisioning of networks and endpoints.

Right now the way to push configuration and query runtime state for networks and endpoints in *netmaster* is through netdcli tool. This issue tracks providing a REST endpoint for the same. To begin with, we need to support following REST interfaces to match up netdcli functionality.

**Usecases**:
- While using *netdcli* has served the purpose for initial part, it does have a limitation of consistent integration with other agents (in terms of error reporting; structured responses etc). Also this requires passing some redundant information to netdcli whenever it is invoked (like state-store info) in every call, that can be set just once in a netmaster daemon.
- It will also help starting up netplugin infra with a default configuration (to promote battery included model as asked in #106)

Filing this issue to see if this will be useful.

**Interface Details:**

**Note** that after this change netdcli will need to be modified to internally make use of the netmaster's REST interface. Also note that to keep changes simple this issue doesn't intentionally deal with multiple instances of *netmaster* working as a single logical entity yet. 

1.  `netdcli -cfg <config from file or stdin>`
Request:
    POST: /v1/cfg/
    Headers:
    Body: json config
Response:
a.    Code: 200 
       Body: empty
b.    Code: 500 
       Body: error-string

2. `netdcli -add-cfg <config from file or stdin>`
Request:
    POST: /v1/add-cfg/
    Headers:
    Body: json config
Response:
a.    Code: 200 
       Body: empty
b.    Code: 500 
       Body: error-string

3. `netdcli -del-cfg <config from file or stdin>`
Request:
    POST: /v1/del-cfg/
    Headers:
    Body: json config
Response:
a.    Code: 200 
       Body: empty
b.    Code: 500 
       Body: error-string

4. `netdcli -host-bindings-cfg <config from file or stdin>`
Request:
    POST: /v1/host-bindings-cfg
    Headers:
    Body: json config
Response:
a.    Code: 200 
       Body: empty
b.    Code: 500 
       Body: error-string

5. `netdcli -oper get -construct network <id>`
Request:
    GET /v1/network/<id>
Response:
    Code: 200
    Body: json encoded list of operational network state

6. `netdcli -oper get -construct endpoint <id>`
Request:
    GET /v1/endpoint/<id>
Response:
    Code: 200
    Body: json encoded operational endpoint state

7. List networks
Request:
    GET /v1/networks/
Response: 
    Code: 200
    Body: json encoded list of operational network state. Empty list if no networks are operational.

8. List endpoints
Request:
    GET /v1/endpoints/
Response: 
    Code: 200
    Body: json encoded list of operational endpoint state. Empty list if no endpoints are operational.

**Comment by jainvipin** [comment]
@mapuri - this is a good idea, but like you pointed out we need to start versioning. Do we need the json response itself should contain the version; also need documentation for this.

**Comment by mapuri** [comment]
> this is a good idea, but like you pointed out we need to start versioning

Yeah, I haven't dug much around versioning but we do need it as this is going to be user/agent facing interface. We have a couple of options around that, one is embedding it in the REST uri, alternatively  we can have them in the json body itself. I showed option 1 here as that seemed more explicit.

> Do we need the json response itself should contain the version

I think this might not be needed if whatever version the client request contains it shall expect the response with same version (i.e. client doesn't get to reject a response). If the server doesn't support a version then it will fail with appropriate error.

> also need documentation for this.

Yes, I agree. I wanted to check if this will be useful before beginning to work on it. Right now I am thinking we can start with offering same netmaster functionality as today albeit behind a REST endpoint.

**Comment by erikh** [comment]
> Yeah, I haven't dug much around versioning but we do need it as this is going to be user/agent facing interface. We have a couple of options around that, one is embedding it in the REST uri, alternatively we can have them in the json body itself. I showed option 1 here as that seemed more explicit.
> 
> Do we need the json response itself should contain the version
> 
> I think this might not be needed if whatever version the client request contains it shall expect the response with same version (i.e. client doesn't get to reject a response). If the server doesn't support a version then it will fail with appropriate error.
> 
> also need documentation for this.
> 
> Yes, I agree. I wanted to check if this will be useful before beginning to work on it. Right now I am thinking we can start with offering same netmaster functionality as today albeit behind a REST endpoint.
> 
> 

FWIW, docker is doing this with Accept: headers; just another option to consider.

-Erik
