### ISSUE TITLE
Update design.md 

### ISSUE THREAD

**Issue by mapuri** [contiv/netplugin#109]
Update design document to cover recent changes around netmaster and netplugin separation.

Also add sections/quick-start-guide for network-function developers to help them start writing their drivers using the netplugin infra.

**Comment by gaurav-dalvi** [comment]
@mapuri : Can we close this issue ?

**Comment by mapuri** [comment]
yes, this is an old issue. Let's open new issue if needed.

**Comment by gaurav-dalvi** [comment]
Closing it !
