### ISSUE TITLE
implement an alternate network-driver

### ISSUE THREAD

**Issue by mapuri** [contiv/netplugin#110]
Right now we have a single ovs based network implementation. We need to implement an alternate network-driver using netplugin infra (could be using linux bridge, mac vlan etc).

The idea is to identify missing pieces and tighten up existing interfaces that netplugin exposes to the network drivers. And hopefully identify a more concrete development process for the folks looking forward to using netplugin infra for it's advantages of ease of integration with supported management functions (kubernetes, libnetwork and more coming soon)

**Comment by abhinandanpb** [comment]
Closing this issue. We can reopen it when newer integration proposals come in .
