### ISSUE TITLE
netdcli cleanup

### ISSUE THREAD

**Issue by mapuri** [contiv/netplugin#112]
netdcli has continued to keep some code from the time it was added earlier as more of a debug/test utility. Some of this code is not maintained or tested and might be ok to remove. This shall result in a removing a lot if unused code; reduce maintenance overheads and keep netdcli a tool that users can continue to play with without issues. 

I am filing this issue to get a general opinion before proceeding with this code cleanup in case. So please let me know.

I think we can remove following options:
- options to `create`/`delete` concrete configuration for networks
- options to `create`/`attach`/`detach`/`delete` concrete configuration for endpoints

Note that the options above can still be performed by using the `-cfg`, `-add-cfg`, `-del-cfg` and `-host-bindings-cfg` flags, that take logical configuration and takes the code path that is maintained and tested.

ping @jainvipin

**Comment by shaleman** [comment]
Closing this since netdcli will be deprecated
