### ISSUE TITLE
Is netmaster and netplugin to connection etcd of haved cert?

### ISSUE THREAD

**Issue by xiaodan1** [contiv/netplugin#1158]
My etcd cluster is config cert, 
![image](https://user-images.githubusercontent.com/22994530/46856660-98fd6080-ce39-11e8-93f9-2c95e209c3b3.png)
,
![image](https://user-images.githubusercontent.com/22994530/46856403-e927f300-ce38-11e8-8231-c3cccfa0631f.png)
Can the netmaster and netplugin is to connection etcd cluster of require authentication?

**Comment by liucimin** [comment]
not yet
