### ISSUE TITLE
Add version support for netmaster API or intent

### ISSUE THREAD

**Issue by mapuri** [contiv/netplugin#116]
This issue shall track discussion for adding version support to the netmaster API.

Below are a few choices:
- use the version info in the REST URL. Example: POST /**v1.0**/endpoint/<uuid>
- follow libnetwork like approach as done here: https://github.com/docker/libnetwork/pull/227/
- alternatively, put the version info in the `intent.Config` itself which is the structure that is generated or fetched as part of the REST endpoints exposed.

**Comment by erikh** [comment]
I think the first, or second options will make routing (and cases based on different routes) easiest.

-Erik

**Comment by abhinandanpb** [comment]
REST APIs are versioned now. Closing the issue
