### ISSUE TITLE
Netplugin whether to support multi etcd?

### ISSUE THREAD

**Issue by xiaodan1** [contiv/netplugin#1163]
contiv version: 1.2.0
etcd version: 3.2.9

on netplugin node:
![image](https://user-images.githubusercontent.com/22994530/52705575-30c4b400-2fbe-11e9-81cd-78f99b521994.png)

I stop etcd at 10.110.13.220, but etcd of 10.110.13.210 and 10.110.13.219 is working.
The log of netplguin is :
![image](https://user-images.githubusercontent.com/22994530/52705794-bf393580-2fbe-11e9-9a34-531cac511af2.png)

**Comment by liucimin** [comment]
https://github.com/contiv/netplugin/pull/1147

**Comment by xiaodan1** [comment]
I already read  #1147, but my problem still exist. I also comparison the code of "netplugin-release-1.2" and #1147 "Files changed".

In  "**/usr/bin/netplugin --mode kubernetes --netmode vlan --vlan-uplinks eth1 --fwdmode bridge --etcd-endpoints http://10.110.13.220:2379,http://10.110.13.210:2379,http://10.110.13.219:2379**" , 
 "--etcd-endpoints http://10.110.13.220:2379,http://10.110.13.210:2379,http://10.110.13.219:2379"
 Is it correct of the writing method ?
Or "--etcd-endpoints http://10.110.13.220:2379,--etcd-endpoints http://10.110.13.210:2379,--etcd-endpoints http://10.110.13.219:2379" , Which is right?

**Comment by liucimin** [comment]
First #1147 is not merge.You should merge it by your self.

Second, the args should like this 
--etcd-endpoints http://10.110.13.220:2379,http://10.110.13.210:2379,http://10.110.13.219:2379

Third, the etcd's ports 2379 maybe https? Unfortunly the contiv just support http.
So your etcd should use 2380 or other ports?See your etcd config.

**Comment by xiaodan1** [comment]
Thanks.
