### ISSUE TITLE
netmaster client: state management

### ISSUE THREAD

**Issue by erikh** [contiv/netplugin#122]
Retrieving state currently works in the client like this:

1. Call the appropriate Get operation, get a `[]byte` back
1. Unmarshal the JSON into the appropriate type
1. Use the type with the attributes you need to perform your operation

I would suggest we return `map[string]interface{}`, or perhaps `[]map[string]interface{}` in appropriate situations, which would allow the consumer to drill down into the properties they care about.

**Comment by shaleman** [comment]
New contivmodel client works differently now.
Closing this issue
