### ISSUE TITLE
Error running make unit-test

### ISSUE THREAD

**Issue by arunabha** [contiv/netplugin#124]
I'm getting the following error when running make unit-test

Godeps/_workspace/src/github.com/vishvananda/netlink/netlink.go:14:2: no buildable Go source files in /Users/agh/opt/software/go/src/github.com/contiv/netplugin/Godeps/_workspace/src/github.com/vishvananda/netlink/nl

Any help is appreciated

**Comment by erikh** [comment]
What platform are you building for? Linux/AMD64?

-Erik

**Comment by mapuri** [comment]
@arunabha, are you seeing this with with Mac OSX by any chance? netplugin uses the vishvananda/netlink library that can't be built on Mac currently as per comments in (https://github.com/vishvananda/netlink/issues/17)

You might want build netplugin in a linux vm or server for now.

Let me try and see if we can somehow address the OSX limitation locally in netplugin builds.

**Comment by arunabha** [comment]
Thanks for the reply. Yes, I'm building on Mac. I'll try building it on a
VM.

**Comment by jainvipin** [comment]
@arunabha - you might find instructions at https://github.com/contiv/netplugin/pull/119 helpful in setting up the VM. If you are interested in doing system tests i.e. multiple hosts then you'd need to run the tests on a bare-metal, which can spawn multiple VMs for you.

@mapuri, @erikh, @shaleman  - per our other discussion, it would be wonderful to get 'make demo' work directly off on a MAC i.e. launching vagrant VMs, etc.

**Comment by mapuri** [comment]
closing this issue. I will open a new one to track building netplugin project independent of host OS
