### ISSUE TITLE
Have netplugin build inside a VM

### ISSUE THREAD

**Issue by mapuri** [contiv/netplugin#125]
This shall minimize the host side requirements and save users from problems like #124

**Comment by rschmied** [comment]
What would be the difference from #119 as that one also explains setting up a VM environment?

**Comment by mapuri** [comment]
@rschmied 

This is tracking an idea that we discussed here around helping users being able to build netplugin on Mac. On Mac OSX netplugin doesn't build natively due to a limitation around namespace support (#124), so we are thinking to run the `make build` target trigger a build inside a linux vm than natively on the host. I think it still needs to be flushed out more wrt vm-in-vm situations that this might result in but I filed this to track it and get the discussions going.

This is different from #119 as that explains the steps needed to reach the stage of doing `make build` itself which shall not change with this enhancement to build process.

**Comment by shaleman** [comment]
Closing this since we build netplugin in VM now.
