### ISSUE TITLE
calico plugin : integration with ipsec + federation

### ISSUE THREAD

**Issue by davidwalter0** [contiv/netplugin#151]
PCI HIPAA and other security compliance measures as well as basic infrastructure sensitive data components would benefit from the ability to have a clean management method for intra cluster ipsec [ so all point to point communications within a cluster are secured [including to storage] and inter cluster communications.

If calico were able to create a simple route able cross cluster network space with ip sec integrated for a tenant, the burden of SSL management between every endpoint would be simplified. This would offer sensitive applications a simpler path to cloud services and is an advantage over other providers 'shared' security model where applications have to manage all endpoint encryption.

When federation for stability, disaster recovery, load balancing or zone latency are required, this would assist in creating a flat network space with security as well as a cleaner path to manage hosting.

Currently an application that has to manage these types of concerns has to implement TLS/SSL point to point security, manage keys for each end point and manage load balancing between clusters. The complexities of load balancing may not change but replicated data points and HA solutions will have more flexibility around a variety of use cases.

**Comment by jainvipin** [comment]
@davidwalter0 - while I agree that PCI/HIPAA compliance is is an absolute need, perhaps you meant to open this issue in [Calico project] (https://github.com/projectcalico/calico).

We'd be happy to discuss ssl management, encryption, federation, etc. among other services fitting into Contiv Neworking if that's what you intended.

**Comment by davidwalter0** [comment]
@jainvipin I started the discussion here, thinking that the design plans were considering calico integration, but that the netplugin direction would consider full network management including solving open problems in the linux container space.

**Comment by jainvipin** [comment]
@davidwalter0 - with changes from @shaleman now meged into the master that supports group-based policies, this is taken care of; it supports tcp flags and 7 tuple based reflexive ACLs; I will close the issue unless you have some objections.

**Comment by davidwalter0** [comment]
Feel free to close if you think this is complete. Perhaps drop the link to the changes that resolve it?

**Comment by shaleman** [comment]
Group based policies were added a while ago. Please see docs.contiv.io for details on how to use policies.
We'll take up other requirements like encryption over next few releases.
Closing this issue for now
