### ISSUE TITLE
Etcd Remote Watch

### ISSUE THREAD

**Issue by danehans** [contiv/netplugin#166]
It is preferred if a local instance of etcd is not required for netplugin to function. Netplugin should be able to communicate with a remote instance of etcd by implementing remote-watch.

**Comment by prateekgogia** [comment]
Also, why does Netplugin has etcd and consul both kv supports, do they both have to be on the same host everytime. Does Contiv supports libkv from docker for host discovery, if not then what mechanism is used for host discovery ?

**Comment by jainvipin** [comment]
@prateekgogia - both do not get used simultaneously; we hope to integrate with whichever exists underneath.
libkv is the way how Contiv integrates with Docker. Btw, libkv isn't used for host discovery; As of now host-discovery is done using /etc/hosts update by docker. 

We use skydns to discover hosts. @DivyaVavili workd on providing the support for this.

**Comment by erikh** [comment]
Just a minor correction here -- we do not use libkv. It's a custom abstraction authored by @mapuri

**Comment by prateekgogia** [comment]
@jainvipin and @erikh Thanks for clarification.

**Comment by shaleman** [comment]
Support for remote etcd was added by #325
