### ISSUE TITLE
DNS on ubuntu desktop 15.04 not working with default DNS config

### ISSUE THREAD

**Issue by SiebeHodzelmans** [contiv/netplugin#172]
When doing a `make demo` the the hosts /etc/resolv.conf is copied to the VM, however on Ubuntu desktop 15.04 this is 

    nameserver 127.0.1.1
    search localdomain

since dnsmasq is running by default on ubuntu desktop. 
This renders the VM unable to do DNS lookups, which causes the swarm binary download to fail (since it can't resolve box.cisco.com).

I myself worked around this by commenting out the `dns=dnsmasq` line in /etc/NetworkManager/NetworkManager.conf.

**Comment by erikh** [comment]
Yeah, this is due to some code we added to get around a proxy issue. I'll try and fix it this week. Sorry for any trouble!

**Comment by erikh** [comment]
@SiebeHodzelmans can you try this again and see if you're still having this problem?

**Comment by SiebeHodzelmans** [comment]
@erikh Sadly it doesn't. I tried with the latest version from github (I redownloaded everything) and when I disable dnsmasq it works great, however when I enable it (and reboot so /etc/resolv.conf gets updated) I get the following error:
```
netplugin-node2: Error while pulling image: Get https://index.docker.io/v1/repositories/skynetservices/skydns/images: dial tcp: lookup index.docker.io: Temporary failure in name resolution
```

**Comment by erikh** [comment]
Huh. Can you give me the commandline you're using to run dnsmasq? Maybe 
I can recreate it in a couple of days.

-Erik

**Comment by SiebeHodzelmans** [comment]
I don't have a specific command that I run. The only thing that I change is uncommenting the `dns=dnsmasq ` line in /etc/NetworkManager/NetworkManager.conf. The deafult content of this conf file is the following (at least for me):
```
[main]
plugins=ifupdown,keyfile,ofono
dns=dnsmasq

[ifupdown]
managed=false
```
This is in a VMware VM with a NAT and a host-only adapter.
I will try to dig deeper into this issue later today.

**Comment by erikh** [comment]
Hmm. ok, host-only networks typically don't use NAT. Are you sure this 
machine can reach other sites?

-Erik

**Comment by SiebeHodzelmans** [comment]
To be clear, it has two adapters, one host-only and one NAT.
I can reach the internet (I tested github.com, gitlab.com, cisco.com and google.com) from inside this machine fine. I also don't have this issue with other projects that use vagrant (kubernetes for example).

**Comment by erikh** [comment]
OK, good to know. I will look into it (see if I can re-create it with 
vmware) and get back to you.

-Erik

**Comment by SiebeHodzelmans** [comment]
I have dug deeper, and found that it still copies the host's `/etc/resolv.conf` file. It does this in the [vagrant file, line 8](https://github.com/contiv/netplugin/blob/master/Vagrantfile#L8).

**Comment by erikh** [comment]
It's fixed here: https://github.com/contiv/netplugin/pull/198/files -- I noticed it the other night when updating the boxes. Let me know if that resolves (heh!) things.

**Comment by SiebeHodzelmans** [comment]
Apologies for the wait.
this has indeed fixed it.

**Comment by erikh** [comment]
Thank you SO MUCH for helping us triage this.
