### ISSUE TITLE
Add Contiv Support to Kubernetes Ansible Module

### ISSUE THREAD

**Issue by danehans** [contiv/netplugin#175]
Have the Kube Ansible module support Contiv. See this Contrail example:

https://github.com/kubernetes/contrib/commit/70db494e49eb465408580ee433cf5c8197b96cc7

**Comment by jainvipin** [comment]
@jojimt - once you upstream your changes can you please close this issue?

**Comment by shaleman** [comment]
Contiv kubernetes ansible changes have been upstreamed.
Closing this
