### ISSUE TITLE
Make plugin APIs consistent

### ISSUE THREAD

**Issue by shaleman** [contiv/netplugin#204]
Currently netplugin/plugin APIs take an object ID as argument. This creates few problems:
1. objects need to be read twice, once by netplugin and again by the drivers. 
2. When an object is deleted, there is no way for drivers to get the parameters of the object.

Instead, better way might be for netplugin to pass down the entire state to drivers as part of plugin API.
This issue tracks the API change required in netplugin and drivers.

**Comment by abhinandanpb** [comment]
This appears to be addressed. We can revisit if there is any api changes needed.
