### ISSUE TITLE
netmaster cannot be started simultaneously on multiple hosts

### ISSUE THREAD

**Issue by erikh** [contiv/netplugin#210]
@vvb will provide logs regarding the failure.

When working on volplugin, I lazily left an ansible configuration in that would start a netmaster on each host (of 3) instead of just one. In this instance, the first host `mon0` failed to start the netmaster because of a key conflict writing to etcd.

Since our current strategy for failover is to utilize a virtual ip, we'll need to support multiple netmasters coming up, even if they are not servicing any requests.

**Comment by vijayvikrant** [comment]
netmaster logs for all three nodes,
https://gist.github.com/vijayvikrant/6ef934e8d8e826afab8d

**Comment by erikh** [comment]
I'm pretty sure this is the reason netmaster/netplugin was soiling itself with my prep of hte demo this week...

basically, what I'm saying is that multiple netmaster starts may put the system in an unrecoverable state.

**Comment by shaleman** [comment]
We fully support netmasters on multiple hosts now
closing this
