### ISSUE TITLE
Obtaining IP address of Netmaster

### ISSUE THREAD

**Issue by flightpath** [contiv/netplugin#225]
I have two containers(A & B). Container A creates container B. Container A also needs to establish the network, policies and rules for Container B by issuing REST api calls to Netmaster.

What is the best way for Container A to dynamically obtain the IP address of the Netmaster that it has visibility to? There could be multiple A containers that reside in different tenants/clusters so manually updating the /etc/hosts file with the netmaster entry for each Container A would be impractical.

**Comment by jojimt** [comment]
In order achieve what you want, container A will need to be on the infra network. Thereby, the problem boils down to DNS resolution in the infra network.

**Comment by jainvipin** [comment]
@flightpath - is it possible to start the container with `--net=host` and use the dns options to specify the nameserver to be that of the host?

**Comment by flightpath** [comment]
Thanks. Tried the --net=host option and that worked. Vipin I'm confused by your reference "use the dns options to specify the nameserver to be that of the host" because docs.docker states the following (i) Your container will use the same DNS servers as the host by default, but you can override this with --dns., and (ii) Note that --add-host --hostname --dns --dns-search --dns-opt and --mac-address are invalid in host netmode.

**Comment by jainvipin** [comment]
@flightpath 
makes sense; thanks for confirming and trying this out. I wasn't sure if with --net=host dns server address is picked up from /etc/resolv.conf of the host. Looks like it is... 

>  Vipin I'm confused by your reference "use the dns options to specify the nameserver to be that of the host" because docs.docker states the following (i) Your container will use the same DNS servers as the host by default, but you can override this with --dns., and (ii) Note that --add-host --hostname --dns --dns-search --dns-opt and --mac-address are invalid in host netmode.
