### ISSUE TITLE
Error Deploying new Container to Endpoint Group

### ISSUE THREAD

**Issue by acusworth** [contiv/netplugin#231]
Following the instructions exactly for the demo in the Contiv documentation.
I created the Policy, added rules, created the enpoint group, and then ran the docker command to create a new container and add to endpoint group. The following error is the result of the last command to create the container.
<img width="1346" alt="6b11f3f2-15eb-487a-9fb5-11efa8bcd0a4" src="https://cloud.githubusercontent.com/assets/16193131/12333139/7677140a-bac0-11e5-81a1-7fd2e57c07e3.png">

**Comment by acusworth** [comment]
Demo vagrant box slept and caused a disconnect. Used reset script solved issue.

**Comment by jainvipin** [comment]
@acusworth - if you don't mind I will reopen this in the hope that if there is something netplugin should do to query the client and reconnect, etc. we should work on it.
@vijayvikrant - can you please help with this?

**Comment by vijayvikrant** [comment]
@jainvipin yes, will work on this.

**Comment by shaleman** [comment]
This is fixed in recent builds
Vagrant box sleeping does not cause etc errors
