### ISSUE TITLE
Netctl Net commands returning null pointer

### ISSUE THREAD

**Issue by acusworth** [contiv/netplugin#232]
Found after downloading latest available code, running vagrant demo. 
Following the demo commands to create a network with netctl failed with a null pointer. Trying to list networks with netctl also return the same null pointer error. Attached is a screen capture of the error.
![netctl_net](https://cloud.githubusercontent.com/assets/16193131/12339320/7a184940-bae2-11e5-85e9-e37d55caf470.jpg)

**Comment by abhinandanpb** [comment]
Hi acusworth. Thanks for trying this out. Can you confirm if you are executing netctl on the node where netmaster service is running ?

**Comment by acusworth** [comment]
Im in node 1 of the demo vagrant box. It worked in previous versions of the demo.

**Comment by acusworth** [comment]
Turns out issue was due to a failure in creating the demo properly with the "make demo" command.
