### ISSUE TITLE
Sporadic UT failure on contivk8s

### ISSUE THREAD

**Issue by jojimt** [contiv/netplugin#249]
Unit test fails on contivk8s occasionally in sanity.

To reproduce, run the unit-test repeatedly, e.g. from a script.

This is from the error log:
```
INFRA_CONTAINER_ID=8ec72deca647bfa60a4b815aa735c87de859b47e872828586749b9d852af1f49  NETNS
=98765
FATA[0000] EP create failed -- Post http://localhost/ContivCNI.AddPod: dial unix /run/con
tiv/contiv-cni.sock: connect: no such file or directory  NETNS=98765
```

**Comment by jainvipin** [comment]
@jojimt - can you please also add some details about the failure? This if someone were to pick up the issue we have some hints on how to reproduce it? Say just run unit-tests, or system-tests make target?

**Comment by jojimt** [comment]
Yes, PR is on the way :)

**Comment by jainvipin** [comment]
:+1:
