### ISSUE TITLE
net creation as per documentation doesn't work

### ISSUE THREAD

**Issue by jainvipin** [contiv/netplugin#252]
Following errors out, even though it is a recommendation from [https://docs.contiv.io] page:
```
$ netctl net create contiv-net --subnet=20.1.1.0/24 --gateway=20.1.1.254 --pkt-tag=1001
500 Internal Server Error: Container 1b7260bd34561f76bd494aeefbad086dae7fd4e150ea4e411de841172f7ddf31 is not running

ERRO[0000] Status 500 in request response               
```

Where as following works:
```
$ netctl net create --subnet=20.1.1.0/24 --gateway=20.1.1.254 --pkt-tag=1001 contiv-net 
$ netctl net list
Tenant   Network     Encap type  Packet tag  Subnet       Gateway
------   -------     ----------  ----------  -------      ------
default  contiv-net  vxlan       1001        20.1.1.1/24  20.1.1.254
```

**Comment by shaleman** [comment]
@jainvipin this might be netmaster complaining about skydns container not the order of the command?

**Comment by jainvipin** [comment]
@shaleman - yes skydns isn't running and I had suspected that, however second attempt running okay made me wonder if it is otherwise. 

The error message could be clearer, perhaps.

**Comment by shaleman** [comment]
We display better error message now.
Lets reopen if something is not clear
