### ISSUE TITLE
show contiv parameters in `docker network inspect`

### ISSUE THREAD

**Issue by jainvipin** [contiv/netplugin#253]
When a docker network is created by netplugin/netmaster, it would be good to allow folks to use `docker network inspect` to know the options that were used by netctl to create the network. this can help correlate the output with contiv networking parameters. For example pkt-tag can show up as an option in the following output:

```
$ docker network inspect contiv-net 
[
    {
        "Name": "contiv-net",
        "Id": "ed6ba9dfa6f7e271c2dc8d0a87c6cb0b773e43de9a6e2a48726433e742b7b4fe",
        "Scope": "global",
        "Driver": "netplugin",
        "IPAM": {
            "Driver": "default",
            "Config": [
                {}
            ]
        },
        "Containers": {},
        "Options": {
            "pkt-tag": "1001"
        }
    }
]
```

**Comment by vijayvikrant** [comment]
@jainvipin PR https://github.com/contiv/netplugin/pull/257 is raised for this.

**Comment by vvb** [comment]
#257 resolved this. This can be closed now.
