### ISSUE TITLE
allow runtime flag to avoid running skydns

### ISSUE THREAD

**Issue by jainvipin** [contiv/netplugin#255]
Allow using external (or pre-built dns) from libnetwork/k8s

`netmaster -dns-service=false . . .`

Desired behavior could be:
- if `dns-service` is specified, either `true` or `false` it is used as a hint to mandate or bypass dns service by netplugin.
- Otherwise, apply the behavior as exists now i.e. when dockplugin is use dns-service, otherwise (e.g. for k8s) skip

**Comment by shaleman** [comment]
Closing.
fixed by #268
