### ISSUE TITLE
run netctl net create get failure at node without skydns 

### ISSUE THREAD

**Issue by leslie-wang** [contiv/netplugin#260]
2 nodes (node1, node2) run netplugin and netmaster. skydns is started at node1. If I run "netctl net create contiv-net --encap=vlan --subnet=20.1.1.0/24 --gateway=20.1.1.254 --pkt-tag=1010" at node2, it will have error like below
  sudo netctl net create contiv-net --encap=vlan --subnet=20.1.1.0/24 --gateway=20.1.1.254 --pkt-tag=1010
INFO[Jan 30 11:02:42.096039974] Received NetworkCreate: &{Key:default:contiv-net Encap:vlan Gateway:20.1.1.254 NetworkName:contiv-net PktTag:1010 Subnet:20.1.1.0/24 TenantName:default LinkSets:{EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType: ObjKey: mutex:{state:0 sema:0}}}} 
INFO[Jan 30 11:02:42.177130636] Received "create" for key: /contiv.io/state/nets/contiv-net.default 
INFO[Jan 30 11:02:42.177539840] Received "create" for network: "contiv-net.default" 
INFO[1737] GET /v1.15/networks/contiv-net               
INFO[Jan 30 11:02:42.201751540] create net {CommonState:{StateDriver:0xc8200620a8 ID:contiv-net.default} Tenant:default NetworkName:contiv-net PktTagType:vlan PktTag:1010 ExtPktTag:0 SubnetIP:20.1.1.0 SubnetLen:24 Gateway:20.1.1.254 EpCount:0 IPAllocMap:{length:257 set:[1 0 0 4611686018427387904 1]} DNSServer:} 
 
INFO[Jan 30 11:02:42.201852742] ofnet Adding Vlan 1010. Vni 0                
INFO[Jan 30 11:02:42.201892456] Network operation create succeeded           
ERRO[1737] Handler for GET /v1.15/networks/contiv-net returned error: network contiv-net not found 
ERRO[1737] HTTP Error                                    err=network contiv-net not found statusCode=404
INFO[Jan 30 11:02:42.232324935] Creating docker network: {Name:contiv-net CheckDuplicate:true Driver:netplugin IPAM:{Driver:netplugin Config:[{Subnet:20.1.1.0/24 IPRange: Gateway:20.1.1.254 AuxAddress:map[]}]}} 
INFO[1737] POST /v1.15/networks/create                  
INFO[Jan 30 11:02:42.257362711] Handling "requestPool" event                 
INFO[Jan 30 11:02:42.257555898] Received RequestPoolRequest: {AddressSpace: Pool:20.1.1.0/24 SubPool: Options:map[] V6:false} 
INFO[Jan 30 11:02:42.257624230] Sending RequestPoolResponse: {Response:{Error:} PoolID:20.1.1.0/24 Pool:20.1.1.0/24 Data:map[]} 
INFO[Jan 30 11:02:42.258364204] Handling "requestAddress" event              
INFO[Jan 30 11:02:42.258499404] Received RequestAddressRequest: {PoolID:20.1.1.0/24 Address:20.1.1.254 Options:map[]} 
INFO[Jan 30 11:02:42.258567093] Sending RequestAddressResponse: {Response:{Error:} Address:20.1.1.254/24 Data:map[]} 
INFO[Jan 30 11:02:42.259096618] Handling "create network" event              
INFO[Jan 30 11:02:42.259333225] CreateNetworkRequest: {NetworkID:8e80699433701acb40e1bd2a2602bb4b7694f40064c9021daa32ba95fa889efe Options:map[com.docker.network.generic:map[]] IPv4Data:[{AddressSpace: Pool:20.1.1.0/24 Gateway:20.1.1.254/24 AuxAddresses:map[]}] IPv6Data:[]} 
INFO[1737] POST /v1.15/networks/contiv-net/connect      
ERRO[1737] Handler for POST /v1.15/networks/contiv-net/connect returned error: invalid container <nil> : nosuchcontainer: no such id: defaultdns 
ERRO[1737] HTTP Error                                    err=invalid container <nil> : nosuchcontainer: no such id: defaultdns statusCode=404
ERRO[Jan 30 11:02:42.322198019] Could not attach container(defaultdns) to network contiv-net. Error: Not found 
ERRO[Jan 30 11:02:42.322232577] Error attaching service container to network: contiv-net.default. Err: Not found 
ERRO[Jan 30 11:02:42.322264350] Error creating network {&{Key:default:contiv-net Encap:vlan Gateway:20.1.1.254 NetworkName:contiv-net PktTag:1010 Subnet:20.1.1.0/24 TenantName:default LinkSets:{EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType:tenant ObjKey:default mutex:{state:0 sema:0}}}}}. Err: Not found 
ERRO[Jan 30 11:02:42.322293432] NetworkCreate retruned error for: &{Key:default:contiv-net Encap:vlan Gateway:20.1.1.254 NetworkName:contiv-net PktTag:1010 Subnet:20.1.1.0/24 TenantName:default LinkSets:{EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType:tenant ObjKey:default mutex:{state:0 sema:0}}}}. Err: Not found 
ERRO[Jan 30 11:02:42.322331742] CreateNetwork error for: {Key:default:contiv-net Encap:vlan Gateway:20.1.1.254 NetworkName:contiv-net PktTag:1010 Subnet:20.1.1.0/24 TenantName:default LinkSets:{EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType:tenant ObjKey:default mutex:{state:0 sema:0}}}}. Err: Not found 
ERRO[Jan 30 11:02:42.322355969] Handler for POST /api/networks/default:contiv-net/ returned error: Not found 
Not found
ERRO[0000] Status 500 in request response

however, this network is created in docker network.
$ docker network ls
NETWORK ID          NAME                DRIVER
8acd12650021        contiv-net          netplugin           
ca8f0479942a        bridge              bridge              
fe9efb858ffe        none                null                
80b169bca84d        host                host                

When I run "netctl net list" at node 2, this network is also listed
$ netctl net list
Tenant   Network     Encap type  Packet tag  Subnet       Gateway
------   -------     ----------  ----------  -------      ------
default  contiv-net  vlan        1010        20.1.1.0/24  20.1.1.254

however, if I run "netctl net list" at node 1, this network is not listed.

At the same time, if I run "netctl net create" command at node 1, everything is fine.

**Comment by jainvipin** [comment]
@leslie-wang - same as #252 
@DivyaVavili is working on a fix, where we allow netmaster to allow to run without skydns (i.e. make it optional)

**Comment by leslie-wang** [comment]
@jainvipin. Good to know it. I'll close it then.
