### ISSUE TITLE
Network delete going through even if EPs exist on it 

### ISSUE THREAD

**Issue by abhinandanpb** [contiv/netplugin#270]
I saw this issue while trying K8s demo.

1) Create a network 
2) Using Replication controller , spin off 50 replicas
3) Delete the network
4) Ip address is still allocated to the pods. 
5) `netctl net ls` shows the network is deleted.

**Comment by jainvipin** [comment]
@abhinandanpb - how does it compare with libnetwork's user created behavior? just curious...

**Comment by abhinandanpb** [comment]
@jainvipin- i will try it and post it here.

**Comment by abhinandanpb** [comment]
It complains of an active endpoint being present when we do a network delete. 

# docker network create --gateway=90.1.1.254 --subnet=90.1.1.1/24 docknet
6ff2c88946368df912185b344b4ac2a1e4a5b761093ab9046c558ee9994ac9b4

#docker run -itd --net=docknet ubuntu bash

#docker exec -it e139ae0b3888 bash

root@e139ae0b3888:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:5a:01:01:01
          inet addr:90.1.1.1  Bcast:0.0.0.0  Mask:255.255.255.0
          inet6 addr: fe80::42:5aff:fe01:101/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:16 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1296 (1.2 KB)  TX bytes:648 (648.0 B)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

root@e139ae0b3888:/#
# docker network rm docknet
Error response from daemon: network docknet has active endpoints
#

**Comment by jainvipin** [comment]
makes sense... we should error out. Not just for network but also for policies, etc.

**Comment by vvb** [comment]
resolved by #277
