### ISSUE TITLE
File handles not released for certain events in netplugin

### ISSUE THREAD

**Issue by DivyaVavili** [contiv/netplugin#287]
**Issue:**
HTTP accept error seen in netplugin and no events are being handled:
2016/02/16 20:38:30 http: Accept error: accept unix /run/docker/plugins/netplugin.sock: accept4: too many open files; retrying in 1s

vagrant@netplugin-node1:/vagrant$ sudo lsof | grep netplugin.sock | wc -l
8040

**Version info:**
Prominently on docker 1.10, but seen with certain events in docker 1.9 as well.

**More info:**
In docker 1.10, plugin activate and capabilities are called periodically by docker. The event handling for these events are not releasing file handles and after a while, accept errors are seen. 

**Reproducibility:**
Easiest way to reproduce is to call "docker volume ls" multiple times in docker 1.10. 
NOTE: 
With docker 1.9, the issue is not seen with "docker volume ls", but the file handles are not released even here in certain events.
docker 1.10 seems to make additional calls to get the same information

**Comment by shaleman** [comment]
This was fixed a while ago. closing it
