### ISSUE TITLE
incorrect CLI output 

### ISSUE THREAD

**Issue by prateekgogia** [contiv/netplugin#318]
When using "-a" flag with policy rule-ls command, it displays the rules which are present under a different policy as well. In the following sample, "ratings-recommendations" has only 1 rule, but when "-a" flag is used it shows rule from other policies as well. Either policy name should not be required with "-a" flag or it should only display rules under one policy name, but, not sure how different will it be compared to not specifying "-a" in that case.

ubuntu@ip-10-10-131-157:~$ netctl policy rule-ls ratings-recommendations
Incoming Rules:
Rule  Priority  From EndpointGroup  From Network  From IpAddress  Protocol  Port  Action
---

1     1                ratings:latest      shop4me                                 0     deny
Outgoing Rules:
Rule  Priority  To EndpointGroup  To Network  To IpAddress  Protocol  Port  Action
---

ubuntu@ip-10-10-131-157:~$ netctl policy rule-ls ratings-recommendations -a
Incoming Rules:
Rule  Priority  From EndpointGroup  From Network  From IpAddress  Protocol  Port  Action
---

1     1         catalog:latest      shop4me                                 0     deny
1     1         ratings:latest      shop4me                                 0     deny
Outgoing Rules:
Rule  Priority  To EndpointGroup  To Network  To IpAddress  Protocol  Port  Action
---

**Comment by shaleman** [comment]
Good point! Thanks @prateekgogia.
"-a" option should not require a policy name. Its supposed to display all rules across all policies..

**Comment by gaurav-dalvi** [comment]
Issue no longer exists : 

```
netctl  policy rule-ls app2db -a
Incorrect Usage.

NAME:
   netctl policy rule-ls - List rules for a given tenant,policy

USAGE:
   netctl policy rule-ls [command options] [policy]

OPTIONS:
   --tenant, -t "default"	Name of the tenant
   --json, -j			Output list in JSON format
   --quiet, -q			Only display name field

```

**Comment by gaurav-dalvi** [comment]
Ideally we should not display all the rules under all the policies when used with -a option. 
If we get specific requirement, we can provide that functionality. Not difficult to implement.

Hence closing this issue.
