### ISSUE TITLE
Metmaster Requires New and Old Etcd Ports

### ISSUE THREAD

**Issue by danehans** [contiv/netplugin#323]
Netmaster does not start without adding a 2nd etcd client/advertise url listening on :4001. Netmaster should not require etcd both :2379 and :4001 ports. The etcd client on Netmaster and any other Contiv components should be updated so both ports are not required.

**Comment by danehans** [comment]
This issue should be addressed by https://github.com/contiv/netplugin/pull/325

**Comment by shaleman** [comment]
fixed by #325 

cc @vvb @mapuri so that we can simplify ansible
