### ISSUE TITLE
netctl net create command succeeds but network is not listed 

### ISSUE THREAD

**Issue by rkharya** [contiv/netplugin#327]
[cluster-admin@contiv-aci-scale-2 ~]$ netctl net create contiv-net --subnet=172.16.0.0/20 --gateway=172.16.15.254 --encap=vlan --tenant "contiv-scale"

[cluster-admin@contiv-aci-scale-2 ~]$ netctl net list
Tenant  Network  Encap type  Packet tag  Subnet   Gateway
------  -------  ----------  ----------  -------  ------
[cluster-admin@contiv-aci-scale-2 ~]$ netctl net list
Tenant  Network  Encap type  Packet tag  Subnet   Gateway
------  -------  ----------  ----------  -------  ------
[cluster-admin@contiv-aci-scale-2 ~]$ netctl net list
Tenant  Network  Encap type  Packet tag  Subnet   Gateway
------  -------  ----------  ----------  -------  ------

Then tried to use same command with --tenant=<name> output says cant change parameters after its created -

[cluster-admin@contiv-aci-scale-2 ~]$ netctl net create contiv-net --subnet=172.16.0.0/20 --gateway=172.16.15.254 --encap=vlan --tenant=contiv-scale
ERRO[0000] Cant change network parameters after its created [github.com/contiv/netplugin/netmaster/objApi.(*APIController).NetworkUpdate apiController.go 589]

netplugin service status message doesn't have any clue what's going on -

[cluster-admin@contiv-aci-scale-2 ~]$ sudo systemctl status -l -n 100 netplugin.service
● netplugin.service - Netplugin
   Loaded: loaded (/etc/systemd/system/netplugin.service; static; vendor preset: disabled)
   Active: active (running) since Thu 2016-04-14 10:05:39 PDT; 14h ago
 Main PID: 19212 (netplugin)
   CGroup: /system.slice/netplugin.service
           └─19212 /usr/bin/netplugin -plugin-mode docker -vlan-if enp5s0f0 -vtep-ip 10.193.231.44 -ctrl-ip 10.193.231.44 -fwd-mode bridge

Apr 15 00:27:14 contiv-aci-scale-2.cisco.com netplugin[19212]: time="Apr 15 00:27:14.088984453" level=info msg="Handling \"getIpamCapability\" event"
Apr 15 00:28:02 contiv-aci-scale-2.cisco.com netplugin[19212]: time="Apr 15 00:28:02.032184808" level=info msg="Handling \"activate\" event"
Apr 15 00:28:02 contiv-aci-scale-2.cisco.com netplugin[19212]: time="Apr 15 00:28:02.033049882" level=info msg="Handling \"getCapability\" event"
Apr 15 00:28:02 contiv-aci-scale-2.cisco.com netplugin[19212]: time="Apr 15 00:28:02.034065149" level=info msg="Handling \"getIpamCapability\" event"
Apr 15 00:28:51 contiv-aci-scale-2.cisco.com netplugin[19212]: time="Apr 15 00:28:51.254600265" level=info msg="Handling \"activate\" event"
Apr 15 00:28:51 contiv-aci-scale-2.cisco.com netplugin[19212]: time="Apr 15 00:28:51.255453949" level=info msg="Handling \"getCapability\" event"
Apr 15 00:28:51 contiv-aci-scale-2.cisco.com netplugin[19212]: time="Apr 15 00:28:51.256333505" level=info msg="Handling \"getIpamCapability\" event"
Apr 15 00:29:51 contiv-aci-scale-2.cisco.com netplugin[19212]: time="Apr 15 00:29:51.069330322" level=info msg="Handling \"activate\" event"
Apr 15 00:29:51 contiv-aci-scale-2.cisco.com netplugin[19212]: time="Apr 15 00:29:51.070132861" level=info msg="Handling \"getCapability\" event"

**Comment by rkharya** [comment]
on deletion it says, network not found -

[cluster-admin@contiv-aci-scale-2 ~]$ netctl net delete contiv-net
INFO[0000] Deleting network default:contiv-net
ERRO[0000] network not found

**Comment by vvb** [comment]
@rkharya you probably need to specify the `--tenant` option in those commands..

**Comment by rkharya** [comment]
it was specified -

[cluster-admin@contiv-aci-scale-2 ~]$ netctl net create contiv-net --subnet=172.16.0.0/20 --gateway=172.16.15.254 --encap=vlan --tenant "contiv-scale"

**Comment by vvb** [comment]
@rkharya you also need to specify in the `net list` `net delete` commands

**Comment by rkharya** [comment]
@vvb thare are 4 issues here -
1. command succeeds with --tenant "contiv-scale"
2. After this 'net list' doesn't show network created
3. Then when i try to modify --tenant=contiv-scale it says cannot modify already existing network!!
4. Then i try to delete, it says no network with name contiv-net found!!!

All the outputs are pasted above. Hope this would help....

**Comment by vvb** [comment]
@rkharya Only the network create command is correctly specified. Try the below,

```
 netctl net create contiv-net --subnet=172.16.0.0/20 --gateway=172.16.15.254 --encap=vlan --tenant=contiv-scale
netctl net list --tenant=contiv-scale
netctl net delete contiv-net --tenant=contiv-scale
```

**Comment by rkharya** [comment]
I got where the problem is. We can use either --tenant=<name> OR --tenant "<nam>" both works. Anyways closing the issue.
