### ISSUE TITLE
Deletion of tenant is allowed even if it has network, groups associated with it.

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#337]
In ACI mode of netplugin, 
Once you have created Tenant , network, group; If you are try to delete tenant first then it allows you to delete it even if corresponding network , groups has to be deleted first. Because of this we end up having network and groups which can not be deleted because corresponding tenant is not present.

It should give some warning so that user can delete group and network first and then delete tenant.

Its happening on these versions of netplugin : v0.1-04-11-2016.17-31-22.UTC and v0.1-03-16-2016.13-43-59.UTC.

**Comment by kahou82** [comment]
This is fixed already

`[vagrant@netplugin-node1 ~]$ netctl tenant create t1
Creating tenant: t1
[vagrant@netplugin-node1 ~]$ netctl network create --tenant t1 -s 100.0.0.0/24 -g 100.0.0.1 test-net
Creating network t1:test-net
[vagrant@netplugin-node1 ~]$ netctl group create -t t1 test-net egpA
Creating EndpointGroup t1:egpA
[vagrant@netplugin-node1 ~]$ netctl tenant rm t1
Deleting tenant t1
ERRO[0000] cannot delete t1 has 1 endpoint groups [github.com/contiv/netplugin/netmaster/objApi.(*APIController).TenantDelete apiController.go 1831]
# remove epgA
[vagrant@netplugin-node1 ~]$ netctl group rm egpA -t t1
[vagrant@netplugin-node1 ~]$ netctl tenant rm t1
Deleting tenant t1
ERRO[0000] cannot delete t1 has 1 networks [github.com/contiv/netplugin/netmaster/objApi.(*APIController).TenantDelete apiController.go 1847]
# remove test-net
[vagrant@netplugin-node1 ~]$ netctl network rm test-net -t t1
Deleting network t1:test-net
[vagrant@netplugin-node1 ~]$ netctl tenant rm t1
Deleting tenant t1
[vagrant@netplugin-node1 ~]$`
