### ISSUE TITLE
Clarification: Does netplugin support sr-iov interfaces in containers

### ISSUE THREAD

**Issue by sainath14** [contiv/netplugin#343]
I see in design and readme docs talking about sriov. Does this plugin support exposing sr-iov interfaces in containers?

**Comment by shaleman** [comment]
@sainath14 
SR-IOV support is coming soon. 
Watch for pull request submission on netplugin.

**Comment by shaleman** [comment]
I hope I answered the question.
Closing this for now. Please reopen if you need any info.
