### ISSUE TITLE
Policy Creation results in Contract being created for each Group

### ISSUE THREAD

**Issue by jhayse** [contiv/netplugin#347]
When utilizing the attached workflow in ACI mode, contracts in ACI are created for each EPG.  The desired result is a Contract being created between EPG1 and EPG2 in a provider consumer relationship.  Note: The contracts created by Contiv will not enable the Admin to modify the Consumer.  Both Contracts are being created solely as a provider Contracts.

Summary:
1. Create Policy with Rule allowing WEB and SSH.
2. Create Groups.
3. Create App-profile with 1 group and update with 2nd group.
4. App-Profile is created within ACI with 2 EPGs and 2 Contracts. Should be 1 contract between Group 1 and Group 2. 

Attached the current steps being used to create this error.  Screenshot of the resulting error and one of the intended design.

[ACIContractWorkflow.txt](https://github.com/contiv/netplugin/files/248695/ACIContractWorkflow.txt)

Error
![contractworkflowerror1](https://cloud.githubusercontent.com/assets/18668506/15014273/1177427c-11d3-11e6-813e-3b9c128ff1e9.png)

![contractworkflowerror2](https://cloud.githubusercontent.com/assets/18668506/15014338/6d4d9614-11d3-11e6-8ff0-a9d5daf07613.png)

Intended Result

![contractworkflowintended2](https://cloud.githubusercontent.com/assets/18668506/15014267/0317fc12-11d3-11e6-91dc-4ad6f9c1f506.png)
 
![contractworkflowintended](https://cloud.githubusercontent.com/assets/18668506/15014287/24e3bdfe-11d3-11e6-89d0-dcd00e2f70d6.png)

**Comment by jojimt** [comment]
We currently have a restriction that the EPGs added to a profile must belong to the same network. While this is a bit different from the ACI model, it covers common use cases with a container cluster. To create app-profiles in this manner, you would use the cli as below:
netctl app-profile create -t pepsi -g sodaapp,sugardb pepsi-net1 store-profile
netctl app-profile update -t pepsi -g sodaapp,sugardb,webtier pepsi-net1 store-profile

We will remove this same n/w restriction in the future.

**Comment by efrahim** [comment]
Do we have the roadmap for ACI- What is currently supported or not.

**Comment by jojimt** [comment]
We have opflex integration in the works which will give you more fine grained control over network attributes. And, we will remove the same n/w restriction for the above. BTW, just for my understanding, (1) Have you tried the app-profile with multiple epg's and a single n/w? (2) Do you have an actual use case that requires use of two different subnets?

**Comment by jhayse** [comment]
Thank you! I did attempt to create a contract with groups residing in the same network and it still created a contract individually for each EPG. 

Utilizing the following workflow:
1. netctl network create -t T1 --subnet 1.1.1.0/24 --encap "vlan" -g 1.1.1.1 CONTIV-NET1
2. netctl policy create -t T1 POL1
3. netctl policy rule-add -t T1 -d "in" -l tcp -P 80 -j "allow" POL1 WEB
4. netctl policy rule-add -t T1 -d "in" -l tcp -P 22 -j "allow" POL1 SSH
5. netctl group create -t T1 -p POL1 CONTIV-NET1 EPG1
6. netctl group create -t T1 -p POL1 CONTIV-NET1 EPG2
7. netctl group create -t T1 -p POL1 CONTIV-NET1 EPG3
8 netctl app-profile create -t T1 -g EPG1,EPG2,EPG3 CONTIV-NET1 AP1

Results in the same issue.  Unable to tie contracts together during creation or after the fact.

![contract2test](https://cloud.githubusercontent.com/assets/18668506/15019010/1513ad0a-11ea-11e6-9a74-e1e5349ca1f7.png)

**Comment by jojimt** [comment]
That's because you did not specify a consumer in the policy. Here is an example of how to specify a consumer:
netctl policy rule-add -t pepsi -d in --protocol tcp --port 6379 --from-group sodaapp -n pepsi-net1 --action allow app2db 1

You can look at https://github.com/contiv/demo/blob/master/k8s/samples/sample_appcli.sh

**Comment by jhayse** [comment]
Thank you for your time and patience!  Utilizing your flow above I was able to create a contract coupling two EPGs together.

**Comment by jhayse** [comment]
Thank you! Forgive my ignorance, I was trying the combinations attempting to find a way for it to work.  It now builds the contract as expected!

**Comment by jojimt** [comment]
No worries. Glad to hear it works as expected.
