### ISSUE TITLE
network is not getting removed using netctl CLI when used in ACI fabric mode.

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#348]
When you create a network in ACI mode, You see in netctl net ls and docker network ls commands. But when you delete this network, It still shows in docker network ls command:

[admin@netmaster ~]$ netctl global set --fabric-mode aci --vlan-range 1100-1200
[admin@netmaster ~]$ netctl tenant create t1
INFO[0000] Creating tenant: t1                          
[admin@netmaster ~]$ netctl network create --tenant t1 --subnet=20.1.1.0/24 --gateway=20.1.1.254 -e "vlan" n1
[admin@netmaster ~]$ 
[admin@netmaster ~]$ 
[admin@netmaster ~]$ 
[admin@netmaster ~]$ 
[admin@netmaster ~]$ netctl network ls -a
Tenant  Network  Encap type  Packet tag  Subnet       Gateway
------  -------  ----------  ----------  -------      ------
t1      n1       vlan        0           20.1.1.0/24  20.1.1.254
[admin@netmaster ~]$ 
[admin@netmaster ~]$ 
[admin@netmaster ~]$ docker network ls 
NETWORK ID          NAME                           DRIVER
e5162330fd96        netmaster/bridge               bridge              
8ababbe306cc        netmaster/none                 null                
88d03eb80552        n1/t1                          netplugin           
e81795b78a75        localhost.localdomain/bridge   bridge              
ebf06a60654e        localhost.localdomain/none     null                
9b79e046f2ad        localhost.localdomain/host     host                
c2296ef58372        netmaster/host                 host                
[admin@netmaster ~]$ 
[admin@netmaster ~]$ 
[admin@netmaster ~]$ netctl network rm --tenant t1 n1
INFO[0000] Deleting network t1:n1                       
[admin@netmaster ~]$ 
[admin@netmaster ~]$ 
[admin@netmaster ~]$ netctl network ls -a
Tenant  Network  Encap type  Packet tag  Subnet   Gateway
------  -------  ----------  ----------  -------  ------
[admin@netmaster ~]$ 
[admin@netmaster ~]$ 
[admin@netmaster ~]$ docker network ls 
NETWORK ID          NAME                           DRIVER
9b79e046f2ad        localhost.localdomain/host     host                
88d03eb80552        n1/t1                          netplugin           
e81795b78a75        localhost.localdomain/bridge   bridge              
ebf06a60654e        localhost.localdomain/none     null                
8ababbe306cc        netmaster/none                 null                
c2296ef58372        netmaster/host                 host                
e5162330fd96        netmaster/bridge               bridge              
[admin@netmaster ~]$

**Comment by gaurav-dalvi** [comment]
This happened even if you create network under default tenant.

**Comment by shaleman** [comment]
@gaurav-dalvi can you check for errors in netmaster log file?

**Comment by gaurav-dalvi** [comment]
@shaleman : 

I was looking for in case missing call to docker network remove , But looks like in both cases logs are similar.

Non ACI - Mode : Deletion of network : 

May 04 14:22:53 netmaster netmaster[7300]: time="May  4 14:22:53.470590118" level=info msg="Received NetworkDelete: &{Key:t1:n1 Encap:vlan Gateway:20.1.1.254 NetworkName:n1 PktTag:0 Subnet:20.1.1.0/24 TenantName:t1 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType:tenant ObjKey:t1}}}"
May 04 14:22:53 netmaster netmaster[7300]: time="May  4 14:22:53.497329668" level=info msg="Containers in network: n1/t1 are {map[18364a043e63ac1a9f2ccb467484870cd229235f2d187848169aafd10ed3a41d:{Name:t1dns EndpointID:e8efd170c1a67603f6035ca433d39a5716cb03b2c0c5825ebbdfb0b6cc33b75f MacAddress:02:42:0a:a8:8d:b0 IPv4Address:20.1.1.1/24 IPv6Address:}]}"
May 04 14:22:53 netmaster netmaster[7300]: time="May  4 14:22:53.499220500" level=info msg="dnsServerIP: 20.1.1.1, nwCfg.dnsip: 20.1.1.1"
May 04 14:22:53 netmaster netmaster[7300]: time="May  4 14:22:53.499249847" level=info msg="Disconnecting dns container from network as all other endpoints are removed: n1"
May 04 14:22:53 netmaster netmaster[7300]: time="May  4 14:22:53.588408085" level=info msg="Received DeleteEndpointRequest: {TenantName:t1 NetworkName:n1 ServiceName: EndpointID:e8efd170c1a67603f6035ca433d39a5716cb03b2c0c5825ebbdfb0b6cc33b75f IPv4Address:}"
May 04 14:22:53 netmaster netmaster[7300]: time="May  4 14:22:53.610240559" level=info msg="Sending DELETE endpoint: &{EndpointID:20.1.1.1 EndpointType:internal EndpointGroup:0 IpAddr:20.1.1.1 IpMask:255.255.255.255 VrfId:1100 MacAddrStr:02:02:14:01:01:01 Vlan:1100 Vni:0 OriginatorIp:10.193.231.123 PortNo:4 Timestamp:2016-05-04 14:22:19.592326605 -0400 EDT} to node 10.193.231.124:9003"
May 04 14:22:53 netmaster netmaster[7300]: time="May  4 14:22:53.611760840" level=info msg="Sending DELETE endpoint: &{EndpointID:20.1.1.1 EndpointType:internal EndpointGroup:0 IpAddr:20.1.1.1 IpMask:255.255.255.255 VrfId:1100 MacAddrStr:02:02:14:01:01:01 Vlan:1100 Vni:0 OriginatorIp:10.193.231.123 PortNo:4 Timestamp:2016-05-04 14:22:19.592326605 -0400 EDT} to node 10.193.231.124:9002"
May 04 14:22:53 netmaster netmaster[7300]: time="May  4 14:22:53.650067506" level=info msg="Deleting docker network: n1/t1"


ACI Mode - Deletion of Network : 

-- Logs begin at Fri 2016-04-29 15:10:05 EDT. --
May 04 14:32:46 netmaster netmaster[31025]: time="May  4 14:32:46.613955947" level=info msg="Received AddressAllocRequest: {NetworkID: AddressPool:20.1.1.0/24 PreferredIPv4Address:}"
May 04 14:32:46 netmaster netmaster[31025]: time="May  4 14:32:46.627074131" level=info msg="Received CreateEndpointRequest: {TenantName:t1 NetworkName:n1 ServiceName: EndpointID:526464966ccb499eb457479dd5094457dd98312da94d436677ded105b8a06431 ConfigEP:{Container:526464966ccb499eb457479dd5094457dd98312da94d436677ded105b8a06431 Host:localhost.localdomain AttachUUID: IPAddress:20.1.1.1 ServiceName:}}"
May 04 14:32:46 netmaster netmaster[31025]: time="May  4 14:32:46.978216588" level=info msg="Received Endpoint CReate from Remote netplugin"
May 04 14:32:46 netmaster netmaster[31025]: time="May  4 14:32:46.978325134" level=info msg="Sending endpoint: &{EndpointID:20.1.1.1 EndpointType:internal EndpointGroup:0 IpAddr:20.1.1.1 IpMask:255.255.255.255 VrfId:1 MacAddrStr:02:02:14:01:01:01 Vlan:1 Vni:0 OriginatorIp:10.193.231.123 PortNo:2 Timestamp:2016-05-04 14:32:46.977545205 -0400 EDT} to node 10.193.231.124:9003"
May 04 14:32:46 netmaster netmaster[31025]: time="May  4 14:32:46.978346672" level=info msg="Connecting to RPC server: 10.193.231.124:9003"
May 04 14:32:46 netmaster netmaster[31025]: time="May  4 14:32:46.978831469" level=info msg="Connected to RPC server: 10.193.231.124:9003"
May 04 14:32:46 netmaster netmaster[31025]: time="May  4 14:32:46.979757270" level=info msg="Sending endpoint: &{EndpointID:20.1.1.1 EndpointType:internal EndpointGroup:0 IpAddr:20.1.1.1 IpMask:255.255.255.255 VrfId:1 MacAddrStr:02:02:14:01:01:01 Vlan:1 Vni:0 OriginatorIp:10.193.231.123 PortNo:2 Timestamp:2016-05-04 14:32:46.977545205 -0400 EDT} to node 10.193.231.124:9002"
May 04 14:32:46 netmaster netmaster[31025]: time="May  4 14:32:46.979798090" level=info msg="Connecting to RPC server: 10.193.231.124:9002"
May 04 14:32:46 netmaster netmaster[31025]: time="May  4 14:32:46.979997155" level=info msg="Connected to RPC server: 10.193.231.124:9002"
May 04 14:32:47 netmaster netmaster[31025]: time="May  4 14:32:47.251807173" level=info msg="Dns server for network n1: 20.1.1.1"

**Comment by gaurav-dalvi** [comment]
@shaleman : 

Sometimes it takes more than 30 seconds to 1 min to delete the network and show up in docker network ls command. This I have observed in both in ACI and non ACI mode. (When I reported this issue, in Non ACI mode it got deleted quickly but in subsequent tests it showed delay there as well. )

Is that much delay is expected, if yes then I will close this issue.

**Comment by gaurav-dalvi** [comment]
@shaleman : Should we close this issue ? As this is not actual problem Its just timing thing that when exactly we see update in docker network ls command.

**Comment by shaleman** [comment]
I'm closing this issue since it takes few minutes for network to disappear from "docker network ls"
