### ISSUE TITLE
network delete fails due to "Network has active endpoints"

### ISSUE THREAD

**Issue by jainvipin** [contiv/netplugin#366]
netctl version:
```
[vagrant@netplugin-node1 netplugin]$ netctl version
Client Version:
Version: pv0.1-05-15-2016.04-10-21.UTC
GitCommit: 09a2a3a
BuildTime: 05-15-2016.04-10-21.UTC

Server Version:
Version: pv0.1-05-15-2016.04-10-21.UTC
GitCommit: 09a2a3a
BuildTime: 05-15-2016.04-10-21.UTC
```

Following sequence of commands suggest that skydns container is playing a role in keeping the epcount up and so can't delete the network:
```
[vagrant@netplugin-node1 netplugin]$ netctl net create -s 10.0.1.0/24 junk
[vagrant@netplugin-node1 netplugin]$ docker run --name=sprite -itd --net=junk alpine /bin/sh
65515c29648424052089fbc2db34345549e377e492bafc1fdbf315cc01db8a58
[vagrant@netplugin-node1 netplugin]$ docker rm -f sprite
sprite
[vagrant@netplugin-node1 netplugin]$ netctl net rm junk
INFO[0000] Deleting network default:junk                
ERRO[0000] Error: Network has active endpoints [github.com/contiv/netplugin/netmaster/master.DeleteNetworkID network.go 398]
 
[vagrant@netplugin-node1 netplugin]$ docker ps
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS              PORTS               NAMES
6a79885afd37        skynetservices/skydns:latest   "/skydns"           3 minutes ago       Up 3 minutes        53/udp, 53/tcp      defaultdns
[vagrant@netplugin-node1 netplugin]$ docker rm -f defaultdns
defaultdns
[vagrant@netplugin-node1 netplugin]$ netctl net rm junk
INFO[0000] Deleting network default:junk                
```

**Comment by jainvipin** [comment]
@vvb, @shaleman: is #277 related?

**Comment by jainvipin** [comment]
To add up to above:

`etcdctl` shows clearly that an endpoint is created per network (e.g. `6236a0975220` below); I am going to try a quick patch and see if this can be fixed by adjusting the count. 

```
/docker/network/v1.0/endpoint/6236a0975220ab64a7f7385e02d801d5c28766424459e1cc1cda34959acb9903
/docker/network/v1.0/endpoint/6c3da94d3cffcecd9125692577672466cd363cd23e3ecb4a4e8ff42ee72edc2d
/docker/network/v1.0/endpoint/a4394e74995a0e944c118155299e06ffffdcd19e3eb171d88e9603fac55f4ee6
/docker/network/v1.0/endpoint/a9238504f80c7e0505c0c3878650fdf6e06b673df2c9c3a135ad7537f2ef590c
/docker/network/v1.0/endpoint/01bffe147af30f2d2fdecbd5cc80313593b2fd6d29c5efbf1039a5af08ae86d9
/docker/network/v1.0/endpoint/46815c25f57285fec357d782a461a8e2ec97664098b6127a1c5fdd8e9ee4b3e8
/docker/network/v1.0/endpoint/cc78c51bb5bf9cbefcc0b53b180f4ae3537e00d1d985ae9f31c5852437c3f236
/docker/network/v1.0/network
/docker/network/v1.0/network/6236a0975220ab64a7f7385e02d801d5c28766424459e1cc1cda34959acb9903
/docker/network/v1.0/endpoint_count
/docker/network/v1.0/endpoint_count/6236a0975220ab64a7f7385e02d801d5c28766424459e1cc1cda34959acb99

```

**Comment by shaleman** [comment]
@jainvipin There is an issue with skydns and netmaster switchover we discovered in sanity runs also.

- Netmaster on node-1 becomes leader and starts skydns container
- Netmaster failover happens at some point to Node-2
- Netmaster on Node-2 can not stop/remove skydns container thats running on Node-1 
- Subsequent "netctl net rm" will fail because skydns container still has an endpoint on this network

**Comment by jainvipin** [comment]
@shaleman - while I was thinking this is related to dns container, but it is not; the above logs I showed were without dns_enable. i.e. following also results into a problem.
1. start netmaster with `/opt/gopath/bin/netmaster -dns-enable=false`
2. create a network using `netctl net create -s 10.0.1.0/24 junk`
3. delete the created network using `netctl net rm junk`
4. You'll see the error `Error: Network has active endpoints`

Before starting the network creation, you can confirm that dns container is not running after step 1.

**Comment by shaleman** [comment]
Hmm, this is what our sanity runs. We don't see any errors in sanity. Whats different here?

**Comment by gaurav-dalvi** [comment]
Is gateway option is triggering something ? 

Positive Case:
[admin@netmaster ~]$ netctl network create --subnet=20.1.1.0/24 --gateway=20.1.1.254 -e "vlan" n1
[admin@netmaster ~]$ netctl network rm n1
INFO[0000] Deleting network default:n1                  

Negative case : (No gateway)
[admin@netmaster ~]$ netctl network create --subnet=20.1.1.0/24  n1
[admin@netmaster ~]$ netctl network rm n1
INFO[0000] Deleting network default:n1                  
ERRO[0000] Error: Network has active endpoints [github.com/contiv/netplugin/netmaster/master.DeleteNetworkID network.go 378]

Negative case : (I tried with vlan anv vxlan as well.)
[admin@netmaster ~]$ netctl network create --subnet=20.1.1.0/24  -e "vxlan" n3
[admin@netmaster ~]$ netctl network rm n3
INFO[0000] Deleting network default:n3                  
ERRO[0000] Error: Network has active endpoints [github.com/contiv/netplugin/netmaster/master.DeleteNetworkID network.go 378]

**Comment by jainvipin** [comment]
@gaurav-dalvi - there is more to it than that...
In a new retry, the issue didn't happen even when gateway was not specified However following pattern is confirmed:
- docker creates an endpoint that matches the network uuid (as in the etcdctl output above)
- this results into 

It would help to watch out for the uuid that matches against network uuid, and count an extra ep that docker created.

It would be good to find out with libnetwork about the reason for issuing ep for the network.

**Comment by jainvipin** [comment]
@gaurav-dalvi: pls ignore above - I was trying what I did above with a local fix in my workspace. So I think the pattern is clear: when default-gw is specified, then this issue happens, not otherwise
