### ISSUE TITLE
netplugin question.

### ISSUE THREAD

**Issue by angry-tony** [contiv/netplugin#370]
I'm a new to netplugin.
how to install netplugin on pre existing centos 7.2 instances, such as a set of bare-metal machines with Centos 7.2 installed?
is there any documentation or instruction ??

**Comment by shaleman** [comment]
@angry-tony 
In addition to what @erikh said, here is a little DIY guide to install netplugin on your own cluster
https://github.com/contiv/demo/tree/master/net

**Comment by shaleman** [comment]
Closing this issue.
Please see https://github.com/contiv/demo/tree/master/net for instructions on how to install netplugin on a cluster
