### ISSUE TITLE
Docs and demo vm are incorrect.

### ISSUE THREAD

**Issue by sfoutrel** [contiv/netplugin#374]
Hello,
your doc is missing some important elements.
A correct GOPATH must be set.
Your VM are referring to a depot that has moved and are failing : http://repos.fedorapeople.org/repos/openstack/openstack-kilo/el7/repodata/repomd.xml
the "make demo" never worked for me... /opt/gopath/src is always binded to my homedir instead of my $GOPATH

Trying to fix and provide a patch.

**Comment by gaurav-dalvi** [comment]
Could you provide more details ? On which VMs you are trying to run this demo ?

netplugin demo , once you do make start fetches two vagrant boxes and inside vagrant box GOPATH is /opt/gopath and your demo runs inside vagrant box.

On your client / laptop : 
You checkout the code let us say at / home/tempUser/ then 

/home/tempUser is mapped to /opt/gopath inside vagrant box.

**Comment by jainvipin** [comment]
@sfoutrel - following works for me without any GOPATH dependency:
```
$ echo $GOPATH

$ cd $HOME
$ mkdir demo
$ cd demo
$ git clone https://github.com/contiv/netplugin
$ cd netplugin
$ make demo
$ make ssh
```
Then inside VM
```
[vagrant@netplugin-node1 netplugin]$ netctl net ls
Tenant  Network  Nw Type  Encap type  Packet tag  Subnet   Gateway
------  -------  -------  ----------  ----------  -------  ------
```

Can you describe some steps like above on what you did that required you to set GOPATH?

**Comment by sfoutrel** [comment]
Hello, will retry all within a script instance to give you all errors. 
Two main points were a repos unavailable and vagrant mount points that were not mounted in the good place.

**Comment by gaurav-dalvi** [comment]
Please try again. Let us know if you face any issues.

**Comment by sfoutrel** [comment]
Ok so cannot make your project work because of virtualbox bugs..
the /etc/resolv.conf of the host is imported into vms and as it's using a 127.0.0.1 it can not resolv anything.
Tried some workarounds that did it on a ubuntu created to test but nothing worked in your centos/ubuntu instances.

**Comment by erikh** [comment]
yeah; this is my fault. I can file a patch, or @jojimt recently fixed it too.

**Comment by erikh** [comment]
Either way, it'll be patched tomorrow.

**Comment by sfoutrel** [comment]
did a vagrant destroy -f
put a nameserver 8.8.8.8 temporarily in my host /etc/resolv.conf
then make demo
and it finished succesfully..

Can now try the demo :)

By the way could not found a complete install guide.

**Comment by erikh** [comment]
I've just filed #384 which resolves this issue.

**Comment by gaurav-dalvi** [comment]
@erikh or @shaleman Can we close this issue now ?

**Comment by erikh** [comment]
Yep! the PR was merged
