### ISSUE TITLE
netctl commands fails with marking the VLAN as created

### ISSUE THREAD

**Issue by pradvara** [contiv/netplugin#375]
Steps to reproduce:

[vagrant@netplugin-node1 netplugin]$ netctl net create contiv-net5 -encap vlan -pkt-tag 35 -s 10.1.1.1/24 -g 20.1.1.254
ERRO[0000] hostIP 20.1.1.254 is exceeding beyond subnet 10.1.1.0/24, hostID 167772414 [github.com/contiv/netplugin/utils/netutils.GetIPNumber netutils.go 178]

[vagrant@netplugin-node1 netplugin]$ netctl net create contiv-net5 -encap vlan -pkt-tag 35 -s 10.1.1.1/24 -g 10.1.1.254
ERRO[0000] requested vlan not available

May 18 18:57:59 vm14 netmaster[25731]: time="May 18 18:57:59.131679516" level=info msg="Received NetworkCreate: &{Key:31:contiv-net Encap:vlan Gateway:30.1.1.254 NetworkName:contiv-net PktTag:31 Subnet:20.1.1.0/24 TenantName:31 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType: ObjKey:}}}"
May 18 18:57:59 vm14 netmaster[25731]: time="May 18 18:57:59.131949773" level=error msg="NetworkCreate retruned error for: &{Key:31:contiv-net Encap:vlan Gateway:30.1.1.254 NetworkName:contiv-net PktTag:31 Subnet:20.1.1.0/24 TenantName:31 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType: ObjKey:}}}. Err: Tenant not found [github.com/contiv/netplugin/netmaster/objApi.(_APIController).NetworkCreate apiController.go 547]"
May 18 18:57:59 vm14 netmaster[25731]: time="May 18 18:57:59.132040546" level=error msg="CreateNetwork error for: {Key:31:contiv-net Encap:vlan Gateway:30.1.1.254 NetworkName:contiv-net PktTag:31 Subnet:20.1.1.0/24 TenantName:31 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType: ObjKey:}}}. Err: Tenant not found [github.com/contiv/netplugin/netmaster/objApi.(_APIController).NetworkCreate apiController.go 547]"
May 18 18:58:43 vm14 netmaster[25731]: time="May 18 18:58:43.379716649" level=info msg="Received NetworkCreate: &{Key:tenant31:contiv-net Encap:vlan Gateway:30.1.1.254 NetworkName:contiv-net PktTag:31 Subnet:20.1.1.0/24 TenantName:tenant31 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType: ObjKey:}}}"
May 18 18:58:44 vm14 netmaster[25731]: time="May 18 18:58:44.203396139" level=error msg="Error creating network {&{Key:tenant31:contiv-net Encap:vlan Gateway:30.1.1.254 NetworkName:contiv-net PktTag:31 Subnet:20.1.1.0/24 TenantName:tenant31 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType:tenant ObjKey:tenant31}}}}. Err: hostIP 30.1.1.254 is exceeding beyond subnet 20.1.1.0/24, hostID 167772414 [github.com/contiv/netplugin/utils/netutils.GetIPNumber netutils.go 177]"
May 18 18:58:44 vm14 netmaster[25731]: time="May 18 18:58:44.203472162" level=error msg="NetworkCreate retruned error for: &{Key:tenant31:contiv-net Encap:vlan Gateway:30.1.1.254 NetworkName:contiv-net PktTag:31 Subnet:20.1.1.0/24 TenantName:tenant31 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType:tenant ObjKey:tenant31}}}. Err: hostIP 30.1.1.254 is exceeding beyond subnet 20.1.1.0/24, hostID 167772414 [github.com/contiv/netplugin/utils/netutils.GetIPNumber netutils.go 177]"
May 18 18:58:44 vm14 netmaster[25731]: time="May 18 18:58:44.203536339" level=error msg="CreateNetwork error for: {Key:tenant31:contiv-net Encap:vlan Gateway:30.1.1.254 NetworkName:contiv-net PktTag:31 Subnet:20.1.1.0/24 TenantName:tenant31 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType:tenant ObjKey:tenant31}}}. Err: hostIP 30.1.1.254 is exceeding beyond subnet 20.1.1.0/24, hostID 167772414 [github.com/contiv/netplugin/utils/netutils.GetIPNumber netutils.go 177]"
May 18 18:59:35 vm14 netmaster[25731]: time="May 18 18:59:35.824903423" level=info msg="Received NetworkCreate: &{Key:tenant31:contiv-net Encap:vlan Gateway:30.1.1.254 NetworkName:contiv-net PktTag:31 Subnet:30.1.1.0/24 TenantName:tenant31 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType: ObjKey:}}}"
May 18 18:59:36 vm14 netmaster[25731]: time="May 18 18:59:36.741082734" level=error msg="Error creating network {&{Key:tenant31:contiv-net Encap:vlan Gateway:30.1.1.254 NetworkName:contiv-net PktTag:31 Subnet:30.1.1.0/24 TenantName:tenant31 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType:tenant ObjKey:tenant31}}}}. Err: requested vlan not available"
May 18 18:59:36 vm14 netmaster[25731]: time="May 18 18:59:36.741149304" level=error msg="NetworkCreate retruned error for: &{Key:tenant31:contiv-net Encap:vlan Gateway:30.1.1.254 NetworkName:contiv-net PktTag:31 Subnet:30.1.1.0/24 TenantName:tenant31 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType:tenant ObjKey:tenant31}}}. Err: requested vlan not available"
May 18 18:59:36 vm14 netmaster[25731]: time="May 18 18:59:36.741203620" level=error msg="CreateNetwork error for: {Key:tenant31:contiv-net Encap:vlan Gateway:30.1.1.254 NetworkName:contiv-net PktTag:31 Subnet:30.1.1.0/24 TenantName:tenant31 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType:tenant ObjKey:tenant31}}}. Err: requested vlan not available"
May 18 22:46:17 vm14 netmaster[25731]: time="May 18 22:46:17.966450871" level=info msg="Received NetworkCreate: &{Key:tenant31:contiv-net Encap:vlan Gateway:30.1.1.254 NetworkName:contiv-net PktTag:31 Subnet:30.1.1.0/24 TenantName:tenant31 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType: ObjKey:}}}"
May 18 22:46:18 vm14 netmaster[25731]: time="May 18 22:46:18.594529424" level=error msg="Error creating network {&{Key:tenant31:contiv-net Encap:vlan Gateway:30.1.1.254 NetworkName:contiv-net PktTag:31 Subnet:30.1.1.0/24 TenantName:tenant31 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType:tenant ObjKey:tenant31}}}}. Err: requested vlan not available"
May 18 22:46:18 vm14 netmaster[25731]: time="May 18 22:46:18.594597947" level=error msg="NetworkCreate retruned error for: &{Key:tenant31:contiv-net Encap:vlan Gateway:30.1.1.254 NetworkName:contiv-net PktTag:31 Subnet:30.1.1.0/24 TenantName:tenant31 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType:tenant ObjKey:tenant31}}}. Err: requested vlan not available"
May 18 22:46:18 vm14 netmaster[25731]: time="May 18 22:46:18.594654521" level=error msg="CreateNetwork error for: {Key:tenant31:contiv-net Encap:vlan Gateway:30.1.1.254 NetworkName:contiv-net PktTag:31 Subnet:30.1.1.0/24 TenantName:tenant31 LinkSets:{AppProfiles:map[] EndpointGroups:map[] Services:map[]} Links:{Tenant:{ObjType:tenant ObjKey:tenant31}}}. Err: requested vlan not available"

**Comment by DivyaVavili** [comment]
No longer see the issue.
