### ISSUE TITLE
TestTwoHostsMultipleTenantsMixVlanVxlan_regress fails

### ISSUE THREAD

**Issue by mapuri** [contiv/netplugin#38]
The failure is due to a loop that get's created as a side-effect of adding the Host data-interface (eth2 in case of vagrant vm based setups) to all vlans. Since vxlan implementation also internally uses a vlan-tag for local forwarding. As a result the incoming vxlan packets also get put back on the Host interface resulting in a loop.

A possible fix is to add host interface only to the vlans created for vlan-based networks.

Below are the test logs of the failure:
++++++++++++++
=== RUN TestTwoHostsMultipleTenantsMixVlanVxlan_regress
2015/04/06 11:25:07 ovs-vsctl on node netplugin-node2:
2bfd5ce9-a922-48b3-9a76-65e929639b9d
    Manager "ptcp:6640"
        is_connected: true
    Bridge contivBridge
        Port "port4"
            tag: 1
            Interface "port4"
                type: internal
        Port "port2"
            tag: 200
            Interface "port2"
                type: internal
        Port "port1"
            Interface "eth2"
        Port "vxifpurple192168210"
            tag: 1
            Interface "vxifpurple192168210"
                type: vxlan
                options: {key="10001", remote_ip="192.168.2.10"}
    ovs_version: "2.0.2"

--- FAIL: TestTwoHostsMultipleTenantsMixVlanVxlan_regress (89.42s)
        docker.go:51: Error 'exit status 1' launching container 'myContainer4', Output:
                PING 11.1.0.1 (11.1.0.1) 56(84) bytes of data.
                From 11.1.0.2 icmp_seq=3 Destination Host Unreachable
                From 11.1.0.2 icmp_seq=4 Destination Host Unreachable
                From 11.1.0.2 icmp_seq=5 Destination Host Unreachable

                --- 11.1.0.1 ping statistics ---
                5 packets transmitted, 0 received, +3 errors, 100% packet loss, time 4013ms
                pipe 3

**Comment by shaleman** [comment]
This test has been deprecated
