### ISSUE TITLE
Node commissioning task is failing at contiv_network : set aci mode

### ISSUE THREAD

**Issue by rkharya** [contiv/netplugin#393]
Docker - 1.11.1.CS2
UCP - 1.1.0
Contive Network - v0.1-05-16-2016.08-29-25.UTC
Node - Docker-aci-2-FCH1945V3GF
Status - Service-Master

Ansible/Cluster manager was clonned today only. Error message -

TASK [contiv_network : set aci mode] *******************************************
    fatal: [Docker-aci-2-FCH1945V3GF]: FAILED! => {"changed": true, "cmd": "contivctl network global set --fabric-mode aci", "delta": "0:00:00.840968", "end": "2016-05-30 15:36:46.333656", "failed": true, "rc": 3, "start": "2016-05-30 15:36:45.492688", "stderr": "time=\"2016-05-30T15:36:46+05:30\" level=error msg=\"307 **Temporarily Moved for Domain Name Expansion**\" ", "stdout": "", "stdout_lines": [], "warnings": []}
    	to retry, use: --limit @/home/cluster-admin/ansible/site.retry

    PLAY RECAP *********************************************************************
    Docker-aci-2-FCH1945V3GF   : ok=84   changed=37   unreachable=0    failed=1

The same code base worked on SanJose ACI setup which is not behind proxy. This error is being seen on a setup in BLR working behind proxy.

Not well versed on the error message so as to debug this further. Attaching logs from node getting commissioned and cluster manager node.

**Comment by rkharya** [comment]
[clusterm-journal.txt](https://github.com/contiv/netplugin/files/289373/clusterm-journal.txt)
[clusterm-status.txt](https://github.com/contiv/netplugin/files/289374/clusterm-status.txt)
[etcd-journal.txt](https://github.com/contiv/netplugin/files/289375/etcd-journal.txt)
[etcd-status.txt](https://github.com/contiv/netplugin/files/289378/etcd-status.txt)
[netmaster-journal.txt](https://github.com/contiv/netplugin/files/289377/netmaster-journal.txt)
[netmaster-status.txt](https://github.com/contiv/netplugin/files/289376/netmaster-status.txt)
[netplugin-journal.txt](https://github.com/contiv/netplugin/files/289379/netplugin-journal.txt)
[netplugin-status.txt](https://github.com/contiv/netplugin/files/289380/netplugin-status.txt)

**Comment by mapuri** [comment]
@rkharya I think you will need to set `no_proxy` env variable as well when you run behind proxy. Something like below:

`-e {"env": {"no_proxy":"127.0.0.1,localhost,netmaster"} }`

**Comment by rkharya** [comment]
@mapuri Thanks, that helped. Pls. close this issue.

**Comment by shaleman** [comment]
Closing the issue since `no_proxy` setting fixed it
