### ISSUE TITLE
Container with Netplugin are getting spawned slowly

### ISSUE THREAD

**Issue by kiranneo** [contiv/netplugin#401]

**Comment by jainvipin** [comment]
@kiranneo - can you provide some details about the setup? Is it Vagrant setup? Version information, etc.
`netctl version`, `docker version`, `etcdctl clusterhealth`? How big is the cluster?

**Comment by kiranneo** [comment]
It is 3-node Ubuntu(15.10) Cluster VM running on ESXi. WE have brought the cluster up using Contiv's net_demo_installer. Spawning of the containers are consistently slower when associated with netplugin.

I have also observed the container get spawned faster in a progrium/consul based swarm cluster than etcd based swarm cluster.

admin04@nxmonit-04-174:~$ netctl version
Client Version:
Version: v0.1-05-19-2016.08-34-56.UTC
GitCommit: 6efd1ef
BuildTime: 05-19-2016.08-34-56.UTC

Server Version:
Version: v0.1-05-19-2016.08-34-56.UTC
GitCommit: 6efd1ef
BuildTime: 05-19-2016.08-34-56.UTC
admin04@nxmonit-04-174:~$ sudo docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64
admin04@nxmonit-04-174:~$ 

admin04@nxmonit-04-174:~$ etcdctl cluster-health
member 2c3c97e8c1c7146c is healthy: got healthy result from http://172.23.145.175:2379
member 90d6744581710a7b is healthy: got healthy result from http://172.23.145.174:2379
member a9a3d39ae3611f1d is healthy: got healthy result from http://172.23.145.176:2379
cluster is healthy
admin04@nxmonit-04-174:~$ 


**admin04@nxmonit-04-174:~$ time sudo docker run -itd --name=contiv-c3 --net=contiv-net alpine /bin/sh
36cb8a70fe9da2156d80574b5001f30b9410a9d5f0885c4d59af98b7d9b6e56c

real	1m56.116s
user	0m0.016s
sys	0m0.004s
admin04@nxmonit-04-174:~$ 
admin04@nxmonit-04-174:~$** 


admin04@nxmonit-04-174:~$ time sudo docker run -itd --name=contiv-c4 alpine /bin/sh
c0dcac3767d17047c043a8cd8892b563e01c4aaf23a7bb410418b38205b74248

**real	1m27.477s**
user	0m0.020s
sys	0m0.004s
admin04@nxmonit-04-174:~$ 

admin04@nxmonit-04-174:~$ time sudo docker -H :2375 run -itd --name=contiv-c5 alpine /bin/sh
6f35d868e706303de48b7b94e5f7e21763eb643cf0c43a6b58bceb284137dd3e

**real	0m41.133s**
user	0m0.012s
sys	0m0.008s
admin04@nxmonit-04-174:~$ 

admin04@nxmonit-04-174:~$ time sudo docker -H :2375 run -itd --name=contiv-c8 --net=contiv-net alpine /bin/sh
d9516b62c516d97bc2177681b3dc82429c0f27ecd48b22190e03741581f6b930

**real	1m18.285s
user	0m0.008s
sys	0m0.012s
admin04@nxmonit-04-174:~$**

**Comment by gaurav-dalvi** [comment]
Looks like bit old version. Can you please test this again with this version : v0.1-06-17-2016.08-42-14.UTC

You can find latest versions here : https://github.com/contiv/netplugin/releases
To run with specific version please read this : https://github.com/contiv/demo/tree/master/net#step-3-provide-executable-privileges-and-run-installer-script

**Comment by abhinandanpb** [comment]
Closing the issue
