### ISSUE TITLE
Issues with make demo command on Windows 10 host machine

### ISSUE THREAD

**Issue by kushal25** [contiv/netplugin#406]
Hello.I am trying to follow the Getting Started with Contiv Network Tutorial [video](https://www.youtube.com/watch?v=KzansAxCBQE&list=PL2k86RlAekM_g6csRwSRQAWvln5SmgicN&index=1), and I'm getting the following error. 

C:\Users\Dell\Desktop\netplugin> make demo
`make ssh-build
make[1]: Entering directory `C:/Users/Dell/Desktop/netplugin'
vagrant box update
==> netplugin-node2: Checking for updates to 'contiv/centos71-netplugin'
    netplugin-node2: Latest installed version: 0.3.1
    netplugin-node2: Version constraints: 0.3.1
    netplugin-node2: Provider: virtualbox
==> netplugin-node2: Box 'contiv/centos71-netplugin' (v0.3.1) is running the latest version.
CONTIV_NODE_OS= vagrant up
Bringing machine 'netplugin-node1' up with 'virtualbox' provider...
Bringing machine 'netplugin-node2' up with 'virtualbox' provider...
==> netplugin-node1: Preparing master VM for linked clones...
    netplugin-node1: This is a one time operation. Once the master VM is prepared,
    netplugin-node1: it will be used as a base for linked clones, making the creation
    netplugin-node1: of new VMs take milliseconds on a modern system.
==> netplugin-node1: Importing base box 'contiv/centos71-netplugin'...
==> netplugin-node1: Cloning VM...
==> netplugin-node1: Matching MAC address for NAT networking...
==> netplugin-node1: Checking if box 'contiv/centos71-netplugin' is up to date...
==> netplugin-node1: Setting the name of the VM: netplugin_netplugin-node1_1465873246441_89299
==> netplugin-node1: Clearing any previously set network interfaces...
==> netplugin-node1: Preparing network interfaces based on configuration...
    netplugin-node1: Adapter 1: nat
    netplugin-node1: Adapter 2: intnet
    netplugin-node1: Adapter 3: intnet
==> netplugin-node1: Forwarding ports...
    netplugin-node1: 9999 (guest) => 9999 (host) (adapter 1)
    netplugin-node1: 22 (guest) => 2222 (host) (adapter 1)
==> netplugin-node1: Running 'pre-boot' VM customizations...
==> netplugin-node1: Booting VM...
==> netplugin-node1: Waiting for machine to boot. This may take a few minutes...
    netplugin-node1: SSH address: 127.0.0.1:2222
    netplugin-node1: SSH username: vagrant
    netplugin-node1: SSH auth method: private key
    netplugin-node1: Warning: Remote connection disconnect. Retrying...
    netplugin-node1: Warning: Remote connection disconnect. Retrying...
    netplugin-node1:
    netplugin-node1: Vagrant insecure key detected. Vagrant will automatically replace
    netplugin-node1: this with a newly generated keypair for better security.
    netplugin-node1:
    netplugin-node1: Inserting generated public key within guest...
    netplugin-node1: Removing insecure key from the guest if it's present...
    netplugin-node1: Key inserted! Disconnecting and reconnecting using new SSH key...
==> netplugin-node1: Machine booted and ready!
==> netplugin-node1: Checking for guest additions in VM...
==> netplugin-node1: Mounting shared folders...
    netplugin-node1: /opt/gopath/bin => C:/Users/Dell/Desktop/netplugin/bin
    netplugin-node1: /opt/gopath/src/github.com/contiv/netplugin => C:/Users/Dell/Desktop/netplugin
==> netplugin-node1: Running provisioner: shell...
    netplugin-node1: Running: inline script
==> netplugin-node1: Running provisioner: shell...
    netplugin-node1: Running: inline script
==> netplugin-node1: Args passed: [[ netplugin-node1 192.168.2.10 192.168.2.10,192.168.2.11 etcd://localhost:2379 ]]
==> netplugin-node1: ln -s '/etc/systemd/system/docker-tcp.socket' '/etc/systemd/system/sockets.target.wants/docker-tcp.socket'
==> netplugin-node1: mkdir: cannot create directory ‘/etc/systemd/system/docker.service.d’: File exists
==> netplugin-node1: [Service]
==> netplugin-node1: Environment="no_proxy=192.168.2.10,192.168.2.11,127.0.0.1,localhost,netmaster" "http_proxy=" "https_proxy="
==> netplugin-node1: Redirecting to /bin/systemctl restart  docker.service
==> netplugin-node1: Running provisioner: shell...
    netplugin-node1: Running: inline script
==> netplugin-node1: Running provisioner: shell...
    netplugin-node1: Running: inline script
==> netplugin-node1: ++ nohup etcd --name netplugin-node1 --data-dir /tmp/etcd -heartbeat-interval=100 -election-timeout=5000 --listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 --advertise-client-urls http://192.168.2.10:2379,http://192.168.2.10:4001 --initial-advertise-peer-urls http://192.168.2.10:2380,http://192.168.2.10:7001 --listen-peer-urls http://192.168.2.10:2380 --initial-cluster netplugin-node1=http://192.168.2.10:2380,netplugin-node1=http://192.168.2.10:7001,netplugin-node2=http://192.168.2.11:2380,netplugin-node2=http://192.168.2.11:7001 --initial-cluster-state new
==> netplugin-node1: ++ nohup consul agent -server -bootstrap -bind=192.168.2.10 -data-dir /opt/consul
==> netplugin-node1: ++ nohup /opt/gopath/src/github.com/contiv/netplugin/scripts/start-swarm.sh 192.168.2.10 master
==> netplugin-node2: Cloning VM...
==> netplugin-node2: Matching MAC address for NAT networking...
==> netplugin-node2: Checking if box 'contiv/centos71-netplugin' is up to date...
==> netplugin-node2: Setting the name of the VM: netplugin_netplugin-node2_1465873290092_4091
==> netplugin-node2: Fixed port collision for 22 => 2222. Now on port 2200.
==> netplugin-node2: Clearing any previously set network interfaces...
==> netplugin-node2: Preparing network interfaces based on configuration...
    netplugin-node2: Adapter 1: nat
    netplugin-node2: Adapter 2: intnet
    netplugin-node2: Adapter 3: intnet
==> netplugin-node2: Forwarding ports...
    netplugin-node2: 22 (guest) => 2200 (host) (adapter 1)
==> netplugin-node2: Running 'pre-boot' VM customizations...
==> netplugin-node2: Booting VM...
==> netplugin-node2: Waiting for machine to boot. This may take a few minutes...
    netplugin-node2: SSH address: 127.0.0.1:2200
    netplugin-node2: SSH username: vagrant
    netplugin-node2: SSH auth method: private key
    netplugin-node2: Warning: Remote connection disconnect. Retrying...
    netplugin-node2: Warning: Remote connection disconnect. Retrying...
    netplugin-node2:
    netplugin-node2: Vagrant insecure key detected. Vagrant will automatically replace
    netplugin-node2: this with a newly generated keypair for better security.
    netplugin-node2:
    netplugin-node2: Inserting generated public key within guest...
    netplugin-node2: Removing insecure key from the guest if it's present...
    netplugin-node2: Key inserted! Disconnecting and reconnecting using new SSH key...
==> netplugin-node2: Machine booted and ready!
==> netplugin-node2: Checking for guest additions in VM...
==> netplugin-node2: Mounting shared folders...
    netplugin-node2: /opt/gopath/bin => C:/Users/Dell/Desktop/netplugin/bin
    netplugin-node2: /opt/gopath/src/github.com/contiv/netplugin => C:/Users/Dell/Desktop/netplugin
==> netplugin-node2: Running provisioner: shell...
    netplugin-node2: Running: inline script
==> netplugin-node2: Running provisioner: shell...
    netplugin-node2: Running: inline script
==> netplugin-node2: Args passed: [[ netplugin-node2 192.168.2.11 192.168.2.10,192.168.2.11 etcd://localhost:2379 ]]
==> netplugin-node2: ln -s '/etc/systemd/system/docker-tcp.socket' '/etc/systemd/system/sockets.target.wants/docker-tcp.socket'
==> netplugin-node2: mkdir: cannot create directory ‘/etc/systemd/system/docker.service.d’: File exists
==> netplugin-node2: [Service]
==> netplugin-node2: Environment="no_proxy=192.168.2.10,192.168.2.11,127.0.0.1,localhost,netmaster" "http_proxy=" "https_proxy="
==> netplugin-node2: Redirecting to /bin/systemctl restart  docker.service
==> netplugin-node2: Running provisioner: shell...
    netplugin-node2: Running: inline script
==> netplugin-node2: Running provisioner: shell...
    netplugin-node2: Running: inline script
==> netplugin-node2: ++ nohup etcd --name netplugin-node2 --data-dir /tmp/etcd -heartbeat-interval=100 -election-timeout=5000 --listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 --advertise-client-urls http://192.168.2.11:2379,http://192.168.2.11:4001 --initial-advertise-peer-urls http://192.168.2.11:2380,http://192.168.2.11:7001 --listen-peer-urls http://192.168.2.11:2380 --initial-cluster netplugin-node1=http://192.168.2.10:2380,netplugin-node1=http://192.168.2.10:7001,netplugin-node2=http://192.168.2.11:2380,netplugin-node2=http://192.168.2.11:7001 --initial-cluster-state new
==> netplugin-node2: ++ nohup consul agent -server -join 192.168.2.10 -bind=192.168.2.11 -data-dir /opt/consul
==> netplugin-node2: ++ nohup /opt/gopath/src/github.com/contiv/netplugin/scripts/start-swarm.sh 192.168.2.11 slave
vagrant ssh netplugin-node1 -c 'sudo -i bash -lc "source /etc/profile.d/envvar.sh && cd /opt/gopath/src/github.com/contiv/netplugin && make run-build"'
/etc/profile.d/envvar.sh: line 0: source: filename argument required
source: usage: source filename [arguments]
Connection to 127.0.0.1 closed.
make[1]: *** [ssh-build] Error 2
make[1]: Leaving directory `C:/Users/Dell/Desktop/netplugin'
make: *** [demo] Error 2`

**System Information :**

OS - Windows 10 (64 bit), 10GB Ram
Virtual Box - 5.0.20
vagrant - 1.8.3
netplugin version - 0.1

I am getting the above error while executing **make demo** instruction on my windows(host machine). I did a bit of debugging by doing a vagrant ssh netplugin-node1 and executing the commands **sudo -i bash -lc "source /etc/profile.d/envvar.sh && cd /opt/gopath/src/github.com/contiv/netplugin && make run-build** and found issues with make run-build.

This is my first experience with netplugin. Let me know if you need any more information. Thanks for the Help!!

**Comment by kushal25** [comment]
Hello Vipin, Thanks for the response. I am following the tutorial which you suggested. However, i've hit a roadblock. I have filed an issue on the repository jainvipin/tutorial. Kindly have a look at it. Thanks.

**Comment by gaurav-dalvi** [comment]
@kushal25 : I replied to your issues at Vipin's tutorial.

**Comment by gaurav-dalvi** [comment]
@kushal25 : Could you please confirm whether you are hitting this issue or not now ?

**Comment by kushal25** [comment]
@gaurav-dalvi Hi gaurav, we have actually moved to a different tool. You can close the issue for now. I will reopen it if needed again.

**Comment by gaurav-dalvi** [comment]
Closing !
