### ISSUE TITLE
global inspect command doesn't display correct information with non zero range

### ISSUE THREAD

**Issue by jainvipin** [contiv/netplugin#413]
when contiv is configured with a non default range `netctl global inspect` doesnt' show the range correctly.

**Comment by gaurav-dalvi** [comment]
@jainvipin I dont see this problem:

```
netctl global set --fabric-mode aci --vlan-range 1150-1170
[admin@aci-testbed-swarm-1 netplugin]$ netctl global inspect
INFO[0000] Inspecting global                            
{
  "Config": {
    "key": "global",
    "name": "global",
    "networkInfraType": "aci",
    "vlans": "1150-1170",
    "vxlans": "1-10000"
  },
  "Oper": {}
}


netctl global set --vlan-range 100-150
[admin@aci-testbed-swarm-1 netplugin]$ netctl global inspect
INFO[0000] Inspecting global                            
{
  "Config": {
    "key": "global",
    "name": "global",
    "networkInfraType": "default",
    "vlans": "100-150",
    "vxlans": "1-10000"
  },
  "Oper": {}
}

```

**Comment by gaurav-dalvi** [comment]
```
netctl version
Client Version:
Version: v0.1-06-30-2016.20-09-48.UTC
GitCommit: e1dbb39
BuildTime: 06-30-2016.20-09-48.UTC

Server Version:
Version: v0.1-06-30-2016.20-09-48.UTC
GitCommit: e1dbb39
BuildTime: 06-30-2016.20-09-48.UTC

```

**Comment by abhinandanpb** [comment]
@gaurav-dalvi i am not really sure about the issue mentioned above. But there is fundamental isssue with global set. If u see in ur example. When u set the vlan-range only , the networkInfraType got set to default. I am fixing this issue to allow stateful updates.

**Comment by gaurav-dalvi** [comment]
if u dont specify fabric mode in netctl global set CLI, I think default value is `default`.

**Comment by abhinandanpb** [comment]
@gaurav-dalvi it is expected to have default - agreed. But if you are in ACI mode already . And u issue global set --vlan-range. It will set the global mode the default. Which is not expected :)

**Comment by gaurav-dalvi** [comment]
@jainvipin : Could you please confirm on this one again ?

**Comment by gaurav-dalvi** [comment]
@jainvipin : Could you please confirm this ?
