### ISSUE TITLE
Switch policies/AEP config not supported in Contiv

### ISSUE THREAD

**Issue by santosh76** [contiv/netplugin#418]
Maybe a known issue. Filing it to document. 
While deploying contiv, realized that the phys-dom association to attached entity profile has to be done manually . I had to create the following on APIC GUI before we could deploy the policies:

1) Switch profile/Interface Profile/Policy groups.
2) Attached entity profile.
3) Phys dom association with attached entity profile.

**Comment by gaurav-dalvi** [comment]
Yes @santosh76 . You need to configure those things on APIC side in order to make this Contiv-ACI integration work. We are in the process of providing documentation for this one.

**Comment by jainvipin** [comment]
@santosh76 - as @gaurav-dalvi mentioned, this is working as designed. Contiv is not expected to take over the physical network configuration; rather work with creating tenants/epgs/app-profile/contracts for container workloads. The goal was to not create 1:1 wrapper on top of ACI object model with Contiv, rather provide the integration with container schedulers/composers.

**Comment by santosh76** [comment]
The limitation is documented. So closing this issue
