### ISSUE TITLE
Disable unsupported commands when fabric mode is ACI

### ISSUE THREAD

**Issue by santosh76** [contiv/netplugin#420]
As of now netctl bgp is not supported on ACI . However the command goes through when i execute it. 
We should throw error or disable the unsupported commands when the fabricmode is ACI

**Comment by jainvipin** [comment]
thanks @santosh76 for nothing this issue; ping @gaurav-dalvi

**Comment by gaurav-dalvi** [comment]
@jainvipin and @santosh76 : Thanks ! I will work on resolving this issue.

**Comment by gaurav-dalvi** [comment]
@abhinandanpb : regarding BGP, abhi has already fix for this. He will commit soon.

**Comment by gaurav-dalvi** [comment]
Fixed with this https://github.com/contiv/netplugin/pull/426

@santosh76  Could you please verify and close this one ?

**Comment by santosh76** [comment]
Closing  it as believed.
