### ISSUE TITLE
Add doc for steps to work on fork of project

### ISSUE THREAD

**Issue by sachja** [contiv/netplugin#43]
Based on various blogs the standard procedure to work on a fork of a go project on github seems to be as follows : 

1. Set GOPATH
2. Install the original repo and its dependencies using git get command. This actually does a git clone for all the src directories so you do not need to do that
go get -u github.com/contiv/netplugin
3. Go to the downloaded src directory
cd $GOPATH/src/github.com/contiv/netplugin
4. Do git remote add 
git remote add fork <your GitHub fork URL, pasted from the clipboard>
5. Make your code changes then:
git push fork

(if instead you wanted to just push changes to contiv repo directly you would skip step 4. Basically there is no need to do git clone either ways as go does that for you). 

e.x. see
http://blog.campoy.cat/2014/03/github-and-go-forking-pull-requests-and.html
Or, 
https://github.com/limetext/lime/wiki/Forking

If this sounds correct - let me know if I should update/add doc with this info.

**Comment by gaurav-dalvi** [comment]
@mapuri  and @sachja Can we close this issue now  ?

**Comment by mapuri** [comment]
yes, this is an old issue. Let's open new issue if needed.

**Comment by gaurav-dalvi** [comment]
Closing it now !
