### ISSUE TITLE
net-demo-installer does not work consistently

### ISSUE THREAD

**Issue by santosh76** [contiv/netplugin#432]
The script provided net-demo-installer does not work consistenly. Inspite of setting the variables, most of the time the script fails . Everytime I run the script, I have say a small prayer that it work.

It ususally fails at the following point: 

TASK [contiv_network : set aci mode] *******************************************
fatal: [node2]: FAILED! => {"changed": true, "cmd": "contivctl network global set --fabric-mode aci", "delta": "0:00:00.523233", "end": "2016-06-25 00:28:54.034586", "failed": true, "rc": 3, "start": "2016-06-25 00:28:53.511353", "stderr": "time=\"2016-06-25T00:28:54-04:00\" level=error msg=\"Post http://netmaster:9999/api/v1/globals/global/: EOF\" ", "stdout": "", "stdout_lines": [], "warnings": []}
fatal: [node1]: FAILED! => {"changed": true, "cmd": "contivctl network global set --fabric-mode aci", "delta": "0:00:00.515999", "end": "2016-06-25 00:28:53.793684", "failed": true, "rc": 3, "start": "2016-06-25 00:28:53.277685", "stderr": "time=\"2016-06-25T00:28:53-04:00\" level=error msg=\"Post http://netmaster:9999/api/v1/globals/global/: EOF\" ", "stdout": "", "stdout_lines": [], "warnings": []}
	to retry, use: --limit @./ansible/site.retry

PLAY RECAP *********************************************************************
node1                      : ok=73   changed=35   unreachable=0    failed=1   
node2                      : ok=73   changed=35   unreachable=0    failed=1   

Sometimes even if works, docker ps does not work . Sometimes I do the following , restart the hosts and run the scripts. 

sudo ovs-vsctl del-br contivVxlanBridge
sudo ovs-vsctl del-br contivVlanBridge
for p in `ifconfig  | grep vport | awk '{print $1}'`; do sudo ip link delete $p type veth; done
sudo rm /var/run/docker/plugins/netplugin.sock
On only one node do this:
sudo etcdctl rm --recursive /contiv
sudo etcdctl rm --recursive /contiv.io
sudo etcdctl rm --recursive /skydns
sudo etcdctl rm --recursive /docker
curl -X DELETE localhost:8500/v1/kv/contiv.io?recurse=true
curl -X DELETE localhost:8500/v1/kv/docker?recurse=true

Still it does not work all the time . Its very frustrating

**Comment by jainvipin** [comment]
@santosh76 - thanks for your patience.
Can you describe how are you installing the setup? Are you using `net_demo_installer -ar`. The ansible roles should take care of most of the things for cleaning up and restart.
Is it a first time setup or a re-install of newer builds, etc.?
Can you describe the version if at all you are overwriting?

**Comment by santosh76** [comment]
Everytime I am using net_demo_installer -ar. I export the following variables and run the script. 

export https_proxy=proxy.esl.cisco.com:8080
export http_proxy=proxy.esl.cisco.com:8080
export CLUSTER_NODE_IPS="10.30.120.217,10.30.120.42"
export no_proxy="10.30.120.217,10.30.120.42,127.0.0.1,localhost,netmaster"

I think in my script, the version is hardcoded 
contiv_network_version="v0.1-06-17-2016.08-42-14.UTC"
docker_version="1.11.1"

Furong/Gaurav suggested that I execute the commands mentioned above, restart the hosts and run net-demo . It worked yesterday morning. Did not work in the night . I tried 4 times today and still I am getting the same error. As I update here, the script is giving me error.

**Comment by gaurav-dalvi** [comment]
After cleaning up docker , etcd from hosts, and then cleaning up stale entries from /etc/hosts files, Issue is resolved.

**Comment by gaurav-dalvi** [comment]
on @santosh76 setup, every time he re run the script it gets stuck at set aci mode task. This is because etcd does not come up. I have to execute these commands every time before we run net_demo_install script again.

sudo ovs-vsctl del-br contivVxlanBridge
sudo ovs-vsctl del-br contivVlanBridge
for p in `ifconfig  | grep vport | awk '{print $1}'`; do sudo ip link delete $p type veth; done
sudo rm /var/run/docker/plugins/netplugin.sock
sudo yum -y remove docker-engine.x86_64
sudo rm -rf /var/lib/docker
sudo rm -rf /usr/bin/net*
sudo rm -rf /usr/bin/etcd*


Are we missing something in ansible ? @mapuri  Any views on this one ?

**Comment by gaurav-dalvi** [comment]
we get this error :


TASK [contiv_network : set aci mode] *******************************************
fatal: [node2]: FAILED! => {"changed": true, "cmd": "netctl global set --fabric-mode aci", "delta": "0:00:00.047125", "end": "2016-06-28 13:44:39.851833", "failed": true, "rc": 3, "start": "2016-06-28 13:44:39.804708", "stderr": "time=\"2016-06-28T13:44:39-04:00\" level=error msg=\"Resource with id: \\\"global\\\" already exists [github.com/contiv/netplugin/netmaster/resources.(*StateResourceManager).DefineResource stateresourcemanager.go 127]\\n\" ", "stdout": "", "stdout_lines": [], "warnings": []}

Looks like etcd cleanup is not happening.

**Comment by mapuri** [comment]
@gaurav-dalvi 

please collect following outputs when the failure is hit. It might help narrow down further.:

```
sudo journalctl -xu etcd
sudo journalctl -xu docker
sudo journalctl -xu netmaster
sudo journalctl -xu netplugin
```

**Comment by gaurav-dalvi** [comment]
@mapuri : You can check logs here :

Node 1:
ssh admin@10.193.246.4 (admin/password)
/tmp/etcd.log 
/tmp/netmaster.log
/tmp/netplugin.log
/tmp/docker.log

Node 2:
ssh admin@10.193.246.5 (admin/password)
/tmp/2etcd.log 
/tmp/2netmaster.log
/tmp/2netplugin.log
/tmp/2docker.log

**Comment by gaurav-dalvi** [comment]
fixed with this : https://github.com/contiv/ansible/pull/231

**Comment by santosh76** [comment]
Works consistently with new ansible
