### ISSUE TITLE
overlapping networks in a tenant allowed

### ISSUE THREAD

**Issue by jainvipin** [contiv/netplugin#440]
If I create two networks with different names but same subnets within a tenant, it is permitted:

```
$ netctl net create -s 10.1.1.0/24 net-one
$ netctl net create -s 10.1.1.0/24 net-two
$ netctl net ls
Tenant   Network  Nw Type  Encap type  Packet tag  Subnet       Gateway  IPv6Subnet  IPv6Gateway
------   -------  -------  ----------  ----------  -------      ------   ----------  -----------
default  net-one  data     vxlan       0           10.1.1.0/24                       
default  net-two  data     vxlan       0           10.1.1.0/24                       
```
This should not be permitted within a tenant.

**Comment by abhinandanpb** [comment]
@jainvipin which docker version are u using?

**Comment by jainvipin** [comment]
@abhinandanpb - shouldn't `netctl` disallow this, regardless of docker version?

**Comment by gaurav-dalvi** [comment]
we allow configuring networks with same parameters under two different tenants. Then why cant we allow this case ? in this case also container in different network will end up having same IP addresses.

**Comment by abhinandanpb** [comment]
@jainvipin I was of the opinion with docker 1.10+ version this should have been prevented. I will need to look at code again. 
@gaurav-dalvi : containers in different network under same tenant cant have same ip address.

**Comment by gaurav-dalvi** [comment]
@gandhihardikm is taking look at this one.

**Comment by gandhihardikm** [comment]
@jainvipin : #471 Overlappingsubnet PR merged to fix this issue. Can you please close this?

**Comment by jainvipin** [comment]
Resolved
