### ISSUE TITLE
netplugin help strings

### ISSUE THREAD

**Issue by rchirakk** [contiv/netplugin#443]
netplugin --help
-->Usage of netd:

  -vlan-if string
 ---> 	My VTEP ip address

[vagrant@netplugin-node1 ~]$ netplugin --version
Version: pv0.1-07-05-2016.15-56-54.UTC
GitCommit: d9a64ab
BuildTime: 07-05-2016.15-56-54.UTC

**Comment by gaurav-dalvi** [comment]
Please test this issue with newer version: v0.1-06-30-2016.20-09-48.UTC

**Comment by rchirakk** [comment]
its still the same in master
https://github.com/contiv/netplugin/blob/master/netplugin/netd.go

**Comment by gaurav-dalvi** [comment]
@apoorva11029 : Will take a look at this one.

**Comment by gaurav-dalvi** [comment]
@rchirakk : Looks like this is fixed. Could you please verify and then close the issue ?
