### ISSUE TITLE
any netctl command to display EPG vlan info?

### ISSUE THREAD

**Issue by fgisiger** [contiv/netplugin#457]
Is there any netctl command to display EPG vlan info? 

If not, can I suggest adding vlan info under _netctl network inspect_ command?

[admin@centos7_vm1 ~]$ netctl network inspect -t t4 bd2
INFO[0000] Inspeting network: bd2 tenant: t4            
{
  "Config": {
    "key": "t4:bd2",
    "encap": "vlan",
    "gateway": "20.10.1.1",
    "networkName": "bd2",
    "nwType": "data",
    "subnet": "20.10.1.4-20.10.1.10/24",
    "tenantName": "t4",
    "link-sets": {
      "EndpointGroups": {
        "t4:app": {          **<<< add vlan info**
          "type": "endpointGroup",
          "key": "t4:app"  
        },
        "t4:db": {              **<<< add vlan info**
          "type": "endpointGroup",
          "key": "t4:db"
        }
      }
    },
    "links": {
      "Tenant": {
        "type": "tenant",
        "key": "t4"
      }
    }
  },

**Comment by gaurav-dalvi** [comment]
@fgisiger : 
Could you please try following commands and see if it solves the purpose or not.

```
netctl global inspect
netctl network inspect <network name> or netct network inspect -t <tenant name> <network name>
netctl group inspect -t <tenant name> <group name>

```

Please use the latest netplugin version from here : https://github.com/contiv/netplugin/releases

**Comment by fgisiger** [comment]
Looks like it is working with the latest release v0.1-09-22-2016.17-21-42.UTC. Thanks for fixing this!

[root@centos7_vm1 ~]# netctl global inspect
Inspecting global
{
  "Config": {
    "key": "global",
    "fwdMode": "bridge",
    "name": "global",
    "networkInfraType": "aci",
    "vlans": "850-900",
    "vxlans": "1-10000"
  },
  "Oper": {
    "numNetworks": 4,
    "vlansInUse": "850-853"
  }
}
[root@centos7_vm1 ~]# netctl network inspect -t t1 bd2
Inspeting network: bd2 tenant: t1
{
  "Config": {
    "key": "t1:bd2",
    "encap": "vlan",
    "gateway": "20.10.1.1",
    "networkName": "bd2",
    "nwType": "data",
    "subnet": "20.10.1.4-20.10.1.10/24",
    "tenantName": "t1",
    "link-sets": {
      "EndpointGroups": {
        "t1:app": {
          "type": "endpointGroup",
          "key": "t1:app"
        }
      }
    },
    "links": {
      "Tenant": {
        "type": "tenant",
        "key": "t1"
      }
    }
  },
  "Oper": {
    "availableIPAddresses": "20.10.1.4-20.10.1.10",
    "pktTag": 851
  }
}
[root@centos7_vm1 ~]# netctl group inspect -t t1 web
Inspeting endpointGroup: web tenant: t1
{
  "Config": {
    "key": "t1:web",
    "extContractsGrps": [
      "cons-grp-1"
    ],
    "groupName": "web",
    "networkName": "bd1",
    "tenantName": "t1",
    "link-sets": {
      "ExtContractsGrps": {
        "t1:cons-grp-1": {
          "type": "extContractsGroup",
          "key": "t1:cons-grp-1"
        }
      }
    },
    "links": {
      "AppProfile": {
        "type": "appProfile",
        "key": "t1:ap"
      },
      "NetProfile": {},
      "Network": {
        "type": "network",
        "key": "t1:bd1"
      },
      "Tenant": {
        "type": "tenant",
        "key": "t1"
      }
    }
  },
  "Oper": {
    "endpoints": [
      {
        "containerID": "9f1d51ac2ee789752929fcd22ad24240f9e901f9cfcfbf2107221b504fb05713",
        "containerName": "/web",
        "endpointGroupId": 4,
        "endpointGroupKey": "web:t1",
        "endpointID": "40497dd87d8e5ea8e0c70b2fbc47a221e080cbbebed443f3734b8251f03ff650",
        "homingHost": "centos7_vm1",
        "ipAddress": [
          "10.10.1.4",
          ""
        ],
        "labels": "map[]",
        "macAddress": "02:02:0a:0a:01:04",
        "network": "bd1.t1",
        "serviceName": "web"
      }
    ],
    "numEndpoints": 1,
    "pktTag": 853
  }
}

**Comment by gaurav-dalvi** [comment]
Closing it !
