### ISSUE TITLE
ACI mode: use EPG static path binding instead of leaf binding

### ISSUE THREAD

**Issue by fgisiger** [contiv/netplugin#458]
Moving this issue to the right category for tracking purposes.

In ACI deployment, typically customer uses EPG static path binding instead of leaf binding. The key disadvantage of using leaf binding is that faults will be generated if some ports on the same switch are used for other EPGs/tenants. 

It would be nice that Contiv can support EPG static path binding to avoid such operation overheads.

**Comment by gaurav-dalvi** [comment]
This is in PR. We are tracking at different issue. Hence closing this one.
