### ISSUE TITLE
netctl policy ls does not have -a option.

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#459]
```
netctl policy ls -a
[admin@aci-testbed-swarm-1 ~]$ netctl policy ls -t t1
Tenant  Policy
------  ------
t1      app2db
```

on the other hand,

We do have 
` netctl network ls -a ` 
` netctl group ls -a `  working.

Is it expected or should we add -a option to this command as well.

**Comment by gaurav-dalvi** [comment]
@shaleman or @jainvipin : Any comments on this one ?

**Comment by shaleman** [comment]
it'll be nice to add `-a` option to policies and rules..

**Comment by gaurav-dalvi** [comment]
@reshmagiliyal  : Could you please look into this one ?

Thanks in advance !

**Comment by reshmagiliyal** [comment]
Yes. On it.

**Comment by fgisiger** [comment]
shall we add the same for _**netctl external-contracts ls**_ as well?

**Comment by gaurav-dalvi** [comment]
@fgisiger : Could you please open new issue for this ?

**Comment by fgisiger** [comment]
Just did. please see https://github.com/contiv/netplugin/issues/462

**Comment by reshmagiliyal** [comment]
Fixed it and raised a PR. 
Link to PR:- https://github.com/contiv/netplugin/pull/465/files

**Comment by gaurav-dalvi** [comment]
Closing !
