### ISSUE TITLE
netctl external-contracts ls does not have -a option

### ISSUE THREAD

**Issue by fgisiger** [contiv/netplugin#462]
It would be nice to have -a options for external contract as well. please see below

[admin@centos7_vm1 ~]$ netctl external-contracts ls -a
Incorrect Usage.

NAME:
   netctl external-contracts ls - List external contracts

USAGE:
   netctl external-contracts ls [command options] [arguments...]

OPTIONS:
   --quiet, -q			Only display name field
   --json, -j			Output list in JSON format
   --tenant, -t "default"	Name of the tenant
   
[admin@centos7_vm1 ~]$ netctl external-contracts ls -t t2
 Name: prov-grp-1    Type: provided
 Contracts:
                     uni/tn-common/brc-default
                     uni/tn-common/brc-FG_ABC
 Name: cons-grp-1    Type: consumed
 Contracts:
    uni/tn-common/brc-default
    uni/tn-common/brc-FG_ABC

**Comment by reshmagiliyal** [comment]
yes working on it

**Comment by reshmagiliyal** [comment]
Fixed it. Created the PR. https://github.com/contiv/netplugin/pull/465/files

**Comment by gaurav-dalvi** [comment]
@fgisiger : Could you please verify and then close this issue ?

**Comment by fgisiger** [comment]
@gaurav-dalvi which version should I verify this with? I just checked with v0.1-07-14-2016.07-06-17.UTC, but it is not working for me.

**Comment by gaurav-dalvi** [comment]
@fgisiger : Could you please test it with this version "v0.1-08-06-2016.07-13-09.UTC"
Thats the latest version we released recently.

**Comment by fgisiger** [comment]
@gaurav-dalvi Verified. looks good to me. thanks!

**Comment by gaurav-dalvi** [comment]
Cool. Closing it !
