### ISSUE TITLE
Unrecognized input header in Ping Tests

### ISSUE THREAD

**Issue by apoorva11029** [contiv/netplugin#479]
Running swarm on Vagrant. For tests like TestNetworkAddDeleteNoGatewayVXLAN, the checkPing test gives an Unrecognized input header error sometimes.

Error:  value errors.errorString = &errors.errorString{s:"Ping6 failed from (container: 28eb21589f6ec219c613bb6dd6e77e4e024a933aa99fcc312061117a5bffd002 (name: \"net1-1-srv3-1\" ip: 10.1.1.5 ipv6: **1001:1::5** host: netplugin-node2)) to 1001:1::4: \"Unrecognized input header\n\" - Process exited with: 1. Reason was:  ()"} 

... value errors.errorString = &errors.errorString{s:"Ping failed from (container: 8bc44e2410f0133e409a618687d3bc5ed84d65ee1378732d90c9ee00ce3fc36a (name: \"net0-0-srv0-0\" ip: 10.1.0.3 ipv6:  host: netplugin-node1)) to **response**: \"ping: bad address 'response'\n\" - Process exited with: 1. Reason was:  ()"}

**Comment by gaurav-dalvi** [comment]
@apoorva11029 : are you still seeing this error now ?
We use swarm 1.2.0.
