### ISSUE TITLE
Error logs displayed while executing system-tests

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#485]
time="Aug  2 19:19:33.297736523" level=error msg="Handler for POST /plugin/updateEndpoint returned error: 100: Key not found (/contiv.io/state/endpointGroups) [3256]" 
time="Aug  2 19:20:38.570808862" level=error msg="Handler for POST /plugin/updateEndpoint returned error: 100: Key not found (/contiv.io/state/endpointGroups) [3880]" 
time="Aug  2 19:19:32.284758576" level=error msg="Error during http POST. Err: Post http://192.168.2.10:9999/plugin/updateEndpoint: dial tcp 192.168.2.10:9999: getsockopt: connection refused" 
time="Aug  2 19:19:33.300043081" level=error msg="Error making POST request: Err: 100: Key not found (/contiv.io/state/endpointGroups) [3256]\n" 
time="Aug  2 19:19:33.300087643" level=error msg="Event: 'start' , Http error posting endpoint update, Error:100: Key not found (/contiv.io/state/endpointGroups) [3256]\n" 
time="Aug  2 19:20:37.555763741" level=error msg="Error during http POST. Err: Post http://192.168.2.10:9999/plugin/updateEndpoint: dial tcp 192.168.2.10:9999: getsockopt: connection refused" 
time="Aug  2 19:20:38.572881665" level=error msg="Error making POST request: Err: 100: Key not found (/contiv.io/state/endpointGroups) [3880]\n" 
time="Aug  2 19:20:38.572911796" level=error msg="Event: 'start' , Http error posting endpoint update, Error:100: Key not found (/contiv.io/state/endpointGroups) [3880]\n" 
#

**Comment by gaurav-dalvi** [comment]
We see this is getting dumped on console while executing system-tests. Even if system-test is passed still we see these statements.

**Comment by shaleman** [comment]
Seems like there is a mismatch of netmaster and netplugin versions.
One of the netmaster REST endpoint was renamed from /plugin/updateProvider to /plugin/updateEndpoint . Looks like netmaster here is still running older code..

**Comment by gaurav-dalvi** [comment]
@shaleman I checked on both vagrant nodes.
Same netctl, netmaster and netplugin are running.

netctl  version
Client Version:
Version: pv0.1-08-02-2016.21-41-39.UTC
GitCommit: c514779
BuildTime: 08-02-2016.21-41-39.UTC

Server Version:
Version: pv0.1-08-02-2016.21-41-39.UTC
GitCommit: c514779
BuildTime: 08-02-2016.21-41-39.UTC
[vagrant@netplugin-node1 ~]$ netmaster -version
Version: pv0.1-08-02-2016.21-41-39.UTC
GitCommit: c514779
BuildTime: 08-02-2016.21-41-39.UTC
[vagrant@netplugin-node1 ~]$ netplugin -version
Version: pv0.1-08-02-2016.21-41-39.UTC
GitCommit: c514779
BuildTime: 08-02-2016.21-41-39.UTC
[vagrant@netplugin-node1 ~]$

**Comment by gaurav-dalvi** [comment]
@abhinandanpb : Any Comments ?

**Comment by DivyaVavili** [comment]
@gaurav-dalvi When do you see this error? Is this on network creation? Do you see this on EPG creation as well?

**Comment by gaurav-dalvi** [comment]
@DivyaVavili : When you execute 
either of this command , it shows up randomly.

`go test -v -timeout 240m ./systemtests -check.v -check.f "Basic"`

or 

`go test -v -timeout 240m ./systemtests -check.v -check.f "Network"`

or 

`go test -v -timeout 240m ./systemtests -check.v -check.f "Policy"`

**Comment by abhinandanpb** [comment]
@gaurav-dalvi @DivyaVavili . I will take look at this.

**Comment by gaurav-dalvi** [comment]
not seeing these errors anymore.
