### ISSUE TITLE
How to add a gateway?

### ISSUE THREAD

**Issue by rayang2004** [contiv/netplugin#490]
I run k8s with contiv （following [https://github.com/kubernetes/contrib/tree/master/ansible](https://github.com/kubernetes/contrib/tree/master/ansible) ）,but I can't ping the gateway over vxlan,so pods in k8s can't connect to the internet and skyDNS.Any help?

**Comment by gaurav-dalvi** [comment]
@jojimt : Might be able to help here .

**Comment by matjohn2** [comment]
@rayang2004 What was the solution here?
Thanks

**Comment by rayang2004** [comment]
@matjohn2  Finnaly I use kubadm & "kubectl apply -f https://raw.githubusercontent.com/contiv/install/master/install/k8s/k8s1.4/contiv.yaml".
