### ISSUE TITLE
feature: improve logging

### ISSUE THREAD

**Issue by jainvipin** [contiv/netplugin#50]
log messages do not need to be all on stdout:
- user option is to be provided to keep the logs in specific directory (logs directory) and a log file name picked in the location
- log messages to have ability to specify the severity fatal/critical, error, warning, info, verbose, extra-verbose
- standard formatting of the messages, per golang's log utilities

**Comment by erikh** [comment]
https://github.com/Sirupsen/logrus might be a good thing here; already in use in docker so it'll be familiar territory for many.

I'm going to tackle this tomorrow, do you have any additional concerns?

**Comment by erikh** [comment]
Sorry, I should have stated *why* logrus is a good idea. :)

I can use the `log` package but it's kind of fiddly, especially when it comes to syslog support (if we wanted to do that). glog can log to a socket but that's unfamiliar for many. logrus can do [numerous outputs](https://github.com/Sirupsen/logrus#hooks) which might prove useful to expose to our consumers.

**Comment by jainvipin** [comment]
@erikh - I am not familiar with other packages. Let's go with your best pick.

**Comment by gaurav-dalvi** [comment]
@jainvipin : Can we close this issue now ?

**Comment by jainvipin** [comment]
sure - with multi-level logging I think we have basics!
