### ISSUE TITLE
Netplugin crashes when network is created post make demo

### ISSUE THREAD

**Issue by abhinandanpb** [contiv/netplugin#524]
Looks like skydns container is detached when startSwarm is run and netplugin fails to find the dns container when network is created.

Steps:
make demo
netctl network create orange -s 10.1.1.0/24 -g 10.1.1.254

**Comment by gaurav-dalvi** [comment]
not able to reproduce the problem. 

Changed the documentation https://github.com/contiv/contiv.github.io/pull/29
Checked with @shaleman . We dont need to set DOCKER_HOST in our scripts. 

also its ok to run swarm-manager and swarm-agent on all the nodes.

**Comment by gaurav-dalvi** [comment]
Closing as not able to reproduce !
