### ISSUE TITLE
Unable to run 'make demo' successfully

### ISSUE THREAD

**Issue by adammy123** [contiv/netplugin#526]
While running `make demo`:

```
==> netplugin-node1: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "d77d926b-ee2d-48bc-aeea-f8ba1bb6e54b", "--type", "headless"]

Stderr: VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

make[1]: *** [start] Error 1
make[1]: Leaving directory `/root/Contiv/netplugin'
make: *** [demo] Error 2
```

Not sure how to go about this, I'm running this on a VM running on CentOS 7.
`Vagrant --version` 1.8.5

**Comment by jainvipin** [comment]
@adammy123 - seems like it can be due to: 
- Either VT-X is not enabled on your machine, which most of the modern systems/cpus are equipped with
- Or, if you are doing `make-demo` inside a VM then it would not work, as mentioned in https://www.virtualbox.org/ticket/4032 (see the last comment)

It is best to try this on OS-X, or Linux bare-metal. The docs deserve a note on this.

**Comment by gaurav-dalvi** [comment]
@adammy123 : Thanks for this. I believe you are trying to do this on Windows.
@jainvipin : Will make note in our docs page.

**Comment by adammy123** [comment]
@gaurav-dalvi Hi, as mentioned earlier it is run on a VM running on CentOS 7, deployed by VMware VSphere.

**Comment by jainvipin** [comment]
@adammy123 - it would be best in that case to install Contiv using: 
http://contiv.github.io/documents/gettingStarted/networking/index.html
for example if you are installing this using swarm, you could use: 
http://contiv.github.io/documents/gettingStarted/networking/install-swarm.html

Nested VMs should work on VMWare vSphere, provided you allocated sufficient memory/vcpus to them.

How about if we get back to you on that with a local run, meanwhile you could install Contiv and play with it using the above in your system?

**Comment by gaurav-dalvi** [comment]
@adammy123 : Could you please check whether you are seeing this issue or not ?

**Comment by gaurav-dalvi** [comment]
@adammy123 : gentle reminder. Please let us know.

**Comment by adammy123** [comment]
@gaurav-dalvi hey, I stopped working on this project already. Sorry for the late response.
