### ISSUE TITLE
Tenant is not getting deleted in APIC when running "netctl tenant rm <Tenant ID> from Controller

### ISSUE THREAD

**Issue by pradvara** [contiv/netplugin#529]
Steps to Reproduce:

- Create a tenant, apply  policy and create EPG with app-profile.
netctl global set --fabric-mode aci --vlan-range 101-110
netctl global info
netctl tenant create india
netctl tenant ls
netctl net create -t india -e vlan -pkt-tag=103 -s 103.1.1.1/24 -g 103.1.1.254 net1
netctl policy create -t india net1-pol
netctl group create -t india -p net1-pol net1 net1-grp
netctl policy rule-add net1-pol 1 --tenant india -direction=in -protocol=tcp -action=allow
netctl app-profile create -t india -g net1-grp net1

- The tenant and application profile gets created in APIC successfully.

[stack@aci-rack1 ~]$ netctl group list -t india
Tenant  Group     Network  Policies
------  -----     -------  --------
india   net1-grp  net1     net1-pol

- Remove the policies and delete the tenant using "netctl tenant rm".
[stack@aci-rack1 ~]$ netctl tenant list
Name
------
default

- Tenant gets removed from the controller.

- In APIC the application profiles are deleted, but the tenant is not getting removed.

![apic_tenant_rm](https://cloud.githubusercontent.com/assets/17447320/17775813/9fe0c2ac-6577-11e6-8ecf-d33b52308a87.jpg)

**Comment by jojimt** [comment]
This is by design. A tenant in APIC could mean more than just the container cluster. If desired, the tenant can be deleted from APIC (contiv ui is not intended to replace the APIC ui).
