### ISSUE TITLE
netctl global info command is missing fwd-mode

### ISSUE THREAD

**Issue by shaleman** [contiv/netplugin#532]
`netctl global info` command is missing forwarding mode.
Its present in global inspect command though..
just noting it here before i forget..

[vagrant@netplugin-node1 libcompose]$ netctl global info
Fabric mode: default
Vlan Range: 1-4094
Vxlan range: 1-10000
[vagrant@netplugin-node1 libcompose]$ netctl global inspect
Inspecting global
{
  "Config": {
    "key": "global",
    "fwdMode": "routing",
    "name": "global",
    "networkInfraType": "default",
    "vlans": "1-4094",
    "vxlans": "1-10000"
  },
  "Oper": {}
}
[vagrant@netplugin-node1 libcompose]$

**Comment by apoorva11029** [comment]
@shaleman I included this with PR for Issue#525. Please check.

**Comment by gaurav-dalvi** [comment]
PR - https://github.com/contiv/netplugin/pull/539  is raised for this.

**Comment by gaurav-dalvi** [comment]
Fixed via this PR : https://github.com/contiv/netplugin/pull/539

**Comment by gaurav-dalvi** [comment]
Closing it !
