### ISSUE TITLE
make demo is failing with today's (22nd August) netplugin code 

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#537]
Error : 

Simple error. But still wondering how come our sanity did not catch this.

```
# github.com/contiv/netplugin/netctl
netctl/netctl.go:622: undefined: argCheck
```

**Comment by gaurav-dalvi** [comment]
two PRs merging order caused this issue.

**Comment by gaurav-dalvi** [comment]
PR : https://github.com/contiv/netplugin/pull/528

and 

PR : https://github.com/contiv/netplugin/pull/527

**Comment by jainvipin** [comment]
@gaurav-dalvi - per @shaleman's comment argcheck in #527 should have been removed, wonder why it didn't

**Comment by gaurav-dalvi** [comment]
@jainvipin : 
after this my PR was merged and I had that check and thats why its failing.

**Comment by rchirakk** [comment]
I have added a fix  in this PR as my commit build was failing,
https://github.com/contiv/netplugin/pull/536

**Comment by gaurav-dalvi** [comment]
@rchirakk : Please dont do that.
I am thinking of omitting this PR https://github.com/contiv/netplugin/pull/527 from our main repo. It broke some other functionality as well.

Waiting for @shaleman to comment on this one.

**Comment by gaurav-dalvi** [comment]
PR - https://github.com/contiv/netplugin/pull/539  is raised for this.

**Comment by gaurav-dalvi** [comment]
Fixed via this PR : https://github.com/contiv/netplugin/pull/539

**Comment by gaurav-dalvi** [comment]
Closing it !
