### ISSUE TITLE
network config in etcd not getting cleaned after removing the configuration in APIC and Contiv setup

### ISSUE THREAD

**Issue by pradvara** [contiv/netplugin#540]
- Network is created in 103.1.1.0/24 network:
[stack@aci-rack1 ~]$ netctl net list -t india
Tenant  Network  Nw Type  Encap type  Packet tag  Subnet        Gateway      IPv6Subnet  IPv6Gateway
------  -------  -------  ----------  ----------  -------       ------       ----------  -----------
india   net1     data     vlan        0           103.1.1.0/24  103.1.1.254

- Able to view the network through docker
[stack@aci-rack1 ~]$ docker network ls
NETWORK ID          NAME                        DRIVER
e8d943a5c817        aci-rack1/bridge            bridge
6c284567ecac        aci-rack1/docker_gwbridge   bridge
b61a47086153        aci-rack1/host              host
6c258d117c9a        aci-rack1/none              null
a6654c7394b5        aci-rack3/bridge            bridge
7861fb1ed3f8        aci-rack3/host              host
763de7088884        aci-rack3/none              null
ba588fa2740b        aci-rack4/bridge            bridge
a5b6fa72ddc5        aci-rack4/docker_gwbridge   bridge
1793285de524        aci-rack4/host              host
b8b9f3fbde3e        aci-rack4/none              null
270a3baf2adf        aci-rack5/bridge            bridge
966e765f0ed5        aci-rack5/docker_gwbridge   bridge
6d9ccccf3376        aci-rack5/host              host
15509418a12a        aci-rack5/none              null
d899e878e167        db/india                    netplugin

- Docker inspection shows different subnet
[stack@aci-rack1 ~]$ docker network inspect db/india
[
    {
        "Name": "db/india",
        "Id": "d899e878e167c7133c0fc596579526e079789ee1147e2a56140ad401761823ad",
        "Scope": "global",
        "Driver": "netplugin",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "netplugin",
            "Options": {
                "network": "net1",
                "tenant": "india"
            },
            "Config": [
                {
                    "Subnet": "101.1.1.0/24",
                    "Gateway": "101.1.1.254"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "36926a569c36a42c47c417075102352331726c5888590d1e66f0f170f9439f3e": {
                "Name": "app1",
                "EndpointID": "ee9e3ceb12da60947499fc9e7f84d763ccd95cccd75a7ca54be0ba6461484524",
                "MacAddress": "02:02:65:01:01:01",
                "IPv4Address": "101.1.1.1/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "encap": "vlan",
            "pkt-tag": "101",
            "tenant": "india"
        },
        "Labels": {}
    }
]

- Container is ceated in different network rather than network created.
[stack@aci-rack5 ucp-bundle-admin]$ docker exec -it 36926a569c36 /bin/sh
/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
200: eth0@if199: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue state UP
    link/ether 02:02:65:01:01:01 brd ff:ff:ff:ff:ff:ff
    inet 101.1.1.1/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::2:65ff:fe01:101/64 scope link
       valid_lft forever preferred_lft forever

[stack@aci-rack1 ~]$ sudo systemctl status netplugin -l
● netplugin.service - Netplugin
   Loaded: loaded (/etc/systemd/system/netplugin.service; static; vendor preset: disabled)
   Active: active (running) since Tue 2016-08-23 13:53:27 IST; 7h ago
 Main PID: 11649 (netplugin)
   CGroup: /system.slice/netplugin.service
           └─11649 /usr/bin/netplugin -plugin-mode docker -vlan-if enp9s0 -vtep-ip 10.106.240.92 -ctrl-ip 10.106.240.92

Aug 23 20:03:23 aci-rack1 netplugin[11649]: time="Aug 23 20:03:23.253612807" level=info msg="Deleted flow: {\"Priority\":100,\"InputPort\":0,\"MacDa\":null,\"MacDaMask\":null,\"MacSa\":null,\"MacSaMask\":null,\"Ethertype\":2048,\"VlanId\":0,\"ArpOper\":0,\"IpSa\":null,\"IpSaMask\":null,\"IpDa\":\"101.1.1.1\",\"IpDaMask\":null,\"Ipv6Sa\":null,\"Ipv6SaMask\":null,\"Ipv6Da\":null,\"Ipv6DaMask\":null,\"IpProto\":0,\"TcpSrcPort\":0,\"TcpDstPort\":0,\"UdpSrcPort\":0,\"UdpDstPort\":0,\"Metadata\":4294967296,\"MetadataMask\":1095216660480,\"TunnelId\":0,\"TcpFlags\":null,\"TcpFlagsMask\":null}"
Aug 23 20:05:25 aci-rack1 netplugin[11649]: time="Aug 23 20:05:25.227515260" level=info msg="EndpointAdd rpc call for endpoint: &{EndpointID:101.1.1.1:india EndpointType:internal EndpointGroup:6 IpAddr:101.1.1.1 IpMask:255.255.255.255 Ipv6Addr:<nil> Ipv6Mask:<nil> Vrf:india MacAddrStr:02:02:65:01:01:01 Vlan:101 Vni:0 OriginatorIp:10.106.240.97 PortNo:9 Timestamp:2016-08-23 20:06:25.556246151 +0530 IST EndpointGroupVlan:102}. localIp: 10.106.240.92"
Aug 23 20:05:25 aci-rack1 netplugin[11649]: time="Aug 23 20:05:25.227593780" level=info msg="Received endpoint: &{EndpointID:101.1.1.1:india EndpointType:internal EndpointGroup:6 IpAddr:101.1.1.1 IpMask:255.255.255.255 Ipv6Addr:<nil> Ipv6Mask:<nil> Vrf:india MacAddrStr:02:02:65:01:01:01 Vlan:101 Vni:0 OriginatorIp:10.106.240.97 PortNo:9 Timestamp:2016-08-23 20:06:25.556246151 +0530 IST EndpointGroupVlan:102}"
Aug 23 20:05:25 aci-rack1 netplugin[11649]: time="Aug 23 20:05:25.228999798" level=info msg="Adding dst group entry for endpoint: &{EndpointID:101.1.1.1:india EndpointType:internal EndpointGroup:6 IpAddr:101.1.1.1 IpMask:255.255.255.255 Ipv6Addr:<nil> Ipv6Mask:<nil> Vrf:india MacAddrStr:02:02:65:01:01:01 Vlan:101 Vni:0 OriginatorIp:10.106.240.97 PortNo:9 Timestamp:2016-08-23 20:06:25.556246151 +0530 IST EndpointGroupVlan:102}"
Aug 23 20:05:25 aci-rack1 netplugin[11649]: time="Aug 23 20:05:25.229103207" level=info msg="Recevied add endpoint for vrf india"
Aug 23 20:05:25 aci-rack1 netplugin[11649]: time="Aug 23 20:05:25.231734448" level=info msg="EndpointAdd rpc call for endpoint: &{EndpointID:101.1.1.1:india EndpointType:internal EndpointGroup:6 IpAddr:101.1.1.1 IpMask:255.255.255.255 Ipv6Addr:<nil> Ipv6Mask:<nil> Vrf:india MacAddrStr:02:02:65:01:01:01 Vlan:101 Vni:0 OriginatorIp:10.106.240.97 PortNo:9 Timestamp:2016-08-23 20:06:25.556246151 +0530 IST EndpointGroupVlan:102}. localIp: 10.106.240.92"
Aug 23 20:05:25 aci-rack1 netplugin[11649]: time="Aug 23 20:05:25.234723912" level=info msg="EndpointAdd rpc call for endpoint: &{EndpointID:101.1.1.1:india EndpointType:internal EndpointGroup:6 IpAddr:101.1.1.1 IpMask:255.255.255.255 Ipv6Addr:<nil> Ipv6Mask:<nil> Vrf:india MacAddrStr:02:02:65:01:01:01 Vlan:101 Vni:0 OriginatorIp:10.106.240.97 PortNo:9 Timestamp:2016-08-23 20:06:25.556246151 +0530 IST EndpointGroupVlan:102}. localIp: 10.106.240.92"
Aug 23 20:05:25 aci-rack1 netplugin[11649]: time="Aug 23 20:05:25.237190330" level=info msg="EndpointAdd rpc call for endpoint: &{EndpointID:101.1.1.1:india EndpointType:internal EndpointGroup:6 IpAddr:101.1.1.1 IpMask:255.255.255.255 Ipv6Addr:<nil> Ipv6Mask:<nil> Vrf:india MacAddrStr:02:02:65:01:01:01 Vlan:101 Vni:0 OriginatorIp:10.106.240.97 PortNo:9 Timestamp:2016-08-23 20:06:25.556246151 +0530 IST EndpointGroupVlan:102}. localIp: 10.106.240.92"
Aug 23 20:05:25 aci-rack1 netplugin[11649]: time="Aug 23 20:05:25.242460558" level=info msg="EndpointAdd rpc call for endpoint: &{EndpointID:101.1.1.1:india EndpointType:internal EndpointGroup:6 IpAddr:101.1.1.1 IpMask:255.255.255.255 Ipv6Addr:<nil> Ipv6Mask:<nil> Vrf:india MacAddrStr:02:02:65:01:01:01 Vlan:101 Vni:0 OriginatorIp:10.106.240.97 PortNo:9 Timestamp:2016-08-23 20:06:25.556246151 +0530 IST EndpointGroupVlan:102}. localIp: 10.106.240.92"
Aug 23 20:05:25 aci-rack1 netplugin[11649]: time="Aug 23 20:05:25.242951985" level=info msg="EndpointAdd rpc call for endpoint: &{EndpointID:101.1.1.1:india EndpointType:internal EndpointGroup:6 IpAddr:101.1.1.1 IpMask:255.255.255.255 Ipv6Addr:<nil> Ipv6Mask:<nil> Vrf:india MacAddrStr:02:02:65:01:01:01 Vlan:101 Vni:0 OriginatorIp:10.106.240.97 PortNo:9 Timestamp:2016-08-23 20:06:25.556246151 +0530 IST EndpointGroupVlan:102}. localIp: 10.106.240.92"

[stack@aci-rack1 ~]$ netmaster --version
Version: v0.1-08-10-2016.10-55-19.UTC
GitCommit: f63775c
BuildTime: 08-10-2016.10-55-19.UTC

Cleanup is not done properly here

Earlier, the app profiles, groups ,policies and tenants are removed from Contiv and APIC and the networks are created.

**Comment by gaurav-dalvi** [comment]
Right now we only delete app-profile from ACI as well as Contiv side when you delete it from contiv side.

This is expected behavior from day 1. Please let us know use case where you want everything to be cleared from contiv side when you clear it from ACI side.

This is certainly doable but right now we dont support it.

**Comment by pradvara** [comment]
@gaurav-dalvi , please correct me if i am wrong here

Above issue pertains to case where I removed all the configurations in Contiv as well as in ACI.

- Created a new network(103).
- I saw the same older network subnet(101) when i did '''docker network inspect''' on the created network.
- The container was also created with old subnet (101)

**Comment by gaurav-dalvi** [comment]
@pradvara :

unless you push app-profile new changes at contiv side does not take effect in ACI side.

Let me know if you still face the issue after this procedure.
1: Create tenant, network, EPG and app-profile at Contiv side.
2: You will see EPG, Network, App-profile and tenant got created at APIC side.
3: Create containers out of epg named network and then see if ACI has learned that endpoint or not.
4: Now delete app-profile from Contiv side and It should get deleted from APIC. (But other parameters remain as it as at Contiv as well ACI side, its expected)


Repeat step 1 to 4 for any new tenant or new network and then create new EPG under that and then push new app-profile. It should work.

**Comment by pradvara** [comment]
@gaurav-dalvi 

1. I have decommissioned all the nodes.
2. Commissioned nodes again with master and worker nodes.
3. Created tenant, network, EPG and app-profile at Contiv side with network 103.1.1.0/24
4.I am seeing EPG, network, app-profile and tenant in APIC.
5. Created containers and the  MAC addresses are learnt in EPG.
6. Deleted the policy, app-profile, groups and tenants from Contiv side.
7. Deleted the same in APIC along with tenant.

8. Followed the same procedure as above but created network with 105.1.1.0/24.

[stack@aci-rack1 ~]$ netctl net ls -t india
Tenant  Network  Nw Type  Encap type  Packet tag  Subnet        Gateway      IPv6Subnet  IPv6Gateway
------  -------  -------  ----------  ----------  -------       ------       ----------  -----------
india   net1     data     vlan        105         105.1.1.0/24  105.1.1.254


Docker network inspect of the above created network is still showing the same old network

[stack@aci-rack1 ~]$ docker network inspect db/india
[
    {
        "Name": "db/india",
        "Id": "4f266f26a5bfc337c0de3e959f90247c8724c4c89ae7d3c06569598dea309a91",
        "Scope": "global",
        "Driver": "netplugin",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "netplugin",
            "Options": {
                "network": "net1",
                "tenant": "india"
            },
            "Config": [
                {
                    "Subnet": "103.1.1.0/24",
                    "Gateway": "103.1.1.254"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {
            "encap": "vlan",
            "pkt-tag": "103",
            "tenant": "india"
        },
        "Labels": {}
    }
]


Created new container and the old network IP from 103 subnet is getting assigned to the container.

Please correct if i am wrong anywhere

**Comment by gaurav-dalvi** [comment]
Fixed via this PR : https://github.com/contiv/netplugin/pull/544

**Comment by gaurav-dalvi** [comment]
@pradvara : Please confirm and then I will close this issue !

**Comment by gaurav-dalvi** [comment]
Closing it !

**Comment by pradvara** [comment]
verified BUG in ```contiv_network_version: v0.1-09-08-2016.20-56-40.UTC```   
Issue not found in this build
