### ISSUE TITLE
integration test fails with concurrent map error

### ISSUE THREAD

**Issue by rchirakk** [contiv/netplugin#545]
NFO[0011] Local endpoint removed and withdrawn successfully 
INFO[0011] Deleting Veth pairs with name: vvport22, vport22 
fatal error: concurrent map writes

goroutine 3320 [running]:
runtime.throw(0x1392c90, 0x15)
        /usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc8208d3ba8 sp=0xc8208d3b90
runtime.mapdelete(0xe8a1c0, 0xc8203ee780, 0xc8208d3c78)
        /usr/local/go/src/runtime/hashmap.go:559 +0x5a fp=0xc8208d3c08 sp=0xc8208d3ba8
github.com/contiv/netplugin/drivers.(*OvsDriver).DeleteEndpoint(0xc820428240, 0xc8202497a0, 0x1d, 0x0, 0x0)
        /opt/gopath/src/github.com/contiv/netplugin/drivers/ovsdriver.go:533 +0x493 fp=0xc8208d3d88 sp=0xc8208d3c08
github.com/contiv/netplugin/netplugin/plugin.(*NetPlugin).DeleteEndpoint(0xc82048d7c0, 0xc8202497a0, 0x1d, 0x0, 0x0)
        /opt/gopath/src/github.com/contiv/netplugin/netplugin/plugin/netplugin.go:135 +0x5a fp=0xc8208d3dc8 sp=0xc8208d3d88
github.com/contiv/netplugin/test/integration.(*integTestSuite).deleteEndpoint(0x1b80840, 0x12ad460, 0x7, 0x12b2278, 0x4, 0x0, 0x0, 0xc82065eff0, 0x0, 0x0)
        /opt/gopath/src/github.com/contiv/netplugin/test/integration/utils_test.go:170 +0x2ba fp=0xc8208d3ed0 sp=0xc8208d3dc8
github.com/contiv/netplugin/test/integration.(*integTestSuite).deleteEndpointsParallel.func1(0x1b80840, 0x12ad460, 0x7, 0x12b2278, 0x4, 0x0, 0x0, 0xc8204045a0, 0xc82065eff0)
        /opt/gopath/src/github.com/contiv/netplugin/test/integration/utils_test.go:187 +0x80 fp=0xc8208d3f48 sp=0xc8208d3ed0
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8208d3f50 sp=0xc8208d3f48
created by github.com/contiv/netplugin/test/integration.(*integTestSuite).deleteEndpointsParallel
        /opt/gopath/src/github.com/contiv/netplugin/test/integration/utils_test.go:189 +0x145

**Comment by gaurav-dalvi** [comment]
@rchirakk : is it continuously reproducible ? When I ran on laster 29th Aug code I did not get this error.

**Comment by rchirakk** [comment]
@gaurav-dalvi this happens at random caused by concurrent map writes.

**Comment by abhinandanpb** [comment]
fixed by #560
