### ISSUE TITLE
K8master install failure - systemd/firewalld/netaddr/ issues

### ISSUE THREAD

**Issue by vramakrishnan** [contiv/netplugin#566]
I followed the steps for installing kubernetes+contiv listed here.
http://contiv.github.io/documents/gettingStarted/networking/k8s.html

I have installed virtualbox+vagrant on MAC OSX and was able to navigate the dependancies and few installation issues and got this far, but running into last set of **three failures.** 

Do we need python-firewall and python-netaddr lib/modules on MAC host or the VMs where K8 master is run ? Is this known issue and please recommend steps to fix this.

------------- Console logs ------------------------------

TASK [contiv : stop aci-gw] ****************************************************
f**atal: [k8master]: FAILED! => {"changed": false, "failed": true, "msg": "systemd could not find the requested service \"'aci-gw'\": "}
...ignoring**

TASK [master : Open firewalld port for apiserver] ******************************
fatal: [k8master]: FAILED! => {"changed": false, "failed": true, "msg": "firewalld and its python 2 module are required for this module"}
...ignoring

TASK [master : Save firewalld port for apiserver] ******************************
**fatal: [k8master]: FAILED! => {"changed": false, "failed": true, "msg": "firewalld and its python 2 module are required for this module"}**

TASK [kubernetes-addons : DNS | Install Template from converted saltfiles] *****
changed: [k8master] => (item=skydns-rc.yaml)
**failed: [k8master] (item=skydns-svc.yaml) => {"failed": true, "item": "skydns-svc.yaml", "msg": "AnsibleFilterError: {{ kube_service_addresses|ipaddr('net')|ipaddr(10)|ipaddr('address') }}: The ipaddr filter requires python-netaddr be installed on the ansible controller"}**

NO MORE HOSTS LEFT *************************************************************
       	to retry, use: --limit @./contrib/ansible/cluster.retry

PLAY RECAP *********************************************************************
k8master                   : ok=191  changed=67   unreachable=0    failed=1
k8node-01                  : ok=45   changed=10   unreachable=0    failed=0
k8node-02                  : ok=45   changed=10   unreachable=0    failed=0
k8node-03                  : ok=45   changed=10   unreachable=0    failed=0

make: *** [k8s-cluster] Error 1

**Comment by jojimt** [comment]
The ipaddr filter requires python-netaddr be installed on the *ansible controller*
That means the machine where you are invoking the script, i.e. the Mac

**Comment by vramakrishnan** [comment]
Thanks and that did the trick.

PLAY RECAP *********************************************************************
k8master                   : ok=192  changed=26   unreachable=0    failed=0
k8node-01                  : ok=133  changed=55   unreachable=0    failed=0
k8node-02                  : ok=129  changed=55   unreachable=0    failed=0
k8node-03                  : ok=129  changed=55   unreachable=0    failed=0
