### ISSUE TITLE
Install netplugin for docker using consul

### ISSUE THREAD

**Issue by tlvenn** [contiv/netplugin#570]
Hi,

I have a consul cluster as well as nomad cluster using docker as container engine.
I would like to install netplugin to provide multi host containers connectivity using consul to save state but I cant seem to find any documentation on how to get started.

Any help would be greatly appreciated, thanks in advance !

**Comment by abhinandanpb** [comment]
@tlvenn the nomad + contiv doc is at http://contiv.github.io/documents/samples/nomad.html
If you are just trying out contiv with nomad then the above document provides a vagrant demo tryout to play with contiv. Please let us know if you need more info.

**Comment by tlvenn** [comment]
Hi @abhinandanpb,

I saw this document but the assumption with vagrant image is that the netplugin is already installed and configured and that is the missing piece for me right now.

Is there a binary package I can download or should i build it myself ?Is there more than one services that need to be running (I think there are 2 actually) ? What configuration file each of those are expecting and how do I make them work with consul ?

Thanks in advance for any guidance in this regard.

**Comment by abhinandanpb** [comment]
ah ok ! So at this point of time we have installer for docker swarm and kubernetes environments. We are in the process of finishing Mesos as well.
 
However I would suggest checking our cluster repo - https://github.com/contiv/cluster which will help you deploy contiv services and install all the dependent services like consul/etcd , docker etc.  The other option is to use - https://github.com/contiv/demo/tree/master/net - this is an installer script that will use ansible to install all the contiv and its dependent services. In fact our Vagrant images are built using the same ansible scripts. 

Contiv supports both consul and etcd. You can then run nomad on top of it. We have also containerized contiv services. However we are in the process of testing the same and may need some tweaking and doc updates.- https://github.com/contiv/netplugin/tree/master/scripts/netContain.

**Comment by abhinandanpb** [comment]
@tlvenn to add to that - we do have a customer who has deployed contiv with nomad using our ansible playbook  here - https://github.com/contiv/ansible. Both cluster and net_demo_installer that i have mentioned above uses the same ansible playbook underneath.

**Comment by tlvenn** [comment]
Thanks for the follow up @abhinandanpb !

I will look into the ansible playbook then to deploy netplugin. You mentioned Docker Swarm, can netplugin works as a docker network plugin without docker swarm ?

I also wanted to confirm that netplugin can be run on hosts with a single network interface.

**Comment by abhinandanpb** [comment]
@tlvenn : To answer your question about docker swarm. Yes it will work without swarm as well. 

At this point of time we will need 2 interfaces - one for control and one for data interface. The need for data interface becomes mandatory depending on the mode you are trying to use.
If the purpose of using contiv is to get native vlan networking (either Layer 2 or Layer 3 BGP networking) then the need for data interface becomes necessary. If you are trying out for overlay networking (vxlan based overlays) then it may not be a necessity.

**Comment by tlvenn** [comment]
Good to hear it can work with Docker without swarm.

Regarding network topology, I am interested into vxlan based overlays and not native vlan networking. Is there an issue to track being able to use Netplugin with vxlan on a single interface ?

Thanks again.

**Comment by ramukima** [comment]
I am looking to run contiv networking on a bare-metal (standalone) to use with docker. I have consul running. Is there a reference documentation to install on bare-metal ?

**Comment by gaurav-dalvi** [comment]
@ramukima : Please take a look at this one : https://github.com/contiv/demo/tree/master/net 

this script uses ansible to provision necessary services required by contiv and installs contiv on the top of docker swarm as well.
Do you have any specific requirement with consul ? By default we run etcd. But we do support consul as well.

**Comment by ramukima** [comment]
I looked at the repository. I want to use contiv just with Docker and Consul, no Swarm. Later, I would like to add such an orchestration tool on top. Is there any reference ? 

etcd is OK for my exploration, but eventually will need to use Consul.

**Comment by gaurav-dalvi** [comment]
You should download netplugin and netmaster (contiv) binaries from here : https://github.com/contiv/netplugin/releases

To start netplugin : sudo ./netplugin -vlan-if <Data interface> -ctrl-ip <Control IP>
You can start netmaster like ./netmaster 
or Please take a look at this : https://github.com/contiv/netplugin/tree/master/scripts/netContain

Also regarding consul , I will let @jojimt to comment on this one.

**Comment by ramukima** [comment]
Thanks @gaurav-dalvi , exactly what I was looking for. Will try.
