### ISSUE TITLE
skydns still use the old etcd port

### ISSUE THREAD

**Issue by sdurrheimer** [contiv/netplugin#572]
Hi there,

It would be nice to change the `ETCD_MACHINES` envvar of `skydns` in order to use the current `2379` port of `etcd`, or even better, use both `2379` and `4001` ports to keep backward compatibility.

**Comment by gaurav-dalvi** [comment]
@rchirakk

**Comment by unclejack** [comment]
We don't use SkyDNS any more. I'll close this issue now.
