### ISSUE TITLE
Cleanup scripts cause error in SkyDNS configuration

### ISSUE THREAD

**Issue by srampal** [contiv/netplugin#573]
vagrant based setup
1) Use "make demo" to build a demo configuration
2) Use "netctl network create <container_name> --subnet=" to create a new network
3) Use "netctl network inspect <container_name" to inspect this network
     The skydns endpoint is shown in this network automatically created by default
4) Now do  "make host-cleanup", "make host-build" and "make host-restart"
5) Create one or two new networks again similar to step (2).
6) Now, inspect these networks similar to step (3).
     For one or both of the new networks you will not see any endpoint corresponding to skydns

**Comment by gaurav-dalvi** [comment]
PR : https://github.com/contiv/netplugin/pull/582

@srampal : Could you please verify this ?

**Comment by gaurav-dalvi** [comment]
PR is closed and merged !
Closing this Issue.
