### ISSUE TITLE
unable to ping container using container name

### ISSUE THREAD

**Issue by fgisiger** [contiv/netplugin#574]
Not sure if this is expected, but I am not able to ping containers using their container names.

I have two containers as below: 
app1: 20.1.1.1
db1: 20.1.1.2

**_from app1:_** 
root@101c62482eca:/pycode# ping app1       <<< ping to local works fine
PING app1 (20.1.1.1): 56 data bytes
64 bytes from 20.1.1.1: icmp_seq=0 ttl=64 time=0.091 ms
64 bytes from 20.1.1.1: icmp_seq=1 ttl=64 time=0.093 ms

root@101c62482eca:/pycode# ping 20.1.1.2      <<< ping to db1 IP works fine
64 bytes from 20.1.1.2: icmp_seq=18 ttl=64 time=0.996 ms
64 bytes from 20.1.1.2: icmp_seq=19 ttl=64 time=0.563 ms
64 bytes from 20.1.1.2: icmp_seq=20 ttl=64 time=0.417 ms

root@101c62482eca:/pycode# ping db1          <<< ping to db1 name not working
ping: unknown host

**Comment by gaurav-dalvi** [comment]
Hello Furong,

You need to start container with --dns option. Here is the example.

```
docker run -itd --net="n1" -name=web --dns=<IP address of DNS Container> alpine sh

you can get IP of DNS container by doing docker inspect on skydns container in contiv cluster.
```

Could you please verify and let me know, So that I can close the issue ?

**Comment by gaurav-dalvi** [comment]
As we discussed, right now DNS container is disabled in ACI mode. Hence this wont work in ACI mode. It will work in non ACI mode.

Closing the issue !
