### ISSUE TITLE
Docker Swarm: Documentation needs to be fixed

### ISSUE THREAD

**Issue by yuva29** [contiv/netplugin#585]
http://contiv.github.io/documents/gettingStarted/networking/swarm.html 

Step 7 says it's attaching the container to `epg` but it's getting attached to the network.

**Comment by gaurav-dalvi** [comment]
@yuva29 : Good find.
could you please make changes here : https://github.com/contiv/contiv.github.io

**Comment by yuva29** [comment]
Working on it

**Comment by yuva29** [comment]
I suppose the document is already updated but those changes are not reflected in the website.

Original document is updated https://github.com/contiv/contiv.github.io/blob/master/websrc/source/documents/gettingStarted/networking/swarm.md 

I guess we have to figure how to sync the website with the repo.

**Comment by rhim** [comment]
@stacykor please address this as part of contiv.github.io overhaul.

**Comment by stacykor** [comment]
This has been updated along with other issueshttp://contiv.github.io/documents/gettingStarted/networking/swarm.html
