### ISSUE TITLE
Temporarily remove timing sensitive system test cases (eg. TestTriggerNetpluginDisconnect)

### ISSUE THREAD

**Issue by srampal** [contiv/netplugin#593]
Some of the current test cases such as TestTriggerNetpluginDisconnect in test/systemtests/test_trigger.go seem to be a bit flaky (potentially a timing issue ?) these fail arbitrarily sometimes on Jenkins sanity runs even though they are unrelated to the code changes actually being commited/ tested. This lengthens the overall development and code commit time significantly as these failuers typically occur at the end of 4 hour Jenkins sanity runs. Hence it may be better to remove this and similar sensitive test cases until they can be made more robust. Once these are removed, please open another issue to track re-introduction of the same test cases after improving their robustness.

**Comment by jojimt** [comment]
Let's not remove tests. Instead, let's investigate the failure. If we remove tests, we won't know what bugs get in.

**Comment by gaurav-dalvi** [comment]
related PR : https://github.com/contiv/netplugin/pull/601
