### ISSUE TITLE
got error when try to build, no buildable Go source files in /XXX/netlink/nl

### ISSUE THREAD

**Issue by jsoyee** [contiv/netplugin#60]
XXX-M-Q0DJ:netplugin XXX$ make build
./scripts/checks
got below error when try to build it
i am new for go, please see if there are any inconsistency for code checkin. 

Checking Go version...
Checking gofmt...
All checks passed!!
go get -d ./ ./netdcli/ ./mgmtfn/k8contivnet/
go install -v ./ ./netdcli/ ./mgmtfn/k8contivnet/
../go/src/github.com/vishvananda/netlink/netlink.go:14:2: no buildable Go source files in /Users/XXX/Desktop/Private/go/src/github.com/vishvananda/netlink/nl
make: *** [build] Error 1

Environment:
    OSX 10.8
    go 1.4.2 (with go-installer for mac)
    GOPATH be well configured

**Comment by mapuri** [comment]
@jsoyee 
Looks like this error is specific to the mac environment, as the build seems to be going through fine in our ubuntu based environment for sanities.

I don't have a mac to try it out but the error seems to indicate that no go source was found at '/Users/XXX/Desktop/Private/go/src/github.com/vishvananda/netlink/nl'. This directory should have been created as part of downloading go dependencies. Can you please verify if it has the .go files downloaded? Also does the build fail always or does subsequent build goes through?

I will see if I can find a mac to repro the error locally.

**Comment by jsoyee** [comment]
@mapuri 
thanks for your feedback. yes, i guess all .go files has been downloaded, 
YIZH2-M-Q0DJ:nl yizh2$ pwd
/Users/yizh2/Desktop/Private/go/src/github.com/vishvananda/netlink/nl
XXX-M-Q0DJ:nl XXX$ ls
addr_linux.go			xfrm_linux.go
addr_linux_test.go		xfrm_linux_test.go
link_linux.go			xfrm_policy_linux.go
nl_linux.go			xfrm_policy_linux_test.go
nl_linux_test.go		xfrm_state_linux.go
route_linux.go			xfrm_state_linux_test.go
route_linux_test.go
XXX-M-Q0DJ:nl XXX$

Here is my go environment:
XXX-M-Q0DJ:netplugin XXX$ go env
GOARCH="386"
GOBIN=""
GOCHAR="8"
GOEXE=""
GOHOSTARCH="386"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/XXX/Desktop/Private/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_386"
CC="clang"
GOGCCFLAGS="-fPIC -m32 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
XXX-M-Q0DJ:netplugin XXX$

i use go installer on my mac, so the environment should all come from what it go on my system. 
I guess it should be some cross platform compiling issues, not sure CGO_ENABLED='1' triggered this. 
thanks, i will use ubuntu to try it out.

**Comment by shaleman** [comment]
We now support building netplugin on Mac by building binaries inside the VM.
Some of us are actively using this mode.
Please reopen if you still see this issue.
