### ISSUE TITLE
tests periodically die due to netplugin crash

### ISSUE THREAD

**Issue by erikh** [contiv/netplugin#621]
Log below, please investigate.

http://contiv.ngrok.io/job/Netplugin_CI/4636/consoleFull

**Comment by abhinandanpb** [comment]
@erikh has this test failed on any other PRs ? We havent seen this failure at all.

**Comment by erikh** [comment]
this fails on the subnet branch which contains no other code changes to anything but the vagrant file.

**Comment by erikh** [comment]
I think it's crashing due to a concurrent map issue in contivmodel, but we'll see.

**Comment by rhim** [comment]
Closing that the build referred to in here got trashed. Need to be opened again if issue shows up again.
