### ISSUE TITLE
Basic tests are failing on AWS EC2 instances with Contiv + Docker swarm

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#630]
Netplugin Log : 
https://gist.github.com/gaurav-dalvi/3337d0cdb22835ac4797d7c133c45283

Test Log: 

https://gist.github.com/gaurav-dalvi/15191f29e9f6a3189dcb565ce2872c90

**Comment by jojimt** [comment]
Based on: ```INFO[0181] docker: Error response from daemon: No healthy node available in the cluster.```, looks like something wrong with the setup itself.

**Comment by gaurav-dalvi** [comment]
will reopen when i see the issue.
