### ISSUE TITLE
Allow a tenant to communicate with another one

### ISSUE THREAD

**Issue by serkansahin** [contiv/netplugin#631]
All is in the title, is it possible to allow an existing tenant (or by creating a new one) to communicate with an other one ?

Example:
tenant 1 = "default" with one vxlan (default-net)
tenant 2 = "devtest" with two vxlans (devtest-net, devtest-web)

I want to be able as a k8s pod from default-net network to reach another k8s pod in other tenants' networks (devtest-net and/or devtest-web)

Thank you !

**Comment by abhinandanpb** [comment]
@serkansahin : wouldnt that break the whole notion of tenancy ? Can you explain your use-case ?

**Comment by serkansahin** [comment]
Hi @abhinandanpb !

I actually work to deploy a k8s cluster with contiv instead of using calico/weave or flannel (I've forked Kubespray's Kargo and modified it). Actually, It's perfectly working, I have contiv as the network plugin for Kubernetes, I can deploy new pods on my virtual networks according to their tenants.

But the problem is that my kube-system's pods (kubedns, dnsmasq, kubeproxy) are deployed in the default tenant, and I need them to reach every pods of every other tenants in my cluster!

So if you can advise me to do that, it would very helpful for I :)

**Comment by paulsinai** [comment]
Hi @abhinandanpb,

I think @serkansahin would isolate tenants inside one kubernetes cluster using contiv tenant but he needs to reach dns-mask which is in the default tenant (as it is in the kube-system namespace) while he keeps the isolation of each tenant. It would be able to use services inside a tenant without having to redeploy all Kube-system pods.

Thanks for your help :-)

**Comment by jojimt** [comment]
First off, multi-tenancy under k8s is still under discussion in k8s community itself. But, in practice, you could solve the issue you're referring to, by creating infra pods within each tenant. Looks like you're trying to optimize this by sharing the services. We do not yet support cross-tenant traffic internally within Contiv. However, provided you're not using overlay, you could use the external network to route between the two tenants, in effect, achieving what you're looking for.

**Comment by serkansahin** [comment]
Hi @jojimt 

Could you explain to me the --nw-type (-n) flag, please ? what's the differences between infra or data networks ?

Thank you !
