### ISSUE TITLE
Error connecting to OVS. Err: dial unix /var/run/openvswitch/db.sock

### ISSUE THREAD

**Issue by yunhostnet** [contiv/netplugin#632]
INFO[Nov 21 11:57:10.271239622] Received request to create new ovs switch bridge:contivVxlanBridge, localIP:10.2.22.85, fwdMode:bridge 
FATA[Nov 21 11:57:10.271378532] Error connecting to OVS. Err: dial unix /var/run/openvswitch/db.sock: connect: no such file or directory

**Comment by gaurav-dalvi** [comment]
Hello @yunhostnet could you please give more information on this.
Which OVS version ?
OS ?
Docker swarm or K8s or some other ? 
Which netplugin version you are trying here ?

**Comment by unclejack** [comment]
OVS was probably not running. Please make sure that OVS is installed and running. Unfortunately, there's nothing more for us to do to help with this issue.
