### ISSUE TITLE
Question related to Contiv network isolation

### ISSUE THREAD

**Issue by sdake** [contiv/netplugin#633]
Hey folks,

I know not a whole lot about contiv or what it provides.  One thing that would be helpful for me is isolation of networks within Kubernetes for security reasons.  Essentially I want Kubernetes to mimic bare metal networking in some way and provide eth1/eth2/eth3 (or whatever they may be called) within each of the containers without using net=host mode.  Using net=host mode is workable, but not ideal and it sure would be nice to isolate some types of traffic from others.

**Comment by gaurav-dalvi** [comment]
@sdake : http://contiv.github.io/
This has all the information about contiv networking. You may want to see various modes in which contiv networking runs. (L2, L3 / BGP , overlay etc)

**Comment by danehans** [comment]
@sdake k8s needs to support multiple interfaces/ip's per pod. Please see https://github.com/kubernetes/kubernetes/issues/27398

**Comment by sdake** [comment]
I see in the docs here:
http://contiv.github.io/documents/networking/features.html

L2 is listed as a feature.  What is missing from this list is "are separate interfaces created" or do we just get one to work with (kubernetes context)?  I suppose VLAN over one interface would work.  What I'm looking for is there a way to create multiple network interfaces in the container with netplugin?

TIA!
-steve

**Comment by jojimt** [comment]
@sdake Can you please provide some details of your use case? As far as kubernetes goes, support for multiple interfaces is under discussion. However, based on your exact use case, we may be able to do something.

**Comment by sdake** [comment]
@jojimt My use case: https://review.openstack.org/#/c/392257/

In essence we are sharing all traffic over one interface now which lacks security.

**Comment by jojimt** [comment]
I could not find a reference to multiple interfaces in the url you provided. It's possible it is hidden somewhere and in that case, it will take me some time to get through it. Could you please elaborate what you mean by "In essence we are sharing all traffic over one interface now which lacks security"? Are you referring to separation of tenant traffic from some kind of control traffic that originates/terminates in the pod?

**Comment by danehans** [comment]
@sdake is involved in the [kolla-k8s](https://github.com/openstack/kolla-kubernetes) project, which is an offshoot of the [kolla](https://wiki.openstack.org/wiki/Kolla) project. Both projects are for deploying OpenStack services (i.e. Nova Scheduler, Neutron API, etc..) in containers. Typical OpenStack deployments contain several different networks for security and traffic isolation purposes. For example, user/admin facing Nova API endpoints belong to different networks, tenant overlay networks belong to a different network than API networks, etc.. It's preferable for several OpenStack services to include multiple interfaces. @jojimt Can you elaborate on:

> However, based on your exact use case, we may be able to do something.

**Comment by danehans** [comment]
@sdake Looks like CNI does not support multiple interfaces per pod either: https://github.com/containernetworking/cni/issues/114

**Comment by jojimt** [comment]
To elaborate, multiple interfaces bring with it a messy routing problem. With some restrictions, e.g.  the additional interface will be used to forward traffic only to directly connected networks, it is possible limit the complexity and do something in the interim. All of that depends on the use case being addressed.

**Comment by danehans** [comment]
@sdake what are your thoughts? IMO supporting add'l interfaces for local networking is a step in the right direction.

**Comment by sdake** [comment]
@danehans the two answers I see that commonly work are vlan on one interface and multiple interfaces directly.  We are using host networking for the dataplane at present and native kubernetes networking for the control plane.  We have the following interface types:

#api_interface: "{{ network_interface }}"
#storage_interface: "{{ network_interface }}"
#cluster_interface: "{{ network_interface }}"
#tunnel_interface: "{{ network_interface }}"

We just need network isolation on the api_interface.
We ideally want QOS on the storage interface and isolation (this is used for ceph traffic which should be second highest priority)
We ideally want QOS and isolation on the cluster interface (this is used for rabbitmq traffic which should be highest priority).

At present we are running all of these over one interface which could lead to a tcpdump security breach.

I'm not sure the best way to solve this problem in Kubernetes environments (I am not a super networking guru).  On bare metal we solve it with separate interfaces.

**Comment by sdake** [comment]
@jojimt apologies for not getting back to you in a timely manner.

**Comment by hwinkel** [comment]
I'm coming from reading contiv docs and capabilities. We have the requirement to deploy network functions as pods. I.e. the termination of Tunnel Protocols and forwarding traffic to a next hop as acting as a routing function. That means the we need at least to interfaces here.

**Comment by rkamudhan** [comment]
We developed a CNI called *[Multus](https://github.com/Intel-Corp/multus-cni)* to support Multi-homed pod in Kubernetes, which support multi interface in a pod and support different network in a single pod. Hope this could be a best use case for the guys in this forum.

**Comment by hwinkel** [comment]
is there any progress for the multi interface use casse?

**Comment by sdake** [comment]
interest in this use case has ceased, although others may have interest in it.
