### ISSUE TITLE
How to build contiv netplugin

### ISSUE THREAD

**Issue by jiangsuwwj1** [contiv/netplugin#637]
I want to install netplugin for docker, but can not found the binary install package. Also I can not found any document about how to build netplugin and integrating method.  

please help. thanks.

**Comment by erikh** [comment]
Builds are here: https://github.com/contiv/netplugin/releases

If you wish, you can check out the repository and `make build`, which will put the artifacts in the `bin/` directory, however it requires a lot of extra tooling to use.

https://github.com/contiv/netplugin#building-and-testing has more information on the tools required.

**Comment by jiangsuwwj1** [comment]
Thank you.

**Comment by gaurav-dalvi** [comment]
closing this !
