### ISSUE TITLE
Question about kubernetes + contiv netplugin + docker integrating

### ISSUE THREAD

**Issue by jiangsuwwj1** [contiv/netplugin#638]
1.  How to integrate Kubernetes + contiv netplugin +docker, is there any guide? 

2. Kubernetes support CNI, but docker support CNM. Contiv support both CNI and CNM, in this situation which interface should i choose. CNI or CNM?

3. I was confused about how Kubbernetes's CNI works, such as how to create a network, how to add a pod into network, how to remove a pod from network.

**Comment by gaurav-dalvi** [comment]
hello @jiangsuwwj1 here are the few links for you : 

- Container networking tutorial , CNM and CNI : https://github.com/jainvipin/tutorial
- http://contiv.github.io/ -- most of the information about contiv is there.
- How to bring up K8s with Contiv : https://github.com/contiv/demo/tree/master/k8s

Please let us know if you have any questions.
