### ISSUE TITLE
make k8s-cluster  failed 

### ISSUE THREAD

**Issue by jiangsuwwj1** [contiv/netplugin#651]
Command "make k8s-cluster" failed, error is as follow.

==> k8master: VirtualBox VM is already running.
==> k8node-01: VirtualBox VM is already running.
==> k8node-02: VirtualBox VM is already running.
==> k8node-03: VirtualBox VM is already running.
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default).
This feature will be 
removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [all] *********************************************************************

TASK [pre-ansible : Get os_version from /etc/os-release] ***********************
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
The authenticity of host '[127.0.0.1]:2200 ([127.0.0.1]:2200)' can't be established.
ECDSA key fingerprint is SHA256:J0bIDPDdfqeTDewgdTvRhPM8DIfYfdrp3j47fl+x2wc.
Are you sure you want to continue connecting (yes/no)? The authenticity of host '[127.0.0.1]:2222 ([127.0.0.1]:2222)' can't be established.
ECDSA key fingerprint is SHA256:oFV3a1YRN6/bmocYhvILEDwawrP64cUvNGehSLL8huM.
Are you sure you want to continue connecting (yes/no)? The authenticity of host '[127.0.0.1]:2202 ([127.0.0.1]:2202)' can't be established.
ECDSA key fingerprint is SHA256:AACSLfPnNUVoZsFBSJwMEmj7tV6JeDBFEmKPsff0MGg.
Are you sure you want to continue connecting (yes/no)? The authenticity of host '[127.0.0.1]:2201 ([127.0.0.1]:2201)' can't be established.
ECDSA key fingerprint is SHA256:A51YRBG8GJEGt7VV5pARu763ZQHEUIyftsjw7FCdEGU.
Are you sure you want to continue connecting (yes/no)? fatal: [k8node-02]: FAILED! => {"failed": true, "msg": "Timeout (12s) waiting for privilege escalation prompt: "}
fatal: [k8node-01]: FAILED! => {"failed": true, "msg": "Timeout (12s) waiting for privilege escalation prompt: "}
fatal: [k8node-03]: FAILED! => {"failed": true, "msg": "Timeout (12s) waiting for privilege escalation prompt: "}
fatal: [k8master]: FAILED! => {"failed": true, "msg": "Timeout (12s) waiting for privilege escalation prompt: "}
	to retry, use: --limit @/Users/wangwenjian/go/src/github.com/k8s/netplugin/vagrant/k8s/contrib/ansible/cluster.retry

PLAY RECAP *********************************************************************
k8master                   : ok=0    changed=0    unreachable=0    failed=1   
k8node-01                  : ok=0    changed=0    unreachable=0    failed=1   
k8node-02                  : ok=0    changed=0    unreachable=0    failed=1   
k8node-03                  : ok=0    changed=0    unreachable=0    failed=1

**Comment by gaurav-dalvi** [comment]
Please provide more details.
OS, netplugin version.

Also we are going to role out new k8s installer (1.4+) so please stay tunned. It will lot easier after that.

I will provide pointers here once its done.

**Comment by jojimt** [comment]
@jiangsuwwj1: I think you just need to respond to this prompt *Are you sure you want to continue connecting (yes/no)?*

**Comment by jiangsuwwj1** [comment]
@jojimt The problem was solved after respond to this prompt. 
thanks
