### ISSUE TITLE
restrict vagrant up to only if vagrant version is 1.8.6+

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#654]
for all vagant files here : https://github.com/contiv/netplugin/tree/master/vagrant

**Comment by gaurav-dalvi** [comment]
@dseevr : if you know the code fix could you please work on this one ?

**Comment by gaurav-dalvi** [comment]
@dseevr : Please close this if this has been merged !

**Comment by dseevr** [comment]
@gaurav-dalvi  It hasn't been merged yet, but this issue will be auto-closed when it does get merged
