### ISSUE TITLE
netplugin netmaster does not work with redhat 7.x

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#656]
Netplugin Logs:
https://gist.github.com/gaurav-dalvi/456afabbc1e8eb7f0387319dc3f5d324

Netmaster Logs : 
https://gist.github.com/gaurav-dalvi/5c3db03531e8d47abb4ce9a24d9e5903

etcd Logs : 
https://gist.github.com/gaurav-dalvi/b3744c1da9da36ae617d5ab1216870cc

**Comment by jojimt** [comment]
Clearly an issue with etcd setup. Please close this an open an issue against ansible repo.
