### ISSUE TITLE
netplugin on kube-nodes failed to start.

### ISSUE THREAD

**Issue by peiqi-caicloud** [contiv/netplugin#658]
I installed the kubernetes with netplugin demo according to http://contiv.github.io/documents/gettingStarted/networking/install-k8s.html.
1 master and 2 node.

I found netplugin failed to start with logs of journalctl -u netplugin:

[root@k8node-01 ~]# systemctl status -l netplugin
● netplugin.service - Netplugin
   Loaded: loaded (/etc/systemd/system/netplugin.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since 二 2016-12-13 10:07:19 UTC; 42min ago
  Process: 31899 ExecStart=/usr/bin/netplugin $NETPLUGIN_ARGS (code=exited, status=1/FAILURE)
 Main PID: 31899 (code=exited, status=1/FAILURE)

12月 13 10:07:17 k8node-01 netplugin[31899]: 2016/12/13 10:07:17 Extension point components: {map[consul:0x196a9c0 etcd:0x196a9c0]}
12月 13 10:07:17 k8node-01 netplugin[31899]: time="Dec 13 10:07:17.509893278" level=info msg="Using%!(EXTRA string=etcd, string=service adapter:, *url.URL=etcd://127.0.0.1:2379)"
12月 13 10:07:17 k8node-01 netplugin[31899]: time="Dec 13 10:07:17.509990126" level=info msg="Connecting to backend (0/0)"
12月 13 10:07:17 k8node-01 netplugin[31899]: time="Dec 13 10:07:17.514226007" level=error msg="Service plugin not connecting to backend client: etcd cluster is unavailable or misconfigured"
12月 13 10:07:19 k8node-01 netplugin[31899]: time="Dec 13 10:07:19.516178288" level=error msg="Failed to connect to etcd. Err: client: etcd cluster is unavailable or misconfigured"
12月 13 10:07:19 k8node-01 netplugin[31899]: time="Dec 13 10:07:19.516250759" level=error msg="Error creating client etcd to url 127.0.0.1:2379. Err: client: etcd cluster is unavailable or misconfigured"
12月 13 10:07:19 k8node-01 netplugin[31899]: time="Dec 13 10:07:19.516295775" level=fatal msg="Error initializing cluster. Err: client: etcd cluster is unavailable or misconfigured"
12月 13 10:07:19 k8node-01 systemd[1]: netplugin.service: main process exited, code=exited, status=1/FAILURE
12月 13 10:07:19 k8node-01 systemd[1]: Unit netplugin.service entered failed state.
12月 13 10:07:19 k8node-01 systemd[1]: netplugin.service failed.

However I checked etcd service on 3 nodes running proprely. and net master also works properly on master node.

I have not found any strange trace.  Does anyone confronted similar situations ???

**Comment by jojimt** [comment]
Try running the clean_restart.sh script, followed by verify_cluster.sh.

**Comment by peiqi-caicloud** [comment]
@jojimt  hello, I restart the service and found a new problem when creating pods:

  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  55s		55s		1	{default-scheduler }			Normal		Scheduled	Successfully assigned redis-srv-2k3iv to k8node-01
  51s		30s		4	{kubelet k8node-01}			Warning		FailedSync	Error syncing pod, skipping: failed to "SetupNetwork" for "redis-srv-2k3iv_default" with SetupNetworkError: "Failed to setup network for pod \"redis-srv-2k3iv_default(1287c44a-c1a6-11e6-996f-5254009fbdfd)\" using network plugins \"cni\": Contiv:Error creating EP; Err: Post http://192.168.16.84:9999/plugin/createEndpoint: dial tcp 192.168.16.84:9999: getsockopt: no route to host; Skipping pod"

my cluster config:

r: Post http://192.168.16.84:9999/plugin/createEndpoint: dial tcp 192.168.16.84:9999: getsockopt: no route to host\{"master": [{"name": "k8master", "management_ip": "192.168.16.83", "contiv_control_if": "eth2", "contiv_control_ip": "192.168.16.84", "contiv_network_if": "eth3", "contiv_network_ip": "192.168.16.85"}],
 "nodes" : [{"name": "k8node-01", "management_ip": "192.168.16.116", "contiv_control_if": "eth2", "contiv_control_ip": "192.168.16.117", "contiv_network_if": "eth3", "contiv_network_ip": "192.168.16.118", "max_pods": "40"},
            {"name": "k8node-02", "management_ip": "192.168.16.148", "contiv_control_if": "eth2", "contiv_control_ip": "192.168.16.149", "contiv_network_if": "eth3", "contiv_network_ip": "192.168.16.150", "max_pods": "40"}]
}

more detailed logs are :

[root@k8node-02 ~]# systemctl status -l netplugin
● netplugin.service - Netplugin
   Loaded: loaded (/etc/systemd/system/netplugin.service; static; vendor preset: disabled)
   Active: active (running) since 三 2016-12-14 02:17:07 UTC; 37min ago
 Main PID: 21417 (netplugin)
   Memory: 3.0M
   CGroup: /system.slice/netplugin.service
           └─21417 /usr/bin/netplugin -vlan-if eth3 -vtep-ip 192.168.16.149 -ctrl-ip 192.168.16.149 -plugin-mode kubernetes

12月 14 02:54:49 k8node-02 netplugin[21417]: time="Dec 14 02:54:49.212549200" level=info msg="Handling \"add pod\" event"
12月 14 02:54:49 k8node-02 netplugin[21417]: time="Dec 14 02:54:49.268787108" level=info msg="labels is bevco/bevco-net1/sugardb for pod redis-srv-rxtfr\n"
12月 14 02:54:49 k8node-02 netplugin[21417]: time="Dec 14 02:54:49.276431749" level=info msg="Making REST request to url: http://192.168.16.84:9999/plugin/createEndpoint"
12月 14 02:54:49 k8node-02 netplugin[21417]: time="Dec 14 02:54:49.290180000" level=error msg="Error during http POST. Err: Post http://192.168.16.84:9999/plugin/createEndpoint: dial tcp 192.168.16.84:9999: getsockopt: no route to host"
12月 14 02:54:49 k8node-02 netplugin[21417]: time="Dec 14 02:54:49.290245461" level=error msg="Error making POST request: Err: Post http://192.168.16.84:9999/plugin/createEndpoint: dial tcp 192.168.16.84:9999: getsockopt: no route to host"
12月 14 02:54:49 k8node-02 netplugin[21417]: time="Dec 14 02:54:49.298203571" level=info msg="Making REST request to url: http://192.168.16.84:9999/plugin/deleteEndpoint"
12月 14 02:54:49 k8node-02 netplugin[21417]: time="Dec 14 02:54:49.299826761" level=error msg="Error during http POST. Err: Post http://192.168.16.84:9999/plugin/deleteEndpoint: dial tcp 192.168.16.84:9999: getsockopt: no route to host"
12月 14 02:54:49 k8node-02 netplugin[21417]: time="Dec 14 02:54:49.299973749" level=error msg="Error making POST request: Err: Post http://192.168.16.84:9999/plugin/deleteEndpoint: dial tcp 192.168.16.84:9999: getsockopt: no route to host"
12月 14 02:54:49 k8node-02 netplugin[21417]: time="Dec 14 02:54:49.300017474" level=error msg="Error creating ep. Err: Post http://192.168.16.84:9999/plugin/createEndpoint: dial tcp 192.168.16.84:9999: getsockopt: no route to host"
12月 14 02:54:49 k8node-02 netplugin[21417]: time="Dec 14 02:54:49.300057198" level=error msg="Handler for POST /ContivCNI.AddPod returned error: Post http://192.168.16.84:9999/plugin/createEndpoint: dial tcp 192.168.16.84:9999: getsockopt: no route to host"

do you have any idea of this error. I run verify_cluster.sh  This error is ignored.

**Comment by peiqi-caicloud** [comment]
@jojimt  I think the problem is about firewalld.

**Comment by jojimt** [comment]
yes, that is correct. You need to open the port on the firewall or disable firewall.

**Comment by peiqi-caicloud** [comment]
@jojimt  hello, I have a new problem:  " 100: Key not found ",  the default pods in kube-system are setup correctly. However, when I create other pods, contiv cannot setup the network config due to the following logs:

it seems the same issue of https://github.com/contiv/netplugin/issues/291.

Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  29s		29s		1	{default-scheduler }			Normal		Scheduled	Successfully assigned bbox-client-ej3q1 to k8node-02
  27s		27s		1	{kubelet k8node-02}			Warning		FailedSync	Error syncing pod, skipping: failed to "SetupNetwork" for "bbox-client-ej3q1_kube-system" with SetupNetworkError: "Failed to setup network for pod \"bbox-client-ej3q1_kube-system(c3350c1c-c1be-11e6-81d1-5254009fbdfd)\" using network plugins \"cni\": Contiv:Error creating EP; Err: 100: Key not found (/contiv.io/state/nets/bevco-net1.bevco) [12328]\n; Skipping pod"

  24s	24s	1	{kubelet k8node-02}		Warning	FailedSync	Error syncing pod, skipping: failed to "SetupNetwork" for "bbox-client-ej3q1_kube-system" with SetupNetworkError: "Failed to setup network for pod \"bbox-client-ej3q1_kube-system(c3350c1c-c1be-11e6-81d1-5254009fbdfd)\" using network plugins \"cni\": Contiv:Error creating EP; Err: 100: Key not found (/contiv.io/state/nets/bevco-net1.bevco) [12338]\n; Skipping pod"

  20s	20s	1	{kubelet k8node-02}		Warning	FailedSync	Error syncing pod, skipping: failed to "SetupNetwork" for "bbox-client-ej3q1_kube-system" with SetupNetworkError: "Failed to setup network for pod \"bbox-client-ej3q1_kube-system(c3350c1c-c1be-11e6-81d1-5254009fbdfd)\" using network plugins \"cni\": Contiv:Error creating EP; Err: 100: Key not found (/contiv.io/state/nets/bevco-net1.bevco) [12352]\n; Skipping pod"

**Comment by jojimt** [comment]
I think you may not have create the tenant and network you're specifying in the podspec.

**Comment by peiqi-caicloud** [comment]
@jojimt Thank you for your notice solved this problem.

However I found pods on different nodes are not reachable. I saw you direct arp packets to controller:65535.

I did n't see sdn controller installation in the script. should I install a sdn controller by myself for connecting pods on different nodes, like Ryu ？

By the way, do you know the openvswitch parse error below？ it's a bug or version compatibility pb...

Thank you.


[root@k8node-02 ~]# ovs-ofctl dump-flows contivVlanBridge
2016-12-15T06:53:39Z|00001|ofp_actions|WARN|invalid instruction ordering: apply_actions must appear before write_metadata, for OpenFlow 1.1+ compatibility
2016-12-15T06:53:39Z|00002|ofp_util|WARN|OFPST_FLOW reply bad instructions
NXST_FLOW reply (xid=0x4):
 cookie=0x16, duration=3320.405s, table=0, n_packets=17, n_bytes=1108, idle_age=461, priority=100,arp,arp_op=1 actions=CONTROLLER:65535
 cookie=0x14, duration=3320.405s, table=0, n_packets=5138, n_bytes=409540, idle_age=0, priority=1 actions=resubmit(,1)
 cookie=0x18, duration=3318.609s, table=1, n_packets=5111, n_bytes=407357, idle_age=0, priority=100,in_port=1 actions=resubmit(,5) ***parse error***

**Comment by peiqi-caicloud** [comment]
@jojimt  Or, I am wondering should we add the default (Normal probably) flows for each bridge by default.

And I have a question:   does the notion "tenant" in netplugin corresponds to namespace in k8s?  because In k8s， some namespaces should be connected while other namespaces may need to be isolated depending detail use cases.

In my expectation, I hope we can map different networks in netplugin for namespaces in k8s according to our needs. 

and For k8s use cases, usually we need a namespace, where all pods can be bidirectly reachable from all other namespaces. could we define  some special flows (like vlan, (vxlan )transition) to make a common network for this namespace in k8s. Instead of traversing of an external  router...

**Comment by peiqi-caicloud** [comment]
@jojimt Would you please have a look for my question?

**Comment by jojimt** [comment]
Contiv tenant is not tied to k8s namespace. It is completely flexible in that you have the option of placing all the pods in your cluster in the same tenant, same network or net-group. This assignment is performed using **io.contiv.tenant, io.contiv.network** and **io.contiv.net-group** labels. See https://github.com/contiv/netplugin/tree/master/mgmtfn/k8splugin for some examples. By default, everything is reachable. You can manage which pods are reachable by applying policy.

**Comment by peiqi-caicloud** [comment]
Thank you for your response. 
@jojimt @erikh @philips 
I would like to know how contiv populate the fdb on each host. You use the etcd watch mechanism for synchronizing each host's fdb or use the ofnet agent package, which, to me, looks a little like the l2 pop mechanism in Neutron... 

I read a little code, It seems to me you use the second method. The advantages and disadvantages for the first method. we store pods' network info in etcd cluster, and the fdb on each host has an agent for synchronizing ？

**Comment by peiqi-caicloud** [comment]
and what is the purpose of BGP part in drivers/ovsdb.go  ovsSwitch.go file ?  personally, I found the code a little disordering...

**Comment by jojimt** [comment]
Closing based on: _@jojimt Thank you for your notice solved this problem._
