### ISSUE TITLE
Create document to run contiv inside container

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#663]
Things to be needed : 
- Which versions it is supported  (docker swarm + docker ) and (k8s + docker )
- script to build container image out of source code
- command to run netplugin as a container (using docker hub contiv image)
- command to run netmaster as a container (using docker hub contiv image)

we can create document something like this 

https://github.com/gaurav-dalvi/demo/blob/contiv-start-doc/HowtoStartContiv.md

**Comment by rhim** [comment]
Currently out of scope. For k8s 1.4 which uses container based setup, it installer should take care of it.

**Comment by gaurav-dalvi** [comment]
Closing it.
