### ISSUE TITLE
docker swarm + contiv + ACI -> Need information

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#673]
Previously we did not use this command.

`netctl aci-gw set -n "topology/pod-1/node-101,topology/pod-1/node-102" -d "TEST-Phys-Dom" -e yes -i no`

Now if we dont execute this command and then run through our flow, Policies are not getting applied as a contracts in ACI. If we execute this command its works fine.

Contiv version : v0.1-11-30-2016.20-08-20.UTC
ACI-gw version : 11-28-2016.2.0_2g

**Comment by jojimt** [comment]
The aci-gw object is the way to set those parameters going forward. However, for backwards compatibility, we will support the old method as well. Looks like the backwards compatibility part if not working as expected. Please open this issue against aci-gw and I will take care of it.

**Comment by gaurav-dalvi** [comment]
Steps to reproduce : 
1: run net_demo (-a oprtion) on one node setup. (number of nodes does not matter)
2: aci-gw version used : `contiv/aci-gw:11-28-2016.2.0_2g`
3: Execute these commands : 

```
netctl global set --fabric-mode aci --vlan-range 1100-1200
netctl tenant create t1
netctl network create --tenant t1 --subnet=20.1.1.0/24 --gateway=20.1.1.254 -e "vlan" n1
netctl policy create -t t1 app2db
netctl group create -t t1 -p app2db n1 g1
netctl group create -t t1 n1 g2
netctl policy rule-add -t t1 -d in --protocol tcp --port 6379 --from-group g2 --action allow app2db 1
netctl app-profile create --tenant t1 -g g1,g2 profile1
```
No proper contract is pushed to ACI. It shows default

Now repeat step 1 to 3 and then execute these commands

```
netctl aci-gw set -n "topology/pod-1/node-101,topology/pod-1/node-102" -d "TEST-Phys-Dom" -e yes -i no

netctl global set --fabric-mode aci --vlan-range 1100-1200
netctl tenant create t1
netctl network create --tenant t1 --subnet=20.1.1.0/24 --gateway=20.1.1.254 -e "vlan" n1
netctl policy create -t t1 app2db
netctl group create -t t1 -p app2db n1 g1
netctl group create -t t1 n1 g2
netctl policy rule-add -t t1 -d in --protocol tcp --port 6379 --from-group g2 --action allow app2db 1
netctl app-profile create --tenant t1 -g g1,g2 profile1
```
You see proper contract is getting pushed to APIC.

**Comment by jojimt** [comment]
Please try with contiv/aci-gw:01-17-2017.2.0_2g

**Comment by jojimt** [comment]
This should be opened against aci-gw, not netplugin.
