### ISSUE TITLE
docker network ls  ,then can not find net?

### ISSUE THREAD

**Issue by fiser321** [contiv/netplugin#674]
after install netplugin  then docker network ls  I  am not find the work?

![image](https://cloud.githubusercontent.com/assets/8924920/21641185/365f23ae-d2b5-11e6-96b1-a25bb68ee8f3.png)

![image](https://cloud.githubusercontent.com/assets/8924920/21641202/50f0ad32-d2b5-11e6-9ed6-502568573e95.png)
but run docker network ls, exists some question
![image](https://cloud.githubusercontent.com/assets/8924920/21641247/8b2f7186-d2b5-11e6-91bf-a6628b10c6f4.png)

**Comment by gaurav-dalvi** [comment]
could you please provide more details ?
`netctl --version`
which orchestration you are using ? (swarm / k8s etc)

**Comment by fiser321** [comment]
@gaurav-dalvi
 
wo have no use  (swarm / k8s etc), my machine only  install docker engine and ovs
env:
I have one machine named centos7.2, I have go env, then git clone https://github.com/contiv/netplugin.git, 

![image](https://cloud.githubusercontent.com/assets/8924920/21666386/5359d02c-d32c-11e6-88af-5fc882a37063.png)

cd   ./netplugin/ ./netmaster/ ./netctl/netctl/ ./mgmtfn/k8splugin/contivk8s/ 
./mgmtfn/mesosplugin/netcontiv/
at these dir ,run go install ,
in GOPATH/bin can bring some binary
$ cp scripts/contrib/completion/bash/netctl /etc/bash_completion.d/netctl
then
$ nohup ./netplugin &
$ nohup ./netmaster &

$ netctl net create contiv-net --subnet=30.1.1.0/24
$ docker network ls
![image](https://cloud.githubusercontent.com/assets/8924920/21666351/24d8eb34-d32c-11e6-87fd-998df7157b0c.png)

if can not find network,
![image](https://cloud.githubusercontent.com/assets/8924920/21666442/ae2562dc-d32c-11e6-8ec7-e684663fc2cd.png)

wo look up netplugin  log,  find some error :

**Comment by fiser321** [comment]
git checkout v0.1-12-23-2016.19-44-42.UTC
I first create network  always exist some error, the second time create network can success,
![image](https://cloud.githubusercontent.com/assets/8924920/21667460/3c36c3fc-d334-11e6-87d1-0a06793c1795.png)

**Comment by fiser321** [comment]
I know reason ，docker.service   add  --cluster-store=etcd://127.0.0.1:2379/ 
thank you!

**Comment by gaurav-dalvi** [comment]
@fiser321 : I am glad you were able to execute this.
