### ISSUE TITLE
dial unix /run/contiv/contiv-cni.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by peiqi-caicloud** [contiv/netplugin#677]
I run netplugin in a three nodes k8s cluster:

then I found logs in /var/log/contivk8s.log when creating pods:

time="2017-01-05T19:00:25+08:00" level=info msg="cniErr: {\"cniVersion\":\"0.1.0\",\"code\":1,\"msg\":\"Contiv:Post http://localhost/ContivCNI.AddPod: dial unix /run/contiv/contiv-cni.sock: connect: no such file or directory\"}" NETNS=18492
time="2017-01-05T19:00:27+08:00" level=info msg="==> Start New Log <==\n" NETNS=18614
time="2017-01-05T19:00:27+08:00" level=info msg="command: ADD, cni_args: IgnoreUnknown=1;K8S_POD_NAMESPACE=kube-system;K8S_POD_NAME=fluentd-elasticsearch-kube-master-1;K8S_POD_INFRA_CONTAINER_ID=f2080b215706fe795a039141ad441a0e5e74d4e7b5432070fccb731e73bfbc2d" NETNS=18614
time="2017-01-05T19:00:27+08:00" level=error msg="EP create failed for pod: kube-system/fluentd-elasticsearch-kube-master-1" NETNS=18614
time="2017-01-05T19:00:27+08:00" level=info msg="cniErr: {\"cniVersion\":\"0.1.0\",\"code\":1,\"msg\":\"Contiv:Post http://localhost/ContivCNI.AddPod: dial unix /run/contiv/contiv-cni.sock: connect: no such file or directory\"}" NETNS=18614
time="2017-01-05T19:00:29+08:00" level=info msg="==> Start New Log <==\n" NETNS=18746
time="2017-01-05T19:00:29+08:00" level=info msg="command: ADD, cni_args: IgnoreUnknown=1;K8S_POD_NAMESPACE=kube-system;K8S_POD_NAME=fluentd-elasticsearch-kube-master-1;K8S_POD_INFRA_CONTAINER_ID=3d65bfc2cec77078f43210aa39129205c409f3153900422e3780647ed8740451" NETNS=18746
time="2017-01-05T19:00:29+08:00" level=error msg="EP create failed for pod: kube-system/fluentd-elasticsearch-kube-master-1" NETNS=18746
time="2017-01-05T19:00:29+08:00" level=info msg="cniErr: {\"cniVersion\":\"0.1.0\",\"code\":1,\"msg\":\"Contiv:Post http://localhost/ContivCNI.AddPod: dial unix /run/contiv/contiv-cni.sock: connect: no such file or directory\"}" NETNS=18746
time="2017-01-05T19:00:32+08:00" level=info msg="==> Start New Log <==\n" NETNS=18873
time="2017-01-05T19:00:32+08:00" level=info msg="command: ADD, cni_args: IgnoreUnknown=1;K8S_POD_NAMESPACE=kube-system;K8S_POD_NAME=fluentd-elasticsearch-kube-master-1;K8S_POD_INFRA_CONTAINER_ID=ecad4dc2c3d79e11a0a41d6ae1e319492ac4728bc05976591c64b22c18b71157" NETNS=18873
time="2017-01-05T19:00:32+08:00" level=error msg="EP create failed for pod: kube-system/fluentd-elasticsearch-kube-master-1" NETNS=18873
time="2017-01-05T19:00:32+08:00" level=info msg="cniErr: {\"cniVersion\":\"0.1.0\",\"code\":1,\"msg\":\"Contiv:Post http://localhost/ContivCNI.AddPod: dial unix /run/contiv/contiv-cni.sock: connect: no such file or directory\"}" NETNS=18873
time="2017-01-05T19:00:34+08:00" level=info msg="==> Start New Log <==\n" NETNS=19017
time="2017-01-05T19:00:34+08:00" level=info msg="command: ADD, cni_args: IgnoreUnknown=1;K8S_POD_NAMESPACE=kube-system;K8S_POD_NAME=fluentd-elasticsearch-kube-master-1;K8S_POD_INFRA_CONTAINER_ID=5e1db128773b03603fb1179e51950a7ccb3d8403666a7623d12e5388798fb85c" NETNS=19017
time="2017-01-05T19:00:34+08:00" level=error msg="EP create failed for pod: kube-system/fluentd-elasticsearch-kube-master-1" NETNS=19017
time="2017-01-05T19:00:34+08:00" level=info msg="cniErr: {\"cniVersion\":\"0.1.0\",\"code\":1,\"msg\":\"Contiv:Post http://localhost/ContivCNI.AddPod: dial unix /run/contiv/contiv-cni.sock: connect: no such file or directory\"}" NETNS=19017

My netplugin service:
[Unit]
Description=Netplugin
After=auditd.service systemd-user-sessions.service time-sync.target etcd.service

[Service]
#EnvironmentFile=/etc/default/netplugin
ExecStart=/usr/bin/netplugin -cluster-store etcd://192.168.16.116:2379
#-plugin-mode kubernetes
KillMode=control-group

netmaster service:
[Unit]
Description=Netmaster
After=auditd.service systemd-user-sessions.service time-sync.target etcd.service

[Service]
#EnvironmentFile=/etc/default/netmaster
ExecStart=/usr/bin/netmaster --cluster-mode=kubernetes --dns-enable=false
KillMode=control-group

**Comment by peiqi-caicloud** [comment]
@jojimt  Hello, I saw you had a similar problem. do you have any idea about this one

**Comment by peiqi-caicloud** [comment]
close this issue please, this is caused by my bad configuration ...

**Comment by gaurav-dalvi** [comment]
Thanks @peiqi-caicloud .

**Comment by supereagle** [comment]
@peiqi-caicloud    Meet the same error, could you provide the correct configuration?

**Comment by neelimamukiri** [comment]
@supereagle, can you upload you /var/contiv/log/netplugin.log file?

**Comment by supereagle** [comment]
[netplugin.txt](https://github.com/contiv/netplugin/files/809797/netplugin.txt)

@neelimamukiri  This is the log file, please take a look, thanks.

**Comment by supereagle** [comment]
This error has been fixed. It is caused by that netplugin is not correctly started as the error config of `/opt/contiv/config/contiv.json`
