### ISSUE TITLE
kubernetes integration issue

### ISSUE THREAD

**Issue by peiqi-caicloud** [contiv/netplugin#684]
We are working on integrating kubernetes with netplugin.

We configured the file /opt/contiv/config/contiv.json as below:

{
  "K8S_API_SERVER": "https://192.168.16.116:6443",
  "K8S_CA": "/etc/kubernetes/certs/ca.crt",
  "K8S_KEY": "/etc/kubernetes/certs/kubecfg.key",
  "K8S_CERT": "/etc/kubernetes/certs/kubecfg.crt",
  "K8S_TOKEN": "qHmHFgPaLW0MGtHx8PTK93PmWnvrJqmn"
}   and validated of token in using:  curl command.

But the problem is that by using the netplugin, It seems We don't have enough right to retrieve the label in Podspec, (I think the netplugin has the right to retrieve the pod name level's infos but not the spec infos).

I got the error as below:

time="2017-01-08T20:06:30+08:00" level=info msg="==> Start New Log <==\n" NETNS=27991
time="2017-01-08T20:06:30+08:00" level=info msg="command: ADD, cni_args: IgnoreUnknown=1;K8S_POD_NAMESPACE=kube-system;K8S_POD_NAME=fluentd-elasticsearch-kube-master-1;K8S_POD_INFRA_CONTAINER_ID=dca0f60a160fd73564d54fb1d629324f4812802a6f27c613547cd8a720580f23" NETNS=27991
time="2017-01-08T20:06:30+08:00" level=error msg="EP create failed for pod: kube-system/fluentd-elasticsearch-kube-master-1" NETNS=27991
time="2017-01-08T20:06:30+08:00" level=info msg="cniErr: {\"cniVersion\":\"0.1.0\",\"code\":1,\"msg\":\"Contiv:Error getting labels\",\"details\":\"Err: Access denied!\"}" NETNS=27991

@ijumps @keontang @ddysher

**Comment by peiqi-caicloud** [comment]
@jojimt @gaurav-dalvi    Hello, I would like to know in which stage our project is?  is it productive ready for kubernetes ?   I have not tested the code for mgmtfn/k8s plugin myself.

thank you for your instructions

**Comment by peiqi-caicloud** [comment]
By the way, we found the netplugin failed easily:

trace:

[root@c4v148 config]# systemctl status netplugin -l
● netplugin.service - Netplugin
   Loaded: loaded (/etc/systemd/system/netplugin.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since 日 2017-01-08 18:10:08 CST; 2h 31min ago
  Process: 15638 ExecStart=/usr/bin/netplugin -cluster-store etcd://192.168.16.116:2379 -ctrl-ip 192.168.16.148 -vtep-ip 192.168.16.150 -plugin-mode kubernetes (code=exited, status=2)
 Main PID: 15638 (code=exited, status=2)

1月 08 18:10:07 c4v148 netplugin[15638]: goroutine 3946672 [chan receive]:
1月 08 18:10:07 c4v148 netplugin[15638]: github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util.(*MessageStream).parse(0xc827d06050)
1月 08 18:10:07 c4v148 netplugin[15638]: /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util/stream.go:147 +0x75
1月 08 18:10:07 c4v148 netplugin[15638]: created by github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util.NewMessageStream
1月 08 18:10:07 c4v148 netplugin[15638]: /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util/stream.go:68 +0x215
1月 08 18:10:07 c4v148 netplugin[15638]: goroutine 3946673 [chan receive]:
1月 08 18:10:07 c4v148 netplugin[15638]: github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util.(*MessageStream).parse(0xc827d06050)
1月 08 18:10:07 c4v148 netplugin[15638]: /opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util/stream.go:147 +0x75
1月 08 18:10:07 c4v148 netplugin[15638]: created by github.com/contiv/netplugin/vendor/github.com/shaleman/libOpenflow/util.NewMessageStream
1月 08 18:10:08 c4v148 systemd[1]: netplugin.service failed.
[root@c4v148 config]#

**Comment by gaurav-dalvi** [comment]
@peiqi-caicloud : Thanks for trying it out. Are you using K8s 1.3.x ? We have started supporting K8s1.4.+ which is much cleaner and easier experience.

You can try here : https://github.com/contiv/netplugin/tree/master/install/k8s
Please let us know if you face any issues.

**Comment by peiqi-caicloud** [comment]
@gaurav-dalvi :  Thanks for your reply, We use k8s 1.4+, but for some reason, we need to integrate it with contiv/netplugin in a non-containerized way.  I've tried the demo/k8s before this and it worked fine. Now I am trying to integrate it with our ansible script.

So far, To me, the problem is caused by http router: between cniserver.go  and kubeClient fetchPodLables func:   the http router server doesn't accept  the request from kubeClient and return a 403 code. I am not sure whether this is caused by my config or it is caused by the code. 


// fetchPodLabels retrieves the labels from the podspec metadata
func (c *APIClient) fetchPodLabels(ns, name string) error {
	var data interface{}

	// initiate a get request to the api server
	podURL := c.baseURL + ns + "/pods/" + name
	req, err := http.NewRequest("GET", podURL, nil)
	if err != nil {
		return err
	}
	if len(strings.TrimSpace(c.authToken)) > 0 {
		req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", c.authToken))
	}
	r, err := c.client.Do(req)
	if err != nil {
		return err
	}

	defer r.Body.Close()
	switch {
	case r.StatusCode == int(404):
		return fmt.Errorf("page not found")
	case r.StatusCode == int(403):
		return fmt.Errorf("access denied")
	case r.StatusCode != int(200):
		log.Errorf("GET Status '%s' status code %d \n", r.Status, r.StatusCode)
		return fmt.Errorf("%s", r.Status)
	}

**Comment by gaurav-dalvi** [comment]
i will let @jojimt to comment on this one.

In general to use netplugin as per your requirements, You can refer this one  : https://github.com/contiv/netplugin/blob/master/install/HowtoSetupContiv.md

**Comment by gaurav-dalvi** [comment]
your netplugin version is older. Please use the latest version from here : 

https://github.com/contiv/netplugin/releases

**Comment by jojimt** [comment]
@peiqi-caicloud If you want to use token based auth, you will need to the latest netplugin release and you need to avoid specifying the certs. Alternatively, you can stick to the cert based auth and make sure the certs you specify are valid.

**Comment by peiqi-caicloud** [comment]
Hello, @jojimt, thank you for your reply!!  

does netplugin support user password based auth now ?  I read the code but I have not found user password based info related information

**Comment by peiqi-caicloud** [comment]
Hello,  @jojimt  @gaurav-dalvi   I replaced the latest netplugin release; I have two questions 

First, there is a netcontiv binary, could you let me know what this binary used for and where should I place it. 

secondly, I configured the /opt/contiv/config/config.json file as below but the netplugin can not turn into active:

{
  "K8S_API_SERVER": "https://192.168.16.116:6443",
  "K8S_TOKEN": "qHmHFgPaLW0MGtHx8PTK93PmWnvrJqmn"
}

**Comment by peiqi-caicloud** [comment]
thanks @jojimt, I think this issue can be closed.
