### ISSUE TITLE
How to deploy on two host or more host?

### ISSUE THREAD

**Issue by xiaodan1** [contiv/netplugin#686]
I have a based problem, how to deploy on two host?
e.g. the one host to run netmaster service and netplugin service,
another one to run netplugin service only?
I not use vbox + vagrant , I use "go install" command to compile.

**Comment by gaurav-dalvi** [comment]
@xiaodan1 : May I know which orchestration engine (swarm or Kubernetes) you are planning to use ?
also which docker version , you are installing ? 

@gkvijay Could you please respond to this ?

**Comment by gkvijay** [comment]
@xiaodan1, are you trying to run the netplugin/netmaster binaries? Do you have etcd running? Please also let us know version of docker, OS and orchestration.

**Comment by xiaodan1** [comment]
thanks, 
OS: Centos7
docker-engine version: 1.12.5
OVS version: 2.5.0
I use netplugin/netmaster binaries to run , and also run etcd, but The etcd to running not etcd`s cluster,(only one etcd service.)
I modify netplugin/netmaster and netplugin/netplugin code ,  from 127.0.0.1:2379 or localhost:2379  to  <etcd node ip>:2379, and then compile to binaries.
I not use orchestration engine (swarm or Kubernetes) . only use docker-engine.

**Comment by xiaodan1** [comment]
@gkvijay My environment following:
node1(192.168.51.90/24):  running netmaster service,  netplugin service , netctl (from code compile                                           binaries)
                                          etcd container(docker run -itd -p 2379:2379 elcolio/etcd /bin/bash )
                                          The /etc/hosts  file  have  "127.0.0.1  netmaster"
                                          for docker daemon add option "--cluster-store=etcd://192.168.51.90:2379"
![image](https://cloud.githubusercontent.com/assets/22994530/21792121/7d548774-d722-11e6-8027-c07f52341da0.png)

node2(192.168.51.35/24): running netplugin service , netctl (from code compile binaries)
                                         not running etcd, but i modify the netplugin/netplugin/{netd.go,skydns2.go}:
                                         and then again compile netplugin/netplugin to get binary of netplugin:
![image](https://cloud.githubusercontent.com/assets/22994530/21791675/7b9e9706-d71f-11e6-9044-8895e6f75fe8.png)
                                     The /etc/hosts file have  "192.168.51.90  netmaster"
                                     for docker daemon add option "--cluster-store=etcd://192.168.51.90:2379"
![image](https://cloud.githubusercontent.com/assets/22994530/21792126/8584b1da-d722-11e6-9903-5b04388dfec7.png)

I not use orchestration engine (swarm or Kubernetes) . only use docker-engine.

The result is : 
    on node1:   "netctl net create -s 20.0.0.1/24 -e vlan -p 20 contiv-vlan20" , 
        and "netctl net ls" is ok, "docker network ls" is ok,
        but  on node2 "netctl net ls" is ok,  "docker network ls" is error,(have not 'contiv-vlan20').
    on node2:    "netctl net create -s 30.0.0.1/24 -e vlan -p 30 contiv-vlan30" , 
        and "netctl net ls" is ok, "docker network ls" is error,(have not 'contiv-vlan30').
        but  on node1 "netctl net ls" is ok,  "docker network ls" is ok .

**Comment by DivyaVavili** [comment]
@xiaodan1: Could you recheck your environment states and configs? The same scenario works for me.

Also, you don't have to modify netplugin/netmaster to pass the etcd IP. You could use the -cluster-store option in both netmaster and netplugin as you did for dockerd.

**Comment by DivyaVavili** [comment]
@xiaodan1: I ran into your issue when docker on node2 was not started before etcd was started on node1. 
Try the following sequence:
1. Start docker daemon on both node1 and node2 with cluster-store option
2. Start etcd on node1 with -p 2379:2379
3. Start netmaster and netplugin services and execute netctl commands (you can use cluster-store option here as well)

**Comment by xiaodan1** [comment]
execute netctl commands (you can use cluster-store option here as well)  ??
How to use --cluster-store option when i execute netctl commands ???

**Comment by xiaodan1** [comment]
You are right, It`s all ok!!
on node1:
![image](https://cloud.githubusercontent.com/assets/22994530/21801759/ff375538-d75d-11e6-8041-d608221afc1a.png)

on node2:
![image](https://cloud.githubusercontent.com/assets/22994530/21801770/0f20d9ba-d75e-11e6-8fbf-6f2b4ef79dd2.png)

Is really the cause of the startup sequence.
Thank you very much.
