### ISSUE TITLE
Want to make netmaster  ip address configurable  

### ISSUE THREAD

**Issue by peiqi-caicloud** [contiv/netplugin#688]
Currently, the netmaster ip address is assigned by the first local address by default. This case is not always good, especially for vagrant environment.

I am thinking to make netmaster ip address configurable so that the connection between netplugin and kubelet(k8s) can be ensured.

@ddysher @keontang

**Comment by gaurav-dalvi** [comment]
@gkvijay @jojimt : could you please respond to this ?

**Comment by peiqi-caicloud** [comment]
in our case, we have several network interfaces: eth0 eth1 eth2 eth3.  The eth0 addr is 10.0.2.15 which  does not work. but netmaster takes it as its address and the netplugins on nodes trying to fetch infos from 10.0.2.15:9999, as a result, netplugins failed to create EPs.   I modified the netmaster addr to eth1 and it works.

**Comment by DivyaVavili** [comment]
Fixed by #818
