### ISSUE TITLE
Netctl panics during install (sometimes)

### ISSUE THREAD

**Issue by neelimamukiri** [contiv/netplugin#693]
This is the output of the installer:

TASK [contiv_network : pull aci-gw container] **********************************

and then some times it fails with the following message in (set aci mode)

TASK [contiv_network : set aci mode] *******************************************
fatal: [node1]: FAILED! => {"changed": true, "cmd": "netctl global set --fabric-mode aci", "delta": "0:00:00.008454", "end": "2017-01-12 07:46:09.941946", "failed": true, "rc": 2, "start": "2017-01-12 07:46:09.933492", "stderr": "panic: runtime error: invalid memory address or nil pointer dereference\n[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x47802c]\n\ngoroutine 1 [running]:\npanic(0x6ff980, 0xc420010120)\n\t/usr/local/go/src/runtime/panic.go:500 +0x1a1\ngithub.com/contiv/netplugin/netctl.setGlobal(0xc42006f440)\n\t/opt/gopath/src/github.com/contiv/netplugin/netctl/netctl.go:893 +0x19c\ngithub.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.Run(0x75230b, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7583e3, 0x15, 0x0, ...)\n\t/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:131 +0x79d\ngithub.com/contiv/netplugin/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc42006f200, 0xc42006f0e0, 0x0, 0x0)\n\t/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/app.go:280 +0x87b\ngithub.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.startApp(0x752ce0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x756e0a, 0x12, 0x0, ...)\n\t/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:209 +0x6e6\ngithub.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.Run(0x752ce0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x756e0a, 0x12, 0x0, ...)\n\t/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:59 +0x11d9\ngithub.com/contiv/netplugin/vendor/github.com/codegangsta/cli.(*App).Run(0xc42006efc0, 0xc42000c0a0, 0x5, 0x5, 0x0, 0x0)\n\t/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/app.go:173 +0xa35\nmain.main()\n\t/opt/gopath/src/github.com/contiv/netplugin/netctl/netctl/main.go:16 +0x11d", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by abhinandanpb** [comment]
@neelimamukiri this is because netmaster might not have completed its init. We will need to add delay before we set the aci mode in the ansible script.

**Comment by neelimamukiri** [comment]
@abhinandanpb, we already have a delay + retries at 
https://github.com/contiv/ansible/blob/master/roles/contiv_network/tasks/main.yml#L103-L109

Should this be increased? Or may be there is an underlying netmaster startup failure as well.

**Comment by abhinandanpb** [comment]
I doubt netmaster is failing. Can you check the next time it happens if netmaster failed ? We can try increasing delays and observe it for few runs.  
However this does warrant checks in netctl to verify the context to avoid panic. We should handle the error.

**Comment by gaurav-dalvi** [comment]
@abhinandanpb : we can not ask customer / outside people to change the script and do triaging. We need to try all possibilities within the team and then send message out.

**Comment by abhinandanpb** [comment]
@gaurav-dalvi  -> @neelimamukiri is in the team :)
