### ISSUE TITLE
Error when choosing a CIDR range inside a subnet 

### ISSUE THREAD

**Issue by erandu** [contiv/netplugin#698]
I am having an issue when I try to specifiy an CIDR  range available inside a contiv subnet, using something like :
`netctl  net create vlan3 -s 200.0.3.50-100/24 -g 200.0.3.254 --pkt-tag 3 --encap vlan`                     
According to the documentation (http://contiv.github.io/documents/networking/ipam.html), it should work, but I am having error message : `Err: subnet string invalid format `

- contiv/bin/netplugin  --version
Version: pv0.1-09-21-2016.01-34-18.UTC
GitCommit: 9930fee-unsupported
BuildTime: 09-21-2016.01-34-18.UTC

```
root@spu1_boot:/# contiv/bin/netctl  --netmaster net create vlan3 -s 200.0.3.50-100/24                                        
ERRO[Jan 16 09:18:56.753291457] ValidateNetwork retruned error for: &{Key:default:vlan3 Encap:vxlan Gateway: Ipv6Gateway: Ipv6Subnet: NetworkName:vlan3 NwType:data PktTag:0 Subnet:200.0.3.50-100/24 TenantName:default LinkSets:{EndpointGroups:map[] Servicelbs:map[] Services:map[]} Links:{Tenant:{ObjType: ObjKey:}}}. Err: subnet string invalid format 
ERRO[Jan 16 09:18:56.753336389] CreateNetwork error for: {Key:default:vlan3 Encap:vxlan Gateway: Ipv6Gateway: Ipv6Subnet: NetworkName:vlan3 NwType:data PktTag:0 Subnet:200.0.3.50-100/24 TenantName:default LinkSets:{EndpointGroups:map[] Servicelbs:map[] Services:map[]} Links:{Tenant:{ObjType: ObjKey:}}}. Err: subnet string invalid format 
ERRO[Jan 16 09:18:56.753354300] Handler for POST /api/v1/networks/default:vlan3/ returned error: subnet string invalid format 
ERRO[0000] subnet string invalid format
```

**Comment by gaurav-dalvi** [comment]
@jojimt / @DivyaVavili  / @abhinandanpb could you please take a look ?

**Comment by DivyaVavili** [comment]
@gaurav-dalvi: The subnet range format should be specified in this format: 
200.0.3.50-200.0.3.100/24

We need to change the document accordingly
