### ISSUE TITLE
Make netplugin_ci more robust to repo failures

### ISSUE THREAD

**Issue by dojacobs** [contiv/netplugin#703]
netplugin_ci relies on some external repos for the build, namely epel and ceph.  Unfortunately, there are a lot of transitory network issues that cause one or the other to become unavailable, and then that particular netplugin_ci job fails, but the entire PR job fails as well.

Should make the build script or Jenkins detect these failures, sleep for a bit, and then start over from the beginning.  (for a maximum of number of retries.)

This should hopefully reduce the number of failed PR jobs due to stupid network/repository issues.

**Comment by dojacobs** [comment]
@unclejack - here's the issue.  I'll look at into what Jenkins might be able to do.

**Comment by dojacobs** [comment]
One solution: rewrite the netplugin_ci job as a pipeline(groovy) script, so each step can be retried if it fails, or abort after n retries.  (may require update to latest version of Jenkins though.)
Example:

stage "foo"
retry (3) {
    # pull from repo...
}

**Comment by dojacobs** [comment]
@JohnKDay says there is local repo for Centos which may contain the ceph and epel stuff, so we may be able to avoid this problem entirely.  Need to change our build system configuration for this.  (at least for netplugin_ci.)

**Comment by unclejack** [comment]
@dojacobs I've updated https://github.com/contiv/netplugin/pull/687 to make the provisioning more robust. It removes the ceph repository because it's not used in the Vagrant environment.

This should solve all problems related to ceph.
