### ISSUE TITLE
Port information should be included in netmaster leader address key

### ISSUE THREAD

**Issue by dseevr** [contiv/netplugin#704]
`netmaster` supports specifying a custom listener ip and port via `--listen-url` but the port information is not recorded in the current leader address key:

```
[vagrant@netplugin-node1 netplugin]$ etcdctl get /contiv.io/lock/netmaster/leader
192.168.2.10
```

**Comment by jojimt** [comment]
The leader address key is distinct from the netmaster API endpoint. In fact, the for API purposes, the leader key does not even matter. You can pick any of the netmasters regardless of whether it is the leader or not. Just need to append the custom API port (which is fixed).

**Comment by dseevr** [comment]
@jojimt Do you mean that port 9999 is fixed?  I see that it's hardcoded in a few spots:

https://github.com/contiv/netplugin/blob/master/netmaster/daemon/daemon.go#L109
https://github.com/contiv/netplugin/blob/master/netmaster/daemon/utils.go#L113

If this is the case, starting a netmaster on anything but port 9999 seems like it would break things, and we currently support doing this (e.g., `--listen-url=192.168.1.10:12345`)

**Comment by jojimt** [comment]
We will fix the hard-coding.

**Comment by dseevr** [comment]
Opened a new issue to track it:  https://github.com/contiv/netplugin/issues/705
