### ISSUE TITLE
When constructing leader URL for forwarding requests, netmaster should not use a hardcoded port

### ISSUE THREAD

**Issue by dseevr** [contiv/netplugin#705]
See discussion in:  https://github.com/contiv/netplugin/issues/704

The ports are currently hardcoded in the following two spots:
- https://github.com/contiv/netplugin/blob/c891b87f51f75c6c3cad0bde6bb92b0dab38b2fb/netmaster/daemon/utils.go#L113
- https://github.com/contiv/netplugin/blob/c891b87f51f75c6c3cad0bde6bb92b0dab38b2fb/netmaster/daemon/daemon.go#L109

**Comment by DivyaVavili** [comment]
Fixed by #818
