### ISSUE TITLE
panic executing netctl when configuring fabric-mode aci 

### ISSUE THREAD

**Issue by roschaer** [contiv/netplugin#719]
#Versions:
Updated centos7

kubeadm version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-alpha.0.2074+a092d8e0f95f52", GitCommit:"a092d8e0f95f5200f7ae2cba45c75ab42da36537", GitTreeState:"clean", BuildDate:"2016-12-13T17:03:18Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

./netctl version
Version: v0.1-11-30-2016.20-08-20.UTC
GitCommit: c39b3d8
BuildTime: 11-30-2016.20-08-20.UTC

#Error:
[root@k8s-master netplugin]# ./netctl global set --fabric-mode aci --vlan-range 100-499
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x477f04]

goroutine 1 [running]:
panic(0x6fe960, 0xc4200120f0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/contiv/netplugin/netctl.setGlobal(0xc420079440)
	/opt/gopath/src/github.com/contiv/netplugin/netctl/netctl.go:891 +0x154
github.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.Run(0x7512cb, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x757383, 0x15, 0x0, ...)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:131 +0x79d
github.com/contiv/netplugin/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc420079200, 0xc4200790e0, 0x0, 0x0)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/app.go:280 +0x87b
github.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.startApp(0x751ca0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x755daa, 0x12, 0x0, ...)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:209 +0x6e6
github.com/contiv/netplugin/vendor/github.com/codegangsta/cli.Command.Run(0x751ca0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x755daa, 0x12, 0x0, ...)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/command.go:59 +0x11d9
github.com/contiv/netplugin/vendor/github.com/codegangsta/cli.(*App).Run(0xc420078fc0, 0xc42000c0e0, 0x7, 0x7, 0x0, 0x0)
	/opt/gopath/src/github.com/contiv/netplugin/vendor/github.com/codegangsta/cli/app.go:173 +0xa35
main.main()
	/opt/gopath/src/github.com/contiv/netplugin/netctl/netctl/main.go:16 +0x11d

**Comment by dseevr** [comment]
I believe this has been fixed by https://github.com/contiv/netplugin/pull/695

**Comment by dseevr** [comment]
Closing as this issue has been fixed for a while
