### ISSUE TITLE
Remove "v" prefix from automated releases

### ISSUE THREAD

**Issue by dseevr** [contiv/netplugin#724]
I missed this in https://github.com/contiv/netplugin/pull/696 :frowning_face: 

semver doesn't allow a "v" at the start of the version string.

cc: @neelimamukiri

**Comment by unclejack** [comment]
@dseevr It's good to see you've assigned this to me. This is fixed by https://github.com/contiv/netplugin/pull/699 ;)

**Comment by dseevr** [comment]
@unclejack awesome, I saw that PR but didn't notice you had deleted the "v" in it 👍
