### ISSUE TITLE
netctl global set --fwd-mode bridge overwrites networkInfraType

### ISSUE THREAD

**Issue by neelimamukiri** [contiv/netplugin#737]
$ netctl global info                  
Fabric mode: default
Forward mode: bridge
ARP mode: proxy
Vlan Range: 1-4094
Vxlan range: 1-10000

$ netctl global set --fabric-mode aci 
$ netctl global info                  

Fabric mode: aci
Forward mode: bridge
ARP mode: proxy
Vlan Range: 1-4094
Vxlan range: 1-10000

$ netctl global set --fwd-mode bridge
$ netctl global info
Fabric mode: default    ******* Fabric mode should not be overwritten here.
Forward mode: bridge
ARP mode: proxy
Vlan Range: 1-4094

**Comment by jojimt** [comment]
@neelimamukiri @abhinandanpb This is by design. The CLI has default options. If you don't specify the option, it will default.

**Comment by abhinandanpb** [comment]
@jojimt since we allow global set to update any field. This should not be set to default. 
fabric-mode is implicitly set to default at init time by netmaster. So it will be changed only if someone explicitly sets different fabric-mode using netctl/Rest call

**Comment by jojimt** [comment]
I think you're confusing REST api and cli. CLI does have default values for all options (just like command line args).

**Comment by abhinandanpb** [comment]
except tenant which is for most of the configs we dont need default values set by the cli. Since we can set any global option at any time. Setting default value when it was set to non default previously would be wrong. 
for eg : netctl global set --fabric-mode aci
followed by netctl global set --arp-mode flood
should honor the fabric mode aci.

**Comment by neelimamukiri** [comment]
@jojimt, I think it is a little confusing from the end user perspective to have the defaults overwrite explicitly set values. I think a read/modify/write semantic may be better in this case. That way we can use the default values for a case where there are no previous user configurations and use the earlier set values for when there is a user specified value.

**Comment by rhim** [comment]
This is also inline with what UI does (it performs a read/modify/write on the object).

**Comment by jojimt** [comment]
I think this would be confusing whichever way we do this. I think we are saying these fields have an "initial" value, rather than a default. That said, as @abhinandanpb pointed out, we have ridden of most default values on the global object already. So, I am ok with this definition.
