### ISSUE TITLE
error with netctl aci-gw set command

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#753]
[root@pod12-srv1 yum.repos.d]# netctl aci-gw set -n "topology/pod-1/node-201,topology/pod-1/node-202" -d "Contiv-PD" -e yes -i no
ERRO[0000] aciGw not found
see this issue with

contiv/aci-gw:02-02-2017.2.1_1h
contiv/aci-gw:12-01-2016.2.1_1h

**Comment by jojimt** [comment]
Looks like a bug in netctl. Works with the GUI.
