### ISSUE TITLE
Subnet IP Pool Range - Broken with subnet capacity error

### ISSUE THREAD

**Issue by shmcfarl** [contiv/netplugin#766]
In the contiv-1.0.0-beta.3 code, when I create a new network with a range, the netmaster logs errors with subnet capacity issues.  This does not happen with all ranges but only certain lengths.  Example:
`netctl network create --encap=vlan --pkt-tag=100 --subnet=10.100.100.194-10.100.100.222/27 --gateway=10.100.100.193 vlan100
Creating network default:vlan100`

This subnet will create the following errors in the netmaster.log:

`time="Mar  1 00:13:49.961773593" level=info msg="Received NetworkCreate: &{Key:default:vlan100 Encap:vlan Gateway:10.100.100.193 Ipv6Gateway: Ipv6Subnet: NetworkName:vlan100 NwType:data PktTag:100 Subnet:10.100.100.194-10.100.100.222/27 TenantName:default LinkSets:{EndpointGroups:map[] Servicelbs:map[] Services:map[]} Links:{Tenant:{ObjType: ObjKey:}}}"
time="Mar  1 00:13:52.173082926" level=info msg="Received NetworkInspect: &{Config:{Key:default:vlan100 Encap:vlan Gateway:10.100.100.193 Ipv6Gateway: Ipv6Subnet: NetworkName:vlan100 NwType:data PktTag:100 Subnet:10.100.100.194-10.100.100.222/27 TenantName:default LinkSets:{EndpointGroups:map[] Servicelbs:map[] Services:map[]} Links:{Tenant:{ObjType:tenant ObjKey:default}}} Oper:{AllocatedAddressesCount:0 AllocatedIPAddresses: AvailableIPAddresses: Endpoints:[] ExternalPktTag:0 NumEndpoints:0 PktTag:0}}"
time="Mar  1 00:13:52.173761740" level=error msg="GetAllocatedIPs: getting ipAddress for idx 32: host id 32 is beyond subnet's capacity 32 [github.com/contiv/netplugin/utils/netutils.GetSubnetIP netutils.go 303]"
time="Mar  1 00:13:52.173825522" level=error msg="GetAllocatedIPs: getting ipAddress for idx 63: host id 63 is beyond subnet's capacity 32 [github.com/contiv/netplugin/utils/netutils.GetSubnetIP netutils.go 303]"`

**Comment by jojimt** [comment]
This does not seem to be "broken". The functionality is all there. However, there is a spurious error message generated in the logs when an inspect is issued. Basically, GetAllocatedIPs encounters an error as nothing has been allocated. We will remove the error log. But, you should be able to use the network. Let me know if that's not the case.

**Comment by shmcfarl** [comment]
If you say so.  :-)
