### ISSUE TITLE
DeleteEndpoint related unittests occassionally fail with 'Ovs port/intf not found' error

### ISSUE THREAD

**Issue by mapuri** [contiv/netplugin#78]
OvsDriver.DeleteEndpoint() depends on the ovsdb cache to have been updated once the port is created. The cache update happens asynchronously through a libovsdb callback. So there is a timing window where cache might not yet have been updated, if a DeleteEndpoint() is called immediately after CreateEndpoint(), as is the case with the testblocks.

For now a workaround is added to the test to add a delay between these calls, but a proper fix needs to be identified.

++++

--- FAIL: TestOvsDriverDeleteEndpointiWithIntfName (0.08s)
        ovsdriver_test.go:527: endpoint Deletion failed. Error: Ovs port/intf not found for id: testDeleteEpWithIntf [ovsdriver.go 232]

**Comment by shaleman** [comment]
I believe this has been fixed a while ago(we stopped using external-id field in ovsdb)
please reopen if you see it.
