### ISSUE TITLE
Display formatting issue with netprofile

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/netplugin#817]
```
[vagrant@contiv-node3 ~]$ netctl group ls -a
Tenant      Group  Network  IP Pool   Policies  Network profile
------      -----  -------  --------  ---------------
TestTenant  epgA   TestNet              testProfile

```

where testProfile is network profile and not policy.

**Comment by kahou82** [comment]
@gaurav-dalvi it looks ok with contiv 1.1.6

`[vagrant@netplugin-node1 ~]$ netctl group ls -t BandwidthTenant -a
Tenant           Group  Network           IP Pool  CfgdTag  Policies  Network profile
------           -----  -------           -------  -------  --------  ---------------
BandwidthTenant  epgA   BandwidthTestNet
BandwidthTenant  epgB   BandwidthTestNet                              testProfile`
