### ISSUE TITLE
About: release-1.0   how to use cfgtool binary for etcdstatedriver;  kubernetes 

### ISSUE THREAD

**Issue by peiqi-caicloud** [contiv/netplugin#851]
Hello,

I build the release-1.0 version and Got netmaster, netplugin, contivk8s, netctl and cfgtool.
I installed netmaster, netplugin, contivk8s, netctl these four binaries in a 4 nodes k8s cluster. 

I got the following logs, I don't know how to install cfgtool, Is it necessary to build the cluster ？

[root@172-25-9-142 ansible-dhNet]# systemctl status netmaster -l
● netmaster.service - Netmaster
   Loaded: loaded (/usr/lib/systemd/system/netmaster.service; enabled; vendor preset: disabled)
   Active: active (running) since 五 2017-04-21 08:49:19 CST; 24h ago
 Main PID: 16228 (netmaster)
   Memory: 30.3M
   CGroup: /system.slice/netmaster.service
           └─16228 /usr/bin/netmaster --cluster-mode=kubernetes --cluster-store=etcd://172.25.9.142:2379

4月 22 09:09:01 172-25-9-142 netmaster[16228]: time="Apr 22 09:09:01.248456743" level=error msg="Handler for POST /plugin/createEndpoint returned error: Key not found [github.com/contiv/netplugin/state.(*EtcdStateDriver).Read etcdstatedriver.go 121]"
4月 22 09:09:01 172-25-9-142 netmaster[16228]: time="Apr 22 09:09:01.443978587" level=info msg="Received CreateEndpointRequest: {TenantName:default NetworkName:default-net ServiceName: EndpointID:7776e0f66dd55f13e6e7d6f1f6412947d66c886c395b1136bfd06336570b9c41 EPCommonName:nginx-701339712-qkq7d ConfigEP:{Container:7776e0f66dd55f13e6e7d6f1f6412947d66c886c395b1136bfd06336570b9c41 Host:172-25-9-144 IPAddress: IPv6Address: ServiceName:}}"
4月 22 09:09:01 172-25-9-142 netmaster[16228]: time="Apr 22 09:09:01.444848451" level=error msg="network default-net.default is not operational"
4月 22 09:09:01 172-25-9-142 netmaster[16228]: time="Apr 22 09:09:01.444895164" level=error msg="Handler for POST /plugin/createEndpoint returned error: Key not found [github.com/contiv/netplugin/state.(*EtcdStateDriver).Read etcdstatedriver.go 121]"
4月 22 09:09:01 172-25-9-142 netmaster[16228]: time="Apr 22 09:09:01.687782635" level=info msg="Received CreateEndpointRequest: {TenantName:default NetworkName:default-net ServiceName: EndpointID:501480e6ef5f332cce231da2422b815920c6d57dfc1ad64d321499a5cffd3e03 EPCommonName:nginx-701339712-jkgsv ConfigEP:{Container:501480e6ef5f332cce231da2422b815920c6d57dfc1ad64d321499a5cffd3e03 Host:172-25-9-144 IPAddress: IPv6Address: ServiceName:}}"
4月 22 09:09:01 172-25-9-142 netmaster[16228]: time="Apr 22 09:09:01.688610616" level=error msg="network default-net.default is not operational"
4月 22 09:09:01 172-25-9-142 netmaster[16228]: time="Apr 22 09:09:01.688643032" level=error msg="Handler for POST /plugin/createEndpoint returned error: Key not found [github.com/contiv/netplugin/state.(*EtcdStateDriver).Read etcdstatedriver.go 121]"
4月 22 09:09:01 172-25-9-142 netmaster[16228]: time="Apr 22 09:09:01.870712917" level=info msg="Received CreateEndpointRequest: {TenantName:default NetworkName:default-net ServiceName: EndpointID:cee9835fa687640d1e6bea8378b7a5618656b342fd554d72219ba4abb16d9033 EPCommonName:nginx-701339712-ssk68 ConfigEP:{Container:cee9835fa687640d1e6bea8378b7a5618656b342fd554d72219ba4abb16d9033 Host:172-25-9-144 IPAddress: IPv6Address: ServiceName:}}"
4月 22 09:09:01 172-25-9-142 netmaster[16228]: time="Apr 22 09:09:01.871537505" level=error msg="network default-net.default is not operational"
4月 22 09:09:01 172-25-9-142 netmaster[16228]: time="Apr 22 09:09:01.871574432" level=error msg="Handler for POST /plugin/createEndpoint returned error: Key not found [github.com/contiv/netplugin/state.(*EtcdStateDriver).Read etcdstatedriver.go 121]"
[root@172-25-9-142 ansible-dhNet]#

**Comment by peiqi-caicloud** [comment]
Besides, I got my kubelet logs: in the " network setup " step, It seems the /run/contiv/contiv-cni.sock reused to be connected ?  

d-2624-11e7-a0d0-0cc47ab4e904)\" using network plugins \"cni\": Contiv:Post http://localhost/ContivCNI.AddPod: dial unix /run/contiv/contiv-cni.sock: connect: connection refused; Skipping pod"
d-261b-11e7-a0d0-0cc47ab4e904)\" using network plugins \"cni\": Contiv:Post http://localhost/ContivCNI.AddPod: dial unix /run/contiv/contiv-cni.sock: connect: connection refused; Skipping pod"


: connect: connection refused; Skipping pod


: connect: connection refused; Skipping pod
(b1db1689-261b-11e7-a0d0-0cc47ab4e904)\" using network plugins \"cni\": Contiv:Post http://localhost/ContivCNI.AddPod: dial unix /run/contiv/contiv-cni.sock: connect: connection refused; Skipping pod"
(b1dc1bdb-261b-11e7-a0d0-0cc47ab4e904)\" using network plugins \"cni\": Contiv:Post http://localhost/ContivCNI.AddPod: dial unix /run/contiv/contiv-cni.sock: connect: connection refused; Skipping pod"


: connect: connection refused; Skipping pod


nnect: connection refused; Skipping pod
(b1de04ee-261b-11e7-a0d0-0cc47ab4e904)\" using network plugins \"cni\": Contiv:Post http://localhost/ContivCNI.AddPod: dial unix /run/contiv/contiv-cni.sock: connect: connection refused; Skipping pod"
6-261b-11e7-a0d0-0cc47ab4e904)\" using network plugins \"cni\": Contiv:Post http://localhost/ContivCNI.AddPod: dial unix /run/contiv/contiv-cni.sock: connect: connection refused; Skipping pod"


nnect: connection refused; Skipping pod
d-2624-11e7-a0d0-0cc47ab4e904)\" using network plugins \"cni\": Contiv:Post http://localhost/ContivCNI.AddPod: dial unix /run/contiv/contiv-cni.sock: connect: connection refused; Skipping pod"


nnect: connection refused; Skipping pod


: connect: connection refused; Skipping pod
d-261b-11e7-a0d0-0cc47ab4e904)\" using network plugins \"cni\": Contiv:Post http://localhost/ContivCNI.AddPod: dial unix /run/contiv/contiv-cni.sock: connect: connection refused; Skipping pod"


: connect: connection refused; Skipping pod
(b1db1689-261b-11e7-a0d0-0cc47ab4e904)\" using network plugins \"cni\": Contiv:Post http://localhost/ContivCNI.AddPod: dial unix /run/contiv/contiv-cni.sock: connect: connection refused; Skipping pod"
(b1dc1bdb-261b-11e7-a0d0-0cc47ab4e904)\" using network plugins \"cni\": Contiv:Post http://localhost/ContivCNI.AddPod: dial unix /run/contiv/contiv-cni.sock: connect: connection refused; Skipping pod"

**Comment by DivyaVavili** [comment]
@peiqi-caicloud: cfgtool is not required to get the cluster up and running. Could you confirm if you have created the default-net before deploying anything else in the cluster?

**Comment by peiqi-caicloud** [comment]
@DivyaVavili Hello,  I deployed kubernetes cluster and create pods for test (It uses default docker0 to setup network at that time), then installed netplugin components manually and reconfigured k8s. After that I found no network was created in default tenant so I used netctl to create a network. I also created net group and policy...

**Comment by peiqi-caicloud** [comment]
In which situation we shall use cfgtool ? I am interested in it.

**Comment by peiqi-caicloud** [comment]
caused by bad config...
