### ISSUE TITLE
Contiv with K8s Tutorial - Netplugin - "tcp :9002: bind: address already in use" 

### ISSUE THREAD

**Issue by truncj** [contiv/netplugin#874]
Hi guys -- I'm running into a few issues using the [tutorial](http://contiv.github.io/documents/gettingStarted/networking/k8s.html).

After running ./setup_cluster.sh I'm having issues with netplugin and netmaster pods, despite them running.

- [vagrant@k8master log]$ k get pods -o wide
- NAME                               READY     STATUS          RESTARTS   AGE       IP             NODE
- contiv-etcd-s5bvc                  1/1       Running         0          23m       192.168.2.10   k8master
- contiv-netmaster-j7k50             1/1       Running         0          22m       192.168.2.10   k8master
- contiv-netplugin-19khk             1/1       Running         0          7m        192.168.2.10   k8master
- contiv-netplugin-2vppk             1/1       Running         0          7m        192.168.2.11   k8node-01
- etcd-k8master                      1/1       Running         0          25m       192.168.2.10   k8master
- kube-apiserver-k8master            1/1       Running         1          1h        192.168.2.10   k8master
- kube-controller-manager-k8master   1/1       Running         1          1h        192.168.2.10   k8master
- kube-dns-3913472980-jm4sg          0/3       rpc error:		 3          46m       <none>         k8node-01
- kube-proxy-6x5zf                   1/1       Running         0          1h        192.168.2.11   k8node-01
- kube-proxy-s25hv                   1/1       Running         0          1h        192.168.2.10   k8master
- kube-scheduler-k8master            1/1       Running         1          1h        192.168.2.10   k8master

The logs for netplugin (below) show that there's an issue with "**listen error:listen tcp :9002: bind: address already in use**"

- [vagrant@k8master log]$ tail netplugin.log 
- time="May  9 19:53:22.698593900" level=info msg="Initing service plugin" 
- time="May  9 19:53:22.767295090" level=info msg="Creating a new bridge: etcd://192.168.2.10:6666" 
- 2017/05/09 19:53:22 Extension point components: {map[etcd:0x17a0150]}
- time="May  9 19:53:22.767345949" level=info msg="Using%!(EXTRA string=etcd, string=service adapter:, *url.URL=etcd://192.168.2.10:6666)" 
- time="May  9 19:53:22.767392602" level=info msg="Connecting to backend (0/0)" 
- time="May  9 19:53:22.830501237" level=info msg="Initializing ovsdriver" 
- time="May  9 19:53:22.830529052" level=info msg="Received request to create new ovs switch bridge:contivVxlanBridge, localIP:192.168.2.10, fwdMode:bridge" 
- time="May  9 19:53:22.881962616" level=info msg="Creating new ofnet agent for contivVxlanBridge,vxlan,[0 0 0 0 0 0 0 0 0 0 255 255 192 168 2 10],9002,6633,[] \n" 
- time="May  9 19:53:22.882209579" level=fatal msg="listen error:listen tcp :9002: bind: address already in use" 

Netmaster logs are showing some activity as well, hopping back and forth between port 9002 and 9003 -but the kubectl logs for netmaster show "CRITICAL ERROR - Netplugin Failed"

- [vagrant@k8master log]$ tail netmaster.log 
- time="May  9 19:50:12.082731662" level=info msg="Sending service del event: {ServiceName:netplugin Role: Version: TTL:10 HostAddr:192.168.2.10 Port:9003 Hostname:k8master}" 
- time="May  9 19:50:12.965607607" level=info msg="Registered node: &{HostAddr:192.168.2.10 HostPort:9003}" 
- time="May  9 19:50:18.995567579" level=info msg="Connecting to RPC server: 192.168.2.10:9002" 
- time="May  9 19:50:18.996666653" level=info msg="Connected to RPC server: 192.168.2.10:9002" 
- time="May  9 19:50:18.997727393" level=info msg="Sending service add event: {ServiceName:netplugin Role: Version: TTL:10 HostAddr:192.168.2.10 Port:9003 Hostname:k8master}" 
- time="May  9 19:50:20.671028839" level=info msg="Registered node: &{HostAddr:192.168.2.10 HostPort:9002}" 
- time="May  9 19:50:21.317046434" level=info msg="Unregister node {HostAddr:192.168.2.10 HostPort:9003}" 
- time="May  9 19:50:21.433561489" level=info msg="Connecting to RPC server: 192.168.2.10:9003" 
- time="May  9 19:50:21.433771219" level=info msg="Connected to RPC server: 192.168.2.10:9003" 
- time="May  9 19:50:24.199166501" level=info msg="Registered node: &{HostAddr:192.168.2.10 HostPort:9003}" 

Any ideas to get around this issue? I had a few other issues with the tutorial that I'll cover in another issue, but I need to get this running sooner. Thanks!

docker version: 1.12.6
kubernetes version: 1.6.2
vagrant version: 1.9.4
virtualbox version: 5.1
OS: MacOS Sierra

**Comment by neelimamukiri** [comment]
The bind error is harmless and can be ignored. Can you post the complete logs?

The current supported install mechanism is to follow https://github.com/contiv/install. Please follow the k8s section there.
