### ISSUE TITLE
kube-dns - Liveness probe failed

### ISSUE THREAD

**Issue by truncj** [contiv/netplugin#878]
Hi guys, running into some issues with kube-dns pod. 

After my previous issue, I was advised to recreate the contivh1 infra network, which I have since recreated. Now I'm noticing in the kube-dns container of my pod is showing the following "liveness probe" error:

`Liveness probe failed: Get http://20.1.1.1:8080/healthz-dnsmasq: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

<img width="682" alt="screen shot 2017-05-15 at 11 45 13 am" src="https://cloud.githubusercontent.com/assets/1036796/26077482/2c66da40-398a-11e7-9617-959a78dfde87.png">

<img width="236" alt="screen shot 2017-05-15 at 2 19 00 pm" src="https://cloud.githubusercontent.com/assets/1036796/26077400/e5ceb8aa-3989-11e7-9ac8-9ba112cbcadc.png">

<img width="624" alt="screen shot 2017-05-15 at 4 24 42 pm" src="https://cloud.githubusercontent.com/assets/1036796/26077710/092e41ca-398b-11e7-859f-b0540b5850fc.png">

I've also noticed that there are no endpoints listed for kube-dns. Normally using calico, we see endpoints for kube-dns that reflect the IP of the kube-dns pod. 

<img width="299" alt="screen shot 2017-05-15 at 4 19 45 pm" src="https://cloud.githubusercontent.com/assets/1036796/26077525/569d7602-398a-11e7-91e5-d0ba3fe7fd2e.png">

Any ideas appreciated!

**Comment by rchirakk** [comment]
@truncj you need to specify a gateway for default-net  20.1.1.0/24 (netctl net create )

**Comment by truncj** [comment]
@rchirakk I recreated the cluster and created the default-net with a gateway (20.1.1.1)... The error is still the same.

`kubelet k8worker01}	spec.containers{kube-dns}	Warning	Unhealthy	Readiness probe failed: Get http://20.1.1.2:8081/readiness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
`

**Comment by rchirakk** [comment]
Can you try to access http://20.1.1.2:8081/readiness from host ? can we have a look at your setup ? webex ?

**Comment by truncj** [comment]
As suggested, I commented out the readiness/health probes using "kubectl edit deployment kube-dns".. this removes the error allowing all of the containers to come up. Still working with @rchirakk to get kube-dns working fully.

**Comment by rchirakk** [comment]
fixed in https://github.com/contiv/netplugin/pull/887
