### ISSUE TITLE
Make netplugin resilient against unconfigured data stores

### ISSUE THREAD

**Issue by dseevr** [contiv/netplugin#915]
## Description

When netplugin starts, it will contact etcd/consul ("the data store") and attempt to read the configuration it should use.  If no configuration is present, it will load a default configuration (mainly, forwarding mode becomes "bridge") and establish a watch to be notified of future changes.

There is some kind of race condition or timing bug where netplugin can come up but have a forwarding mode (and potentially other settings?) which does not match the current state of the data store.

This is pretty easy to reproduce using the `make demo-kubeadm` target in contiv/install.  One or both of the nodes will come up with the wrong forwarding mode.

There are a few issues here:

1.  The race condition/timing issue.  We should probably establish the watch before checking the data store for the config.  If we do things the other way around, there is a tiny window between the read and the establishing of the watch where we could miss an update.  I doubt this is the issue, but we should fix it.
2.  Should netplugin start with default settings in the absence of an available configuration?  I would say NO.  Even if netplugin receives a config via the data store watch shortly after it starts, **there is a period of time where it is 100% capable of servicing requests from Docker when it has no configuration loaded**.  This seems really bad and unnecessary and is easily avoided.  We could either poll in a loop until the configuration is present or just die (like when the data store is unavailable).  There are likely other options here, like having the configuration set up as part of the container bring-up, etc.
3.  We should modify our k8s yaml to have a readiness probe for netplugin.  The probe could be hitting one of the HTTP endpoints which isn't available until after the config is read + applied and the http listener socket is up.

#### Expected Behavior

Netplugin shouldn't come up in a different forwarding mode than its data store is specifying.

## Steps to Reproduce (for bugs)

1.  Clone contiv/install, run `make demo-kubeadm`
2.  `cd cluster`
3.  `vagrant ssh kubeadm-master -- sudo head /var/contiv/log/netplugin.log` <-- look at forwarding mode
4.  `vagrant ssh kubeadm-worker0 -- sudo head /var/contiv/log/netplugin.log` <-- look at forwarding mode

## Your Environment

* netctl version: 1.0.3
* Orchestrator version (e.g. kubernetes, mesos, swarm): k8s 1.6 and 1.7
* Operating System and version:  Mac OSX 10.11.6 and Ubuntu 16.04 LTS (amd64), both running latest Vagrant and Virtualbox

cc: @gkvijay @rhim

**Comment by kahou82** [comment]
@tiewei looks like it is something you have fixed?

**Comment by tiewei** [comment]
yes, this can be closed

**Comment by tiewei** [comment]
i think this has been resolved by contiv/netplugin#1043
