### ISSUE TITLE
With vlan mode of netplugin, docker network break sometimes

### ISSUE THREAD

**Issue by jiangsuwwj1** [contiv/netplugin#955]
Recently I encountered a network problem.
I used vlan mode of netplugin and create a subnet of 10.99.0.0/19, then specific the gateway of 10.99.0.252. So there will be eight thousand addresses in the subnet.
Sometimes docker network break for a while, about half a minute, then it recover again.

Does anyone encountered this problem? Or is there any method to troubleshoot it ?

**Comment by jiangsuwwj1** [comment]
In addition, there is lots of entries in openflow tables, Does this couse this problem?
ovs-ofctl dump-flows contivVlanBridge -O OpenFlow13
.........
 
 cookie=0x927, duration=9012.696s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.15 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x928, duration=9012.696s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.1.184 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x929, duration=9012.695s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.7.62 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x92a, duration=9012.694s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.1.32 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x92b, duration=9012.694s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.4.190 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x92c, duration=9012.693s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.5.233 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x92d, duration=9012.692s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.114 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x92e, duration=9012.692s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.0.161 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x92f, duration=9012.691s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.1.224 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x930, duration=9012.691s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.1.230 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x931, duration=9012.690s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.6.130 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x932, duration=9012.690s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.8.96 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x933, duration=9012.689s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.78 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x943, duration=8793.046s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.169 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x944, duration=8789.277s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.170 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x945, duration=8783.103s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.171 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x946, duration=8776.913s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.172 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x94b, duration=2597.228s, table=4, n_packets=2522, n_bytes=2899572, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.177 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x94c, duration=2594.466s, table=4, n_packets=2594, n_bytes=2910500, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.178 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x94d, duration=2591.048s, table=4, n_packets=2759, n_bytes=3184822, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.179 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x94e, duration=2586.840s, table=4, n_packets=2832, n_bytes=3224504, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.180 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x950, duration=2583.223s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.181 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x951, duration=2579.349s, table=4, n_packets=5368, n_bytes=3033638, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.182 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x952, duration=1829.028s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.1.194 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x953, duration=1823.826s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.183 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x954, duration=1820.485s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.184 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0x955, duration=1816.228s, table=4, n_packets=0, n_bytes=0, priority=100,ip,metadata=0x100000000/0xff00000000,nw_dst=10.99.9.185 actions=write_metadata:0/0xfffe,goto_table:5
 cookie=0xd, duration=9022.040s, table=4, n_packets=3209700, n_bytes=2306051464, priority=1 actions=goto_table:5
 cookie=0xe, duration=9022.040s, table=5, n_packets=3818199, n_bytes=2813476048, priority=1 actions=goto_table:6
 cookie=0xc, duration=9022.040s, table=6, n_packets=16227461, n_bytes=6722004461, priority=1 actions=goto_table:9
 cookie=0x15, duration=9022.038s, table=9, n_packets=16227461, n_bytes=6722004461, priority=1 actions=NORMAL

**Comment by gkvijay** [comment]
Please add more details. Are you using docker swarm or swarm-mode or kubernetes? which version? What are the steps to reproduce the issue? What is the observed behavior (what do you mean by docker network breaks?) You can also join contiv-users slack channel

**Comment by jiangsuwwj1** [comment]
root cause is arp table overflow.

**Comment by jiangsuwwj1** [comment]
close
