### ISSUE TITLE
Removal of Contiv network is possible even though there is a Docker Network attached to it

### ISSUE THREAD

**Issue by rkharya** [contiv/netplugin#962]
<img width="1490" alt="screen shot 2017-08-29 at 1 23 23 pm" src="https://user-images.githubusercontent.com/12057795/29810399-442ea55a-8cbd-11e7-81bb-f5a6242a9b0f.png">
## Description
v2Plugin on DEE 17.06 in native swarm mode, allows removal of Contiv network in L2/vLAN mode while its already attached with docker network by contiv-tag. 

#### Expected Behavior
It should throw an error while removing contiv network via `netctl network rm`. Removal of Contiv backend network leave Docker network with contiv driver in orphaned state and `docker service create` results in service deployment without any containers running. docker service throws not errors and it gets deployed. 

#### Observed Behavior
1).
RKHARYA-M-H07C:ucp-17.06-C rkharya$ docker network ls
NETWORK ID          NAME                                     DRIVER                  SCOPE
5a65d30ffbde        DEE-Ctrl-C-1.cisco.com/bridge            bridge                  local
fff4a7da2a01        DEE-Ctrl-C-1.cisco.com/docker_gwbridge   bridge                  local
8b98948f9e47        DEE-Ctrl-C-1.cisco.com/host              host                    local
573580b589d2        DEE-Ctrl-C-1.cisco.com/none              null                    local
75479d4151b8        DEE-Ctrl-C-2.cisco.com/bridge            bridge                  local
f7cc5018159e        DEE-Ctrl-C-2.cisco.com/docker_gwbridge   bridge                  local
762ae79b52eb        DEE-Ctrl-C-2.cisco.com/host              host                    local
ddf69843692a        DEE-Ctrl-C-2.cisco.com/none              null                    local
adbabf139804        DEE-Ctrl-C-3.cisco.com/bridge            bridge                  local
b8dbec7bb473        DEE-Ctrl-C-3.cisco.com/docker_gwbridge   bridge                  local
cc101f9652b0        DEE-Ctrl-C-3.cisco.com/host              host                    local
23405d0b69cb        DEE-Ctrl-C-3.cisco.com/none              null                    local
92ec4722a915        DEE-Wrk-C-1.cisco.com/bridge             bridge                  local
5200d9218cd0        DEE-Wrk-C-1.cisco.com/docker_gwbridge    bridge                  local
189906f6b69c        DEE-Wrk-C-1.cisco.com/host               host                    local
5d4e5c21347b        DEE-Wrk-C-1.cisco.com/none               null                    local
eyjbu3hr2fkk        contiv-net                               contiv/v2plugin:1.1.1   swarm
ph9qvuysdpig        dtr-ol                                   overlay                 swarm
u9wxzdotrtdy        ingress                                  overlay                 swarm

2)
RKHARYA-M-H07C:ucp-17.06-C rkharya$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                          PORTS
dewvl3g744yz        ucp-agent-s390x     global              0/0                 docker/ucp-agent-s390x:2.2.0
dha3b6tn6cfm        my-alpine           replicated          0/2                 alpine
s072llqvo79r        ucp-agent           global              4/4                 docker/ucp-agent:2.2.0
wzftqbref15u        ucp-agent-win       global              0/0                 docker/ucp-agent-win:2.2.0

3)
RKHARYA-M-H07C:ucp-17.06-C rkharya$ docker service ps my-alpine
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE        ERROR               PORTS
pq6qdq7btt4i        my-alpine.1         alpine                                  Running             New 17 minutes ago
u4uir4ddf45s        my-alpine.2         alpine                                  Running             New 17 minutes ago

4)
RKHARYA-M-H07C:ucp-17.06-C rkharya$ docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
353f16f97f7e        contiv/auth_proxy:1.1.1      "./auth_proxy --tl..."   5 days ago          Up 5 days                               DEE-Ctrl-C-1.cisco.com/auth-proxy
d04925636760        contiv/auth_proxy:1.1.1      "./auth_proxy --tl..."   5 days ago          Up 5 days                               DEE-Ctrl-C-3.cisco.com/auth-proxy
87209b40c0e7        contiv/auth_proxy:1.1.1      "./auth_proxy --tl..."   5 days ago          Up 5 days                               DEE-Ctrl-C-2.cisco.com/auth-proxy
f2cfa1acf3de        quay.io/coreos/etcd:v2.3.8   "/etcd"                  5 days ago          Up 5 days                               DEE-Wrk-C-1.cisco.com/etcd
72c01b081796        quay.io/coreos/etcd:v2.3.8   "/etcd"                  5 days ago          Up 5 days                               DEE-Ctrl-C-2.cisco.com/etcd
51d9d3a59ba9        quay.io/coreos/etcd:v2.3.8   "/etcd"                  5 days ago          Up 5 days                               DEE-Ctrl-C-3.cisco.com/etcd
83f266863920        quay.io/coreos/etcd:v2.3.8   "/etcd"                  5 days ago          Up 5 days                               DEE-Ctrl-C-1.cisco.com/etcd

5)
[root@DEE-Ctrl-C-1 ~]# netctl network ls -a
Tenant  Network  Nw Type  Encap type  Packet tag  Subnet   Gateway  IPv6Subnet  IPv6Gateway  Cfgd Tag
------  -------  -------  ----------  ----------  -------  ------   ----------  -----------  ---------

## Steps to Reproduce (for bugs)
1. Create Contiv tenant
2. Create Contiv network in L2/vLAN mode for the tenant -
netctl network create --nw-type data --encap vlan --pkt-tag 2001 --subnet 100.100.100.0/24 --gateway 100.100.100.254 --nw-tag contiv-net-tag contiv-net
3. Create Docker network using `-o contiv-tag` 
docker network create contiv-net -o contiv-tag=contiv-net-tag -d contiv/v2plugin:1.1.1 --ipam-opt contiv-tag=contiv-net-tag --ipam-driver contiv/v2plugin:1.1.1
4. Delete contiv nework -
netctl network rm contiv-net -t contiv-tenant
5. Docker network still exists with contiv driver -
RKHARYA-M-H07C:ucp-17.06-C rkharya$ docker network ls
NETWORK ID          NAME                                     DRIVER                  SCOPE
5a65d30ffbde        DEE-Ctrl-C-1.cisco.com/bridge            bridge                  local
fff4a7da2a01        DEE-Ctrl-C-1.cisco.com/docker_gwbridge   bridge                  local
8b98948f9e47        DEE-Ctrl-C-1.cisco.com/host              host                    local
573580b589d2        DEE-Ctrl-C-1.cisco.com/none              null                    local
75479d4151b8        DEE-Ctrl-C-2.cisco.com/bridge            bridge                  local
f7cc5018159e        DEE-Ctrl-C-2.cisco.com/docker_gwbridge   bridge                  local
762ae79b52eb        DEE-Ctrl-C-2.cisco.com/host              host                    local
ddf69843692a        DEE-Ctrl-C-2.cisco.com/none              null                    local
adbabf139804        DEE-Ctrl-C-3.cisco.com/bridge            bridge                  local
b8dbec7bb473        DEE-Ctrl-C-3.cisco.com/docker_gwbridge   bridge                  local
cc101f9652b0        DEE-Ctrl-C-3.cisco.com/host              host                    local
23405d0b69cb        DEE-Ctrl-C-3.cisco.com/none              null                    local
92ec4722a915        DEE-Wrk-C-1.cisco.com/bridge             bridge                  local
5200d9218cd0        DEE-Wrk-C-1.cisco.com/docker_gwbridge    bridge                  local
189906f6b69c        DEE-Wrk-C-1.cisco.com/host               host                    local
5d4e5c21347b        DEE-Wrk-C-1.cisco.com/none               null                    local
eyjbu3hr2fkk        contiv-net                               contiv/v2plugin:1.1.1   swarm
ph9qvuysdpig        dtr-ol                                   overlay                 swarm
u9wxzdotrtdy        ingress                                  overlay                 swarm
6. Docker service still can be created using Docker network with Contiv driver
7. Service spawns w/o any errors
8. Container doesn't come up online, SS attached

## Your Environment

* netctl version - 1.1.1
* Orchestrator version (e.g. kubernetes, mesos, swarm): ucp/2.2.0, DEE-17.06 native swarm mode
* Operating System and version - RHEL 7.3 Bare Metal
<img width="1680" alt="screen shot 2017-08-29 at 1 22 46 pm" src="https://user-images.githubusercontent.com/12057795/29810377-3014a736-8cbd-11e7-8df4-67e9d23fcb41.png">

**Comment by kahou82** [comment]
@rkharya I tried to reproduce it but seems fail at step #3

`[vagrant@netplugin-node1 ~]$ netctl network create --nw-type data --encap vlan --pkt-tag 2001 --subnet 100.100.100.0/24 --gateway 100.100.100.254 --nw-tag contiv-net-tag contiv-net
Creating network default:contiv-net

[vagrant@netplugin-node1 ~]$ netctl network list
Tenant   Network     Nw Type  Encap type  Packet tag  Subnet            Gateway          IPv6Subnet  IPv6Gateway  Cfgd Tag
------   -------     -------  ----------  ----------  -------           ------           ----------  -----------  ---------
default  contiv-net  data     vlan        2001        100.100.100.0/24  100.100.100.254                           contiv-net-tag

[vagrant@netplugin-node1 ~]$ docker network create contiv-net -o contiv-tag=contiv-net-tag -d contiv/v2plugin:1.1.1 --ipam-opt contiv-tag=contiv-net-tag --ipam-driver contiv/v2plugin:1.1.1
Error response from daemon: network with name contiv-net already exists`

Am I missing anything?

**Comment by blaksmit** [comment]
UCS team completed testing and the warning is now seen.
