### ISSUE TITLE
Swarm cluster reboot results in v2plugin bootup failures due to etcd cluster health issue

### ISSUE THREAD

**Issue by rkharya** [contiv/netplugin#963]
## Description
A 4-node swarm cluster running DEE 17.06 in native swarm mode with Contiv tenant/network created and `docker service` using Contiv network deployed. Cluster reboot caused Contiv plugin bootup failures resulting in service un-availability. 

Cluster config - DEE-Ctrl-1/2/3 - Swarm Managers and Contiv Masters; DEE-Wrk-1 - Swarm & Contiv worker node

#### Expected Behavior
Cluster node reboot should start all the previously running daemons and services gracefully without any failuers

#### Observed Behavior

1). UCP/Swarm cluster is in healthy state -

[root@DEE-Ctrl-C-1 contiv]# docker node ls
ID                            HOSTNAME                 STATUS              AVAILABILITY        MANAGER STATUS
d4ex4rpt3lf45nyr68n0hhbyn     DEE-Wrk-C-1.cisco.com    Ready               Active
j5093lckl3pyqom8cgukt1u2m *   DEE-Ctrl-C-1.cisco.com   Ready               Active              Reachable
jikws571sb9h10sog2e2mutwl     DEE-Ctrl-C-3.cisco.com   Ready               Active              Reachable
wezg87537cf22ltk1nxxnhypp     DEE-Ctrl-C-2.cisco.com   Ready               Active              Leader

RKHARYA-M-H07C:ucp-17.06-C rkharya$ docker info
Containers: 92
 Running: 58
 Paused: 0
 Stopped: 34
Images: 77
Server Version: ucp/2.2.0
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint, whitelist
Nodes: 4
 DEE-Ctrl-C-1.cisco.com: 10.65.121.121:12376
  └ ID: XDZI:SX3Y:ZXVJ:CEFO:4ND3:BJZ2:6Q34:JDXM:YR3Y:ARFH:2QMP:KKVM|10.65.121.121:12376
  └ Status: Healthy
  └ Containers: 27 (13 Running, 0 Paused, 14 Stopped)
  └ Reserved CPUs: 0 / 92
  └ Reserved Memory: 0 B / 264.2 GiB
  └ Labels: kernelversion=3.10.0-693.1.1.el7.x86_64, operatingsystem=Red Hat Enterprise Linux, ostype=linux, storagedriver=devicemapper
  └ UpdatedAt: 2017-08-30T04:31:55Z
  └ ServerVersion: 17.06.1-ee-1
 DEE-Ctrl-C-2.cisco.com: 10.65.121.122:12376
  └ ID: W3ZT:3DNO:JIA5:XIRM:2WWP:C3GI:IYQB:TAE6:3NGT:5NQK:U4SV:DAZY|10.65.121.122:12376
  └ Status: Healthy
  └ Containers: 30 (22 Running, 0 Paused, 8 Stopped)
  └ Reserved CPUs: 0 / 92
  └ Reserved Memory: 0 B / 264.2 GiB
  └ Labels: kernelversion=3.10.0-693.1.1.el7.x86_64, operatingsystem=Red Hat Enterprise Linux, ostype=linux, storagedriver=devicemapper
  └ UpdatedAt: 2017-08-30T04:31:54Z
  └ ServerVersion: 17.06.1-ee-1
 DEE-Ctrl-C-3.cisco.com: 10.65.121.123:12376
  └ ID: 2EOM:BDPX:IXVU:Z3ZF:AJKA:RVDI:ADWU:Y2NU:MJRS:DEMJ:YY4R:ASFM|10.65.121.123:12376
  └ Status: Healthy
  └ Containers: 27 (20 Running, 0 Paused, 7 Stopped)
  └ Reserved CPUs: 0 / 92
  └ Reserved Memory: 0 B / 264.2 GiB
  └ Labels: kernelversion=3.10.0-693.1.1.el7.x86_64, operatingsystem=Red Hat Enterprise Linux, ostype=linux, storagedriver=devicemapper
  └ UpdatedAt: 2017-08-30T04:31:54Z
  └ ServerVersion: 17.06.1-ee-1
 DEE-Wrk-C-1.cisco.com: 10.65.121.124:12376
  └ ID: 6DTE:3DBB:NGYV:Z6UY:WZKA:MSGX:BMM7:4HRS:5DSW:ZX6A:V7AM:XOMO|10.65.121.124:12376
  └ Status: Healthy
  └ Containers: 8 (3 Running, 0 Paused, 5 Stopped)
  └ Reserved CPUs: 0 / 92
  └ Reserved Memory: 0 B / 264.2 GiB
  └ Labels: kernelversion=3.10.0-693.1.1.el7.x86_64, operatingsystem=Red Hat Enterprise Linux, ostype=linux, storagedriver=devicemapper
  └ UpdatedAt: 2017-08-30T04:31:54Z
  └ ServerVersion: 17.06.1-ee-1
Cluster Managers: 3
 DEE-Ctrl-C-2.cisco.com: Healthy
  └ Orca Controller: https://10.65.121.122:4443
  └ Classic Swarm Manager: tcp://10.65.121.122:2376
  └ Engine Swarm Manager: tcp://10.65.121.122:12376
  └ KV: etcd://10.65.121.122:12379
 DEE-Ctrl-C-1.cisco.com: Healthy
  └ Orca Controller: https://10.65.121.121:4443
  └ Classic Swarm Manager: tcp://10.65.121.121:2376
  └ Engine Swarm Manager: tcp://10.65.121.121:12376
  └ KV: etcd://10.65.121.121:12379
 DEE-Ctrl-C-3.cisco.com: Healthy
  └ Orca Controller: https://10.65.121.123:4443
  └ Classic Swarm Manager: tcp://10.65.121.123:2376
  └ Engine Swarm Manager: tcp://10.65.121.123:12376
  └ KV: etcd://10.65.121.123:12379
Plugins:
 Volume:
 Network:
 Log:
Swarm: active
 NodeID: j5093lckl3pyqom8cgukt1u2m
 Is Manager: true
 ClusterID: q2cwkavd2zh49qapd3mg3ak91
 Managers: 3
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
  External CAs:
    cfssl: https://10.65.121.121:12381/api/v1/cfssl/sign
    cfssl: https://10.65.121.122:12381/api/v1/cfssl/sign
    cfssl: https://10.65.121.123:12381/api/v1/cfssl/sign
 Root Rotation In Progress: false
 Node Address: 10.65.121.121
 Manager Addresses:
  10.65.121.121:2377
  10.65.121.122:2377
  10.65.121.123:2377
Kernel Version: 3.10.0-693.1.1.el7.x86_64
Operating System: linux
Architecture: amd64
CPUs: 368
Total Memory: 1.032TiB
Name: ucp-controller-10.65.121.121
ID: q2cwkavd2zh49qapd3mg3ak91
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 com.docker.ucp.license_key=wasvIv_S3w_xAfArYYf31vO6TIXfzD31M0gStiRLSOS5
 com.docker.ucp.license_max_engines=20
 com.docker.ucp.license_expires=2018-01-06 23:47:53 +0000 UTC
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No kernel memory limit support

2). DEE engine is in healthy state -

[root@NFS ansible]# ansible DEE-C-Nodes -m shell -a "systemctl status docker.service"
DEE-Ctrl-C-1 | SUCCESS | rc=0 >>
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─http-proxy.conf
   Active: active (running) since Wed 2017-08-30 09:54:12 IST; 26min ago
     Docs: https://docs.docker.com
 Main PID: 2146 (dockerd)
   Memory: 436.0M
   CGroup: /system.slice/docker.service
           ├─ 2146 /usr/bin/dockerd
           ├─ 2560 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc
           ├─ 5044 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12387 -container-ip 172.17.0.3 -container-port 12387
           ├─ 5051 docker-containerd-shim 4dc4d8b8133bf219d4454647f0a22b1643f48ab9c3a00557a5802290dd960430 /var/run/docker/libcontainerd/4dc4d8b8133bf219d4454647f0a22b1643f48ab9c3a00557a5802290dd960430 docker-runc
           ├─ 5169 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 2376 -container-ip 172.17.0.4 -container-port 2375
           ├─ 5183 docker-containerd-shim 8fd23491ef9be17652c35bc0e5f6d41986b914ece7eb0868fa7fc9be12c4b42e /var/run/docker/libcontainerd/8fd23491ef9be17652c35bc0e5f6d41986b914ece7eb0868fa7fc9be12c4b42e docker-runc
           ├─ 5412 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12380 -container-ip 172.17.0.5 -container-port 12380
           ├─ 5425 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12379 -container-ip 172.17.0.5 -container-port 2379
           ├─ 5443 docker-containerd-shim f20863436d46740e1496687c0c8074378119a3db395c7d258844bf7df26a3976 /var/run/docker/libcontainerd/f20863436d46740e1496687c0c8074378119a3db395c7d258844bf7df26a3976 docker-runc
           ├─ 5553 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12376 -container-ip 172.17.0.6 -container-port 2376
           ├─ 5565 docker-containerd-shim 0b45be0548876d2dc347613c8116c1217f5cab014191445d0102b49a9310f976 /var/run/docker/libcontainerd/0b45be0548876d2dc347613c8116c1217f5cab014191445d0102b49a9310f976 docker-runc
           ├─ 5681 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12381 -container-ip 172.17.0.2 -container-port 12381
           ├─ 5703 docker-containerd-shim ece907882c62935077f7df176d32de7b521c378dfcad1b0fb697faccf1ac3904 /var/run/docker/libcontainerd/ece907882c62935077f7df176d32de7b521c378dfcad1b0fb697faccf1ac3904 docker-runc
           ├─ 5781 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 4443 -container-ip 172.17.0.7 -container-port 8080
           ├─ 5793 docker-containerd-shim 64fa932be0d78e234d3c5098e85282155f22efac2a565229ddd679b914c18742 /var/run/docker/libcontainerd/64fa932be0d78e234d3c5098e85282155f22efac2a565229ddd679b914c18742 docker-runc
           ├─ 5881 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12382 -container-ip 172.17.0.8 -container-port 12382
           ├─ 5889 docker-containerd-shim e0ff88d40fff667a4a9e3fb0dec1e610443e4bfc598ec4653592b3101e49184b /var/run/docker/libcontainerd/e0ff88d40fff667a4a9e3fb0dec1e610443e4bfc598ec4653592b3101e49184b docker-runc
           ├─ 5997 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12384 -container-ip 172.17.0.9 -container-port 12384
           ├─ 6010 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12383 -container-ip 172.17.0.9 -container-port 12383
           ├─ 6016 docker-containerd-shim 8bfbf1881b7945652b446736c71cc3679bc613923e75474dedbce90d2bedd90c /var/run/docker/libcontainerd/8bfbf1881b7945652b446736c71cc3679bc613923e75474dedbce90d2bedd90c docker-runc
           ├─ 9224 docker-containerd-shim afd826b68302d12e470d1d505c5b213832f5d2448629127a5e09b96d566f6d21 /var/run/docker/libcontainerd/afd826b68302d12e470d1d505c5b213832f5d2448629127a5e09b96d566f6d21 docker-runc
           ├─ 9456 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12386 -container-ip 172.17.0.10 -container-port 4443
           ├─ 9487 docker-containerd-shim 5d925e59374b6e08fa55e5238ba5730e2a84c075ba887929c008bb380e79a947 /var/run/docker/libcontainerd/5d925e59374b6e08fa55e5238ba5730e2a84c075ba887929c008bb380e79a947 docker-runc
           ├─ 9556 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12385 -container-ip 172.17.0.11 -container-port 4443
           ├─ 9563 docker-containerd-shim 584ed4360bc7b07f1122a3ee5bd2b769da75046934bcf175bd9fd778aa6bb145 /var/run/docker/libcontainerd/584ed4360bc7b07f1122a3ee5bd2b769da75046934bcf175bd9fd778aa6bb145 docker-runc
           ├─ 9792 docker-containerd-shim 2693a61ff3502437a8c2e1d084fab41a41f13c4ceb28eb7e2e2d5abb19e67c18 /var/run/docker/libcontainerd/2693a61ff3502437a8c2e1d084fab41a41f13c4ceb28eb7e2e2d5abb19e67c18 docker-runc
           └─28507 docker-containerd-shim d3b93bd088b0db1f04682788ed51e8423d392cd246dcc32d0f6630641ced8965 /var/run/docker/libcontainerd/d3b93bd088b0db1f04682788ed51e8423d392cd246dcc32d0f6630641ced8965 docker-runc

3). `docker plugin ls` - shows netplugin in disable state -

[root@DEE-Ctrl-C-1 contiv]# docker plugin ls
ID                  NAME                    DESCRIPTION                        ENABLED
785a6f234864        contiv/v2plugin:1.1.1   Contiv network plugin for Docker   false

4). `etcdctl` cluster-health in bad state -

[root@DEE-Ctrl-C-2 ~]# etcdctl cluster-health
failed to check the health of member 4e4cc7333b64318a on http://10.65.121.121:2379: Get http://10.65.121.121:2379/health: dial tcp 10.65.121.121:2379: getsockopt: no route to host
failed to check the health of member 4e4cc7333b64318a on http://10.65.121.121:4001: Get http://10.65.121.121:4001/health: dial tcp 10.65.121.121:4001: getsockopt: no route to host
member 4e4cc7333b64318a is unreachable: [http://10.65.121.121:2379 http://10.65.121.121:4001] are all unreachable
failed to check the health of member 7bccc8ff27427e84 on http://10.65.121.123:2379: Get http://10.65.121.123:2379/health: dial tcp 10.65.121.123:2379: i/o timeout
failed to check the health of member 7bccc8ff27427e84 on http://10.65.121.123:4001: Get http://10.65.121.123:4001/health: dial tcp 10.65.121.123:4001: getsockopt: no route to host
member 7bccc8ff27427e84 is unreachable: [http://10.65.121.123:2379 http://10.65.121.123:4001] are all unreachable
member fce99a86a2b6a6f7 is unhealthy: got unhealthy result from http://10.65.121.122:2379
cluster is unhealthy

5). `netctl` commands are failing -

[root@DEE-Ctrl-C-1 contiv]# netctl tenant ls
ERRO[0000] Get http://netmaster:9999/api/v1/tenants/: dial tcp 127.0.0.1:9999: getsockopt: connection refused
[root@DEE-Ctrl-C-1 contiv]# netctl network ls -a
ERRO[0000] Get http://netmaster:9999/api/v1/tenants/default/: dial tcp 127.0.0.1:9999: getsockopt: connection refused

## Steps to Reproduce (for bugs)

1. Create swarm cluster with DEE-17.06 bits 
2. Install Contiv in L2-vLan mode
3. Create tenant/network and docker network with contiv-tag and v2Plugin driver defined
4. Deploy `docker service` using contiv network
5. verify the connectivity
6. Reboot all 4 nodes at-ones

## Your Environment

* netctl version - 1.1.1
* Orchestrator version (e.g. kubernetes, mesos, swarm) - swarm/UCP-17.06
* Operating System and version - RHEL7.3 Bare Metal

Logs are attached herewith.
[Ctrl-1-contiv.tar.gz](https://github.com/contiv/netplugin/files/1262460/Ctrl-1-contiv.tar.gz)
[Ctrl-2-contiv.tar.gz](https://github.com/contiv/netplugin/files/1262459/Ctrl-2-contiv.tar.gz)
[Ctrl-3-contiv.tar.gz](https://github.com/contiv/netplugin/files/1262461/Ctrl-3-contiv.tar.gz)

**Comment by rkharya** [comment]
We are still seeing etcd cluster health issues on our setup when we do a cluster reboot. We installed 1.1.4 afresh on a 4 node cluster and rebooted the cluster at once using `reboot` command issued through Ansible. Once nodes comes back, we see following -

1). etcd cluster-health -
root@NFS ~]# ansible DEE-C-Nodes -m shell -a "etcdctl cluster-health"
DEE-Ctrl-C-2 | FAILED | rc=5 >>
member 4e4cc7333b64318a is unreachable: no available published client urls
member 7bccc8ff27427e84 is unreachable: no available published client urls
member fce99a86a2b6a6f7 is unreachable: no available published client urls
cluster is unhealthy

DEE-Ctrl-C-1 | FAILED | rc=5 >>
member 4e4cc7333b64318a is unreachable: no available published client urls
member 7bccc8ff27427e84 is unreachable: no available published client urls
member fce99a86a2b6a6f7 is unreachable: no available published client urls
cluster is unhealthy

DEE-Ctrl-C-3 | FAILED | rc=5 >>
member 4e4cc7333b64318a is unreachable: no available published client urls
member 7bccc8ff27427e84 is unreachable: no available published client urls
member fce99a86a2b6a6f7 is unreachable: no available published client urls
cluster is unhealthy

DEE-Wrk-C-1 | FAILED | rc=4 >>
cluster may be unhealthy: failed to list membersError:  client: etcd cluster is unavailable or misconfigured
error #0: client: etcd member http://127.0.0.1:2379 has no leader
error #1: client: etcd member http://127.0.0.1:4001 has no leader

2) Contiv plugin gets disabled as before -
[root@NFS ~]# ansible DEE-C-Nodes -m shell -a "docker plugin ls"
DEE-Ctrl-C-1 | SUCCESS | rc=0 >>
ID                  NAME                    DESCRIPTION                        ENABLED
727fb4a3f452        contiv/v2plugin:1.1.4   Contiv network plugin for Docker   false

DEE-Wrk-C-1 | SUCCESS | rc=0 >>
ID                  NAME                    DESCRIPTION                        ENABLED
4fcf156dea28        contiv/v2plugin:1.1.4   Contiv network plugin for Docker   false

DEE-Ctrl-C-2 | SUCCESS | rc=0 >>
ID                  NAME                    DESCRIPTION                        ENABLED
5b5ecdc5d192        contiv/v2plugin:1.1.4   Contiv network plugin for Docker   false

DEE-Ctrl-C-3 | SUCCESS | rc=0 >>
ID                  NAME                    DESCRIPTION                        ENABLED
15d9ad3c7fed        contiv/v2plugin:1.1.4   Contiv network plugin for Docker   false

3). iptables INPUT rules doesn't have contiv entries any more -

[root@NFS ~]# ansible DEE-C-Nodes -m shell -a "iptables -L INPUT"
DEE-Wrk-C-1 | SUCCESS | rc=0 >>
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:bootps
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
INPUT_direct  all  --  anywhere             anywhere
INPUT_ZONES_SOURCE  all  --  anywhere             anywhere
INPUT_ZONES  all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

DEE-Ctrl-C-1 | SUCCESS | rc=0 >>
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:bootps
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
INPUT_direct  all  --  anywhere             anywhere
INPUT_ZONES_SOURCE  all  --  anywhere             anywhere
INPUT_ZONES  all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

DEE-Ctrl-C-2 | SUCCESS | rc=0 >>
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:bootps
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
INPUT_direct  all  --  anywhere             anywhere
INPUT_ZONES_SOURCE  all  --  anywhere             anywhere
INPUT_ZONES  all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

DEE-Ctrl-C-3 | SUCCESS | rc=0 >>
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:bootps
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
INPUT_direct  all  --  anywhere             anywhere
INPUT_ZONES_SOURCE  all  --  anywhere             anywhere
INPUT_ZONES  all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

System can be accessed for live debugging. Contiv logs from netmaster primary node is attached herewith -

[dee-ctrl-C-1.tar.gz](https://github.com/contiv/netplugin/files/1371677/dee-ctrl-C-1.tar.gz)

**Comment by chrisplo** [comment]
Two PRs address this issue:
https://github.com/contiv/ansible/pull/376
https://github.com/contiv/ansible/pull/380

**Comment by blaksmit** [comment]
Rajesh is still reporting this issue. He needs to verify further. Reopening until he has verified.
