### ISSUE TITLE
IPAM should not allocate the first IP address and last address! 

### ISSUE THREAD

**Issue by jiangsuwwj1** [contiv/netplugin#964]
In my environment,  configuration is as follows, In availableIPAddresses the first address 192.168.0.0 and the last address 192.168.0.255 should not be allocated, but it does.

root@localhost ~]# netctl net inspect vlan-66
{
  "Config": {
    "key": "default:vlan-66",
    "encap": "vlan",
    "gateway": "192.168.0.252",
    "networkName": "vlan-66",
    "nwType": "data",
    "pktTag": 66,
    "subnet": "192.168.0.0/24",
    "tenantName": "default",
    "link-sets": {
      "EndpointGroups": {
        "default:epgA": {
          "type": "endpointGroup",
          "key": "default:epgA"
        }
      }
    },
    "links": {
      "Tenant": {
        "type": "tenant",
        "key": "default"
      }
    }
  },
  "Oper": {
    "allocatedAddressesCount": 11,
    "availableIPAddressesCount": 243,
    "allocatedIPAddresses": "192.168.0.1-192.168.0.5, 192.168.0.10-192.168.0.12, 192.168.0.15, 192.168.0.252, 192.168.0.254",
    "availableIPAddresses": "192.168.0.0, 192.168.0.6-192.168.0.9, 192.168.0.13-192.168.0.14, 192.168.0.16-192.168.0.251, 192.168.0.253, 192.168.0.255",
    "networkTag": "vlan-66.default",
    "numEndpoints": 7,
    "pktTag": 66
  }

**Comment by rchirakk** [comment]
IPAM doesn't allocate first/last ip address.

**Comment by jiangsuwwj1** [comment]
In my env , it appeared.  

My resolve solution is :
In netutils.go    modify NextClear method as bellow:

// NextClear wrapper around Bitset to check max id
func NextClear(allocMap bitset.BitSet, idx uint, subnetLen uint) (uint, bool) {
	maxHosts := uint(1 << (32 - subnetLen))
	for {
		value, found := allocMap.NextClear(idx)
		if found && value == 0 {
			idx = value + 1
			continue
		}

		if found && value >= maxHosts-1 {
			return 0, false
		}

		return value, found
	}
}
