### ISSUE TITLE
Restarting Docker Engine renders Contiv plugin in failed state 

### ISSUE THREAD

**Issue by rkharya** [contiv/netplugin#974]
## Description
Docker Engine restart on one of the manager node of a 10 node working swarm+contiv cluster, makes Contiv netplugin in disabled state. Manually enabling the plugin using `docker plugin enable` also does not helps.

#### Expected Behavior
Docker Engine restart should not result in Contiv plugin failuers, in coming up gracefully.

#### Observed Behavior
Restarting Docker Engine on one of the Contiv master node results in Contiv netplugin failuers on that nodes -
- docker plugin ls shows contiv netplugin enabled state to `false`
- etcd cluster becomes un-healthy
- Docker Engine comes up cleanly, swarm cluster is healthy
- Docker Service runs w/o any issues, and containers moved to healthy nodes cleanly

## Steps to Reproduce (for bugs)
1. Bring up Docker Swarm cluster
2. Bring up Contiv on the cluster with 3 mastars and rest as worker nodes
3. Create Contiv tenant, network, policy, group etc
4. Create Docker network using Contiv as back-end provider network
5. Spawn Docker service and associated containers
6. Restart Docker Engine on one of the master nodes

## Your Environment

* netctl - v2plugin - 1.1.1
* Orchestrator version (e.g. kubernetes, mesos, swarm): UCP2.2.2/Nativ Swarm mode
* Operating System and version - RHEL 7.3

Logs from DEE-Ctrl-3 where Docker Engine was restarted, attached herewith.

**Comment by rkharya** [comment]
[DEE-Ctrl-3.tar.gz](https://github.com/contiv/netplugin/files/1305327/DEE-Ctrl-3.tar.gz)

**Comment by rkharya** [comment]
Initial de-bug info -

1) Iptables INPUT rules are intact -

[root@DEE-Ctrl-3 contiv]# iptables -L INPUT
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ndmp /* Contiv auth proxy service (10000) */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:otv /* contiv network traffic (8472) */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:bgp /* contiv network traffic (179) */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:webcache /* contiv network traffic (8080) */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:distinct /* contiv network traffic (9999) */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:9003 /* contiv network traffic (9003) */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:dynamid /* contiv network traffic (9002) */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:etlservicemgr /* contiv network traffic (9001) */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:afs3-callback /* etcd traffic (7001) */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:2380 /* etcd traffic (2380) */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:newoak /* etcd traffic (4001) */
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:2379 /* etcd traffic (2379) */
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:bootps
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
INPUT_direct  all  --  anywhere             anywhere
INPUT_ZONES_SOURCE  all  --  anywhere             anywhere
INPUT_ZONES  all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere             ctstate INVALID
REJECT     all  --  anywhere             anywhere             reject-with icmp-host-prohibited

2) plugin re-start, manual way did not helped -

[root@DEE-Ctrl-3 log]# docker plugin ls
ID                  NAME                    DESCRIPTION                        ENABLED
42e597c38833        contiv/v2plugin:1.1.1   Contiv network plugin for Docker   false

[root@DEE-Ctrl-3 log]# docker plugin enable contiv/v2plugin:1.1.1
Error response from daemon: dial unix /run/docker/plugins/42e597c3883303fafecde655e406717d8ae04f6497082db90c345fc1c7bf4521/netplugin.sock: connect: no such file or directory

3) etcd service is in failed state -

[root@DEE-Ctrl-3 log]# systemctl status -l 100 etcd.service
Failed to get unit for PID 100: PID 100 does not belong to any loaded unit.
● etcd.service - Etcd
   Loaded: loaded (/etc/systemd/system/etcd.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2017-09-15 10:28:16 IST; 5s ago
  Process: 27801 ExecStop=/usr/bin/etcd.sh stop (code=exited, status=1/FAILURE)
  Process: 27496 ExecStart=/usr/bin/etcd.sh start (code=exited, status=0/SUCCESS)
 Main PID: 27496 (code=exited, status=0/SUCCESS)
   Memory: 0B
   CGroup: /system.slice/etcd.service

Sep 15 10:28:16 DEE-Ctrl-3.cisco.com systemd[1]: etcd.service: control process exited, code=exited status=1
Sep 15 10:28:16 DEE-Ctrl-3.cisco.com systemd[1]: Unit etcd.service entered failed state.
Sep 15 10:28:16 DEE-Ctrl-3.cisco.com systemd[1]: etcd.service failed.

4) Restart of etcd cluster did not helped either -

[root@DEE-Ctrl-3 log]# systemctl start etcd.service
[root@DEE-Ctrl-3 log]# systemctl status -l 100 etcd.service
Failed to get unit for PID 100: PID 100 does not belong to any loaded unit.
● etcd.service - Etcd
   Loaded: loaded (/etc/systemd/system/etcd.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-09-15 10:28:40 IST; 1s ago
  Process: 28390 ExecStop=/usr/bin/etcd.sh stop (code=exited, status=1/FAILURE)
 Main PID: 28632 (etcd.sh)
   Memory: 1.6M
   CGroup: /system.slice/etcd.service
           ├─28632 /bin/bash /usr/bin/etcd.sh start
           └─28680 sleep 10s

Sep 15 10:28:40 DEE-Ctrl-3.cisco.com etcd.sh[28632]: + peers=,10.65.122.62,10.65.122.62
Sep 15 10:28:40 DEE-Ctrl-3.cisco.com etcd.sh[28632]: + peers=10.65.122.62,10.65.122.62
Sep 15 10:28:40 DEE-Ctrl-3.cisco.com etcd.sh[28632]: + '[' 10.65.122.62,10.65.122.62 == '' ']'
Sep 15 10:28:40 DEE-Ctrl-3.cisco.com etcd.sh[28632]: ++ echo 10.65.122.62,10.65.122.62
Sep 15 10:28:40 DEE-Ctrl-3.cisco.com etcd.sh[28632]: ++ awk -F, '{print $1}'
Sep 15 10:28:40 DEE-Ctrl-3.cisco.com etcd.sh[28632]: + peer=10.65.122.62
Sep 15 10:28:40 DEE-Ctrl-3.cisco.com etcd.sh[28632]: + add_member 10.65.122.62
Sep 15 10:28:40 DEE-Ctrl-3.cisco.com etcd.sh[28632]: + res=1
Sep 15 10:28:40 DEE-Ctrl-3.cisco.com etcd.sh[28632]: + for i in '{1..10}'
Sep 15 10:28:40 DEE-Ctrl-3.cisco.com etcd.sh[28632]: + sleep 10s

[root@DEE-Ctrl-3 log]# systemctl status -l 100 etcd.service
Failed to get unit for PID 100: PID 100 does not belong to any loaded unit.
● etcd.service - Etcd
   Loaded: loaded (/etc/systemd/system/etcd.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-09-15 10:28:40 IST; 11s ago
  Process: 28390 ExecStop=/usr/bin/etcd.sh stop (code=exited, status=1/FAILURE)
 Main PID: 28632 (etcd.sh)
   Memory: 7.4M
   CGroup: /system.slice/etcd.service
           ├─28632 /bin/bash /usr/bin/etcd.sh start
           └─29055 /usr/bin/docker run -t --rm --net=host --name etcd -v /var/lib/etcd:/var/lib/etcd -e ETCD_NAME=node2 -e ETCD_DATA_DIR=/var/lib/etcd -e ETCD_INITIAL_CLUSTER_TOKEN=contiv-cluster -e ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001 -e ETCD_ADVERTISE_CLIENT_URLS=http://10.65.122.63:2379,http://10.65.122.63:4001 -e ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.65.122.63:2380,http://10.65.122.63:7001 -e ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 -e ETCD_HEARTBEAT_INTERVAL=1000 -e ETCD_ELECTION_TIMEOUT=10000 -e ETCD_INITIAL_CLUSTER=node3=http://10.65.122.62:2380,node3=http://10.65.122.62:7001,node1=http://10.65.122.61:2380,node1=http://10.65.122.61:7001,node2=http://10.65.122.63:2380 -e ETCD_INITIAL_CLUSTER_STATE=existing -e ETCD_PROXY= quay.io/coreos/etcd:v2.3.8

Sep 15 10:28:50 DEE-Ctrl-3.cisco.com etcd.sh[28632]: ++ awk -F ETCD_ '{print "ETCD_"$2 "ETCD_"$3 "ETCD_"$4}'
Sep 15 10:28:50 DEE-Ctrl-3.cisco.com etcd.sh[28632]: ++ sed 's/"//g'
Sep 15 10:28:50 DEE-Ctrl-3.cisco.com etcd.sh[28632]: + export ETCD_NAME=node2 ETCD_INITIAL_CLUSTER=node3=http://10.65.122.62:2380,node3=http://10.65.122.62:7001,node1=http://10.65.122.61:2380,node1=http://10.65.122.61:7001,node2=http://10.65.122.63:2380 ETCD_INITIAL_CLUSTER_STATE=existing
Sep 15 10:28:50 DEE-Ctrl-3.cisco.com etcd.sh[28632]: + ETCD_NAME=node2
Sep 15 10:28:50 DEE-Ctrl-3.cisco.com etcd.sh[28632]: + ETCD_INITIAL_CLUSTER=node3=http://10.65.122.62:2380,node3=http://10.65.122.62:7001,node1=http://10.65.122.61:2380,node1=http://10.65.122.61:7001,node2=http://10.65.122.63:2380
Sep 15 10:28:50 DEE-Ctrl-3.cisco.com etcd.sh[28632]: + ETCD_INITIAL_CLUSTER_STATE=existing
Sep 15 10:28:50 DEE-Ctrl-3.cisco.com etcd.sh[28632]: ++ env
Sep 15 10:28:50 DEE-Ctrl-3.cisco.com etcd.sh[28632]: + echo '==> starting etcd with environment:' ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.65.122.63:2380,http://10.65.122.63:7001 ETCD_INITIAL_CLUSTER_STATE=existing ETCD_INITIAL_CLUSTER=node3=http://10.65.122.62:2380,node3=http://10.65.122.62:7001,node1=http://10.65.122.61:2380,node1=http://10.65.122.61:7001,node2=http://10.65.122.63:2380 ETCD_ELECTION_TIMEOUT=10000 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin PWD=/ ETCD_INITIAL_CLUSTER_TOKEN=contiv-cluster LANG=en_US.UTF-8 ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 SHLVL=1 ETCD_NAME=node2 ETCD_ADVERTISE_CLIENT_URLS=http://10.65.122.63:2379,http://10.65.122.63:4001 ETCD_DATA_DIR=/var/lib/etcd ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001 ETCD_HEARTBEAT_INTERVAL=1000 _=/usr/bin/env
Sep 15 10:28:50 DEE-Ctrl-3.cisco.com etcd.sh[28632]: ==> starting etcd with environment: ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.65.122.63:2380,http://10.65.122.63:7001 ETCD_INITIAL_CLUSTER_STATE=existing ETCD_INITIAL_CLUSTER=node3=http://10.65.122.62:2380,node3=http://10.65.122.62:7001,node1=http://10.65.122.61:2380,node1=http://10.65.122.61:7001,node2=http://10.65.122.63:2380 ETCD_ELECTION_TIMEOUT=10000 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin PWD=/ ETCD_INITIAL_CLUSTER_TOKEN=contiv-cluster LANG=en_US.UTF-8 ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 SHLVL=1 ETCD_NAME=node2 ETCD_ADVERTISE_CLIENT_URLS=http://10.65.122.63:2379,http://10.65.122.63:4001 ETCD_DATA_DIR=/var/lib/etcd ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001 ETCD_HEARTBEAT_INTERVAL=1000 _=/usr/bin/env
Sep 15 10:28:50 DEE-Ctrl-3.cisco.com etcd.sh[28632]: + /usr/bin/docker run -t --rm --net=host --name etcd -v /var/lib/etcd:/var/lib/etcd -e ETCD_NAME=node2 -e ETCD_DATA_DIR=/var/lib/etcd -e ETCD_INITIAL_CLUSTER_TOKEN=contiv-cluster -e ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001 -e ETCD_ADVERTISE_CLIENT_URLS=http://10.65.122.63:2379,http://10.65.122.63:4001 -e ETCD_INITIAL_ADVERTISE_PEER_URLS=http://10.65.122.63:2380,http://10.65.122.63:7001 -e ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 -e ETCD_HEARTBEAT_INTERVAL=1000 -e ETCD_ELECTION_TIMEOUT=10000 -e ETCD_INITIAL_CLUSTER=node3=http://10.65.122.62:2380,node3=http://10.65.122.62:7001,node1=http://10.65.122.61:2380,node1=http://10.65.122.61:7001,node2=http://10.65.122.63:2380 -e ETCD_INITIAL_CLUSTER_STATE=existing -e ETCD_PROXY= quay.io/coreos/etcd:v2.3.8

5) Docker engine is running ok -

[root@DEE-Ctrl-3 log]# systemctl status -l docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─http-proxy.conf
   Active: active (running) since Fri 2017-09-15 10:20:25 IST; 32min ago
     Docs: https://docs.docker.com
 Main PID: 5278 (dockerd)
   Memory: 485.8M
   CGroup: /system.slice/docker.service
           ├─5278 /usr/bin/dockerd
           ├─5290 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc
           ├─5976 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12376 -container-ip 172.17.0.2 -container-port 2376
           ├─6000 docker-containerd-shim 8218b020653e3f7a88b48e320874577df0181d450c94bf4a9142ec3ae3c0a244 /var/run/docker/libcontainerd/8218b020653e3f7a88b48e320874577df0181d450c94bf4a9142ec3ae3c0a244 docker-runc
           ├─6076 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12387 -container-ip 172.17.0.4 -container-port 12387
           ├─6194 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12382 -container-ip 172.17.0.5 -container-port 12382
           ├─6221 docker-containerd-shim d44987763e18a10320cb948b5a5f3d3a14cd212491dc431036dbd5da321c3f5a /var/run/docker/libcontainerd/d44987763e18a10320cb948b5a5f3d3a14cd212491dc431036dbd5da321c3f5a docker-runc
           ├─6296 docker-containerd-shim 70ec94c05067083cae898bd4648eeb0f8c54961724be6017aac572df607ac430 /var/run/docker/libcontainerd/70ec94c05067083cae898bd4648eeb0f8c54961724be6017aac572df607ac430 docker-runc
           ├─6385 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 443 -container-ip 172.17.0.6 -container-port 8080
           ├─6415 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12380 -container-ip 172.17.0.7 -container-port 12380
           ├─6436 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12379 -container-ip 172.17.0.7 -container-port 2379
           ├─6470 docker-containerd-shim ef690b414d8bed32e6374ccbb27d4a325d257d8bcd553050fad82fa54ee46454 /var/run/docker/libcontainerd/ef690b414d8bed32e6374ccbb27d4a325d257d8bcd553050fad82fa54ee46454 docker-runc
           ├─6520 docker-containerd-shim add1ce47d75d3646a35d7b04036dfc284d76036955fdb82b824ec1d959214f44 /var/run/docker/libcontainerd/add1ce47d75d3646a35d7b04036dfc284d76036955fdb82b824ec1d959214f44 docker-runc
           ├─6672 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12384 -container-ip 172.17.0.9 -container-port 12384
           ├─6698 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12383 -container-ip 172.17.0.9 -container-port 12383
           ├─6733 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 2376 -container-ip 172.17.0.3 -container-port 2375
           ├─6808 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12381 -container-ip 172.17.0.10 -container-port 12381
           ├─6848 docker-containerd-shim 6fb81d6a28a980586dd87e2316f72a3388db631951a5362d622e9e2be2dcc82f /var/run/docker/libcontainerd/6fb81d6a28a980586dd87e2316f72a3388db631951a5362d622e9e2be2dcc82f docker-runc
           ├─6870 docker-containerd-shim 49889e42f321ba5b8df470e8de830f3e3004743492d53fe2dbbe84fe00b21a3a /var/run/docker/libcontainerd/49889e42f321ba5b8df470e8de830f3e3004743492d53fe2dbbe84fe00b21a3a docker-runc
           ├─7006 docker-containerd-shim c12cc67998838f61502d8d44e52658737c847c3f47112b19368980867d1d1c74 /var/run/docker/libcontainerd/c12cc67998838f61502d8d44e52658737c847c3f47112b19368980867d1d1c74 docker-runc
           ├─7399 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12386 -container-ip 172.17.0.11 -container-port 4443
           ├─7407 docker-containerd-shim 8624eac221714c4e979770c6c96e1509eaec93623c5fdf6a6658f853edaf334e /var/run/docker/libcontainerd/8624eac221714c4e979770c6c96e1509eaec93623c5fdf6a6658f853edaf334e docker-runc
           ├─7511 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12385 -container-ip 172.17.0.8 -container-port 4443
           ├─7522 docker-containerd-shim d85bb91311327e0aed692ee0e3af002cd3f55712eba7a10269554a206a6a511b /var/run/docker/libcontainerd/d85bb91311327e0aed692ee0e3af002cd3f55712eba7a10269554a206a6a511b docker-runc
           └─8029 docker-containerd-shim 2d6fe88415cfa1132559a3d5a757f15248a5531d3d6ac37c091c4ee453d23860 /var/run/docker/libcontainerd/2d6fe88415cfa1132559a3d5a757f15248a5531d3d6ac37c091c4ee453d23860 docker-runc

Sep 15 10:49:46 DEE-Ctrl-3.cisco.com dockerd[5278]: time="2017-09-15T10:49:46.312707766+05:30" level=info msg="Node join event for DEE-DTR-3.cisco.com-f0f97a28ccfe/10.65.122.66"
Sep 15 10:50:04 DEE-Ctrl-3.cisco.com dockerd[5278]: time="2017-09-15T10:50:04.841913320+05:30" level=info msg="Node join event for DEE-DTR-3.cisco.com-f0f97a28ccfe/10.65.122.66"
Sep 15 10:50:13 DEE-Ctrl-3.cisco.com dockerd[5278]: time="2017-09-15T10:50:13.276542639+05:30" level=info msg="Node join event for DEE-Ctrl-1.cisco.com-3972622eb61f/10.65.122.61"
Sep 15 10:50:34 DEE-Ctrl-3.cisco.com dockerd[5278]: time="2017-09-15T10:50:34.843954080+05:30" level=info msg="Node join event for DEE-Ctrl-1.cisco.com-3972622eb61f/10.65.122.61"
Sep 15 10:50:42 DEE-Ctrl-3.cisco.com dockerd[5278]: time="2017-09-15T10:50:42.741051024+05:30" level=info msg="Node join event for DEE-Wrk-1.cisco.com-559aae50a7cb/10.65.122.67"
Sep 15 10:50:59 DEE-Ctrl-3.cisco.com dockerd[5278]: time="2017-09-15T10:50:59.254773565+05:30" level=info msg="Node join event for DEE-DTR-2.cisco.com-4dbd01d6169a/10.65.122.65"
Sep 15 10:51:04 DEE-Ctrl-3.cisco.com dockerd[5278]: time="2017-09-15T10:51:04.845576261+05:30" level=info msg="Node join event for DEE-Wrk-3.cisco.com-fc06d8e7c3a5/10.65.122.69"
Sep 15 10:51:34 DEE-Ctrl-3.cisco.com dockerd[5278]: time="2017-09-15T10:51:34.847698383+05:30" level=info msg="Node join event for DEE-Wrk-1.cisco.com-559aae50a7cb/10.65.122.67"
Sep 15 10:52:04 DEE-Ctrl-3.cisco.com dockerd[5278]: time="2017-09-15T10:52:04.850158479+05:30" level=info msg="Node join event for DEE-Wrk-4.cisco.com-d3658233554a/10.65.122.70"
Sep 15 10:52:34 DEE-Ctrl-3.cisco.com dockerd[5278]: time="2017-09-15T10:52:34.852997766+05:30" level=info msg="Node join event for DEE-DTR-1.cisco.com-70031d839e01/10.65.122.64"

**Comment by gkvijay** [comment]
After the docker engine restart, please do docker plugin disable followed by docker plugin enable and collect the plugin bootup log (/var/log/contiv/plugin_bootup.log)

**Comment by rkharya** [comment]
We further de-bugged the issue in detail and it looks there are 2 main issues -
1. restart of the contiv plugin, which upon engine restart does not start on its own. User has to do a manual start. For worker node manual restart works fine.
2. etcd cluster in failed state. This gets corrected if we remove /var/lib/etcd/membar/wal directory. After this, node on which engine was restarted, joins the same cluster as member cleanly. This in-turn also enable the contiv plugin successfully. But one has to do it manually. 

So issue #974 & #975 are essentially same and we need to fix plugin re-start issue. Etcd cluster issue is being handled through $963. 

Logs are attached herewith, as requested -

[DEE-Ctrl-1-after.tar.gz](https://github.com/contiv/netplugin/files/1309861/DEE-Ctrl-1-after.tar.gz)
[DEE-Ctrl-1-before.tar.gz](https://github.com/contiv/netplugin/files/1309862/DEE-Ctrl-1-before.tar.gz)

**Comment by g1rana** [comment]
issue is side effect of #963 should be closed after #963

**Comment by kahou82** [comment]
#963 is closed. Can we close this?
