### ISSUE TITLE
Restarting Docker Engine on a worker node puts the Contiv netplugin on the disabled state

### ISSUE THREAD

**Issue by sisudhir** [contiv/netplugin#975]
## Description
Our setup has a 10 node swarm cluster with 3 Contiv manager and 7 worker nodes. 
On restarting docker engine on worker node, we observed that the Contiv netplugin goes into a false state and we need to manually enable the plugin. 
Docker Engine restart may be required for many reasons like - upgrade of Engine, or restarting engine from error state, certificate updates etc.

#### Expected Behavior
Restarting docker engine should not affect the state of the Contiv plugin. User should not be enabling Contiv manually.

#### Observed Behavior
Restarting docker engine disables the Contiv plugin. Enabled state of plugin goes false.

## Steps to Reproduce (for bugs)
1. Need atleast one Contiv worker node with the Contiv netmasters in a Docker swarm cluster. 
2. Ensure Contiv plugin is in the enabled state - 'docker plugin ls'
3. Restart docker engine - 'systemctl restart docker.service'
4. Run 'docker plugin ls' to see the status - Now the plugin will be in be false state (which is not expected)
5. Manually enable the netplugin by running 'docker plugin enable contiv/v2plugin:1.1.1'

## Your Environment
* netctl version - v2plugin:1.1.1
* Orchestrator version (e.g. kubernetes, mesos, swarm): Docker UCP version 2.2.2/ Native Swarm mode
* Operating System and version - RHEL 7.3

**Comment by sisudhir** [comment]
1) State after restarting Docker Engine - 

[root@DEE-Wrk-1 ~]# docker plugin ls
ID                  NAME                    DESCRIPTION                        ENABLED
bed86ef2660d        contiv/v2plugin:1.1.1   Contiv network plugin for Docker   false

2) Manual start & successful state -

[root@DEE-Wrk-1 ~]# docker plugin enable contiv/v2plugin:1.1.1
contiv/v2plugin:1.1.1
[root@DEE-Wrk-1 ~]# docker plugin ls
ID                  NAME                    DESCRIPTION                        ENABLED
bed86ef2660d        contiv/v2plugin:1.1.1   Contiv network plugin for Docker   true

3) Docker service containers come up on the worker node using contiv network -  

[root@DEE-Wrk-1 ~]# docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                    PORTS                     NAMES
33691c89efdd        alpine:latest                "sleep 100000"           27 minutes ago      Up 27 minutes                                       contiv-alpine.5.vajc463m6igg65l2xvo2ai83t
402104419b20        docker/ucp-agent:2.2.2       "/bin/ucp-agent agent"   37 minutes ago      Up 37 minutes             2376/tcp                  ucp-agent.xs3cblkazrfo4hyy7o8blje19.icx8g5f85air051tp60qk63z5
3c3c5c3dadb5        quay.io/coreos/etcd:v2.3.8   "/etcd"                  37 minutes ago      Up 37 minutes                                       etcd
865fe4d57a49        docker/ucp-agent:2.2.2       "/bin/ucp-agent pr..."   2 weeks ago         Up 37 minutes (healthy)   0.0.0.0:12376->2376/tcp   ucp-proxy


Logs are attached herewith -

[DEE-Wrk-1.tar.gz](https://github.com/contiv/netplugin/files/1305378/DEE-Wrk-1.tar.gz)

**Comment by kahou82** [comment]
This can be closed once #974 is closed

**Comment by kahou82** [comment]
We still need this https://github.com/contiv/ansible/pull/368 before we close this issue.

**Comment by dseevr** [comment]
Closing now that https://github.com/contiv/ansible/pull/368 is merged

**Comment by sisudhir** [comment]
This issue seems to be persisting in the new 1.1.4 build as well - this build was supposed to have the fix for this issue. 
We still have to manually enable the v2plugin with `docker plugin enable contiv/v2plugin:1.1.4` after docker service restart.
Command details:
[root@DEE-Wrk-C-1 ~]# systemctl restart docker.service
[root@DEE-Wrk-C-1 ~]# docker plugin ls
ID                  NAME                    DESCRIPTION                        ENABLED
4fcf156dea28        contiv/v2plugin:1.1.4   Contiv network plugin for Docker   false

[root@DEE-Wrk-C-1 ~]# systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─http-proxy.conf
   Active: active (running) since Tue 2017-10-10 15:46:49 IST; 20min ago
     Docs: https://docs.docker.com
 Main PID: 15732 (dockerd)
   Memory: 255.9M
   CGroup: /system.slice/docker.service
           ├─15732 /usr/bin/dockerd
           ├─15747 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2...
           ├─16196 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 12376 -container-ip 172.17.0.2 -container-port 2376
           ├─16203 docker-containerd-shim 7b25b12329cc2f4f3ef526f7780697190972bc8e0f42706630ff4c8d651fd010 /var/run/docker/libcontainerd/7...
           ├─16628 docker-containerd-shim 4c38254aeaff22798f72b3def0986435df3089ed331d015dae2bb54fa2483963 /var/run/docker/libcontainerd/4...
           └─16705 docker-containerd-shim 084d1bed983b44684247ba39690221434b73286fa3d8324576cae30c205b8130 /var/run/docker/libcontainerd/0...

Oct 10 16:05:31 DEE-Wrk-C-1.cisco.com dockerd[15732]: time="2017-10-10T16:05:31.435980147+05:30" level=error msg="Handler for GET /v1.24/n...
Oct 10 16:05:32 DEE-Wrk-C-1.cisco.com dockerd[15732]: time="2017-10-10T16:05:32.879648858+05:30" level=info msg="Node join event for...1.122"
Oct 10 16:06:02 DEE-Wrk-C-1.cisco.com dockerd[15732]: time="2017-10-10T16:06:02.880495707+05:30" level=info msg="Node join event for...1.121"
Oct 10 16:06:15 DEE-Wrk-C-1.cisco.com dockerd[15732]: time="2017-10-10T16:06:15.912008177+05:30" level=info msg="Node join event for...1.123"
Oct 10 16:06:31 DEE-Wrk-C-1.cisco.com dockerd[15732]: time="2017-10-10T16:06:31.437980859+05:30" level=error msg="Error getting node...ager."
Oct 10 16:06:31 DEE-Wrk-C-1.cisco.com dockerd[15732]: time="2017-10-10T16:06:31.438034467+05:30" level=error msg="Handler for GET /v1.24/n...
Oct 10 16:06:32 DEE-Wrk-C-1.cisco.com dockerd[15732]: time="2017-10-10T16:06:32.881466760+05:30" level=info msg="Node join event for...1.123"
Oct 10 16:06:50 DEE-Wrk-C-1.cisco.com dockerd[15732]: time="2017-10-10T16:06:50.655276910+05:30" level=info msg="Node join event for...1.122"
Oct 10 16:07:02 DEE-Wrk-C-1.cisco.com dockerd[15732]: time="2017-10-10T16:07:02.304818938+05:30" level=info msg="Node join event for...1.121"
Oct 10 16:07:02 DEE-Wrk-C-1.cisco.com dockerd[15732]: time="2017-10-10T16:07:02.882310181+05:30" level=info msg="Node join event for...1.122"
Hint: Some lines were ellipsized, use -l to show in full.

Please re-open this issue. attaching herewith the worker node logs. 
[dee-wrk-c-1.tar.gz](https://github.com/contiv/netplugin/files/1371543/dee-wrk-c-1.tar.gz)

**Comment by blaksmit** [comment]
Closing per call with UCS team on 10/26. Rajesh confirmed this is no longer seen.
